[[data]]
"अङ्गम्" = 'प्लुतान्वितं'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'विकल्पः'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '"सर्व एव प्लुतः साहसमनिच्छता विभाषा कर्त्तव्यः" इति पतञ्जलिः।'
"प्रभावोदाहरणम्" = '''
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''



[[data]]
"अङ्गम्" = 'अशूद्रम् अस्त्रिकं नाम|गोत्रं|भोः'
"प्रत्ययः/ विवक्षा" = 'सम्बोधनं वाक्यान्ते प्रत्यभिवादने'
"परिणामः" = 'टेः प्लुत उदात्तः (क्वचिद् विकल्पेन)'
"प्रासिद्ध्यम्" = '३'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'प्रत्यभिवादेऽशूद्रे। (स्त्रियां न। भोराजन्यविशां वेति वाच्यम्।)'
"प्रभावोदाहरणम्" = '''भो आयुष्मान् एधि देवदत्ता꣡ ३ ॥  
विकल्पेन - आयुष्मानेधि भोः3 । आयुष्मानेधीन्द्रवर्म3न् । आयुष्मानेधीन्द्रपालित3 ॥
'''
"अभावोदाहरणम्" = 'आयुष्मानेधि तुषजक। भो आयुष्मती भव गार्गि ॥ आयुष्मानेधि ।'
"विवरणम्" = ''


[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'सम्बोधनं दूरात्, वाक्यान्ते'
"परिणामः" = 'टेः प्लुतः (एकश्रुतिः)'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = ' दूराद्धूते च'
"प्रभावोदाहरणम्" = '''आगच्छ यज्ञदत्ता ३ ॥  
पलायस्व देवदत्ता ३ ॥
'''
"अभावोदाहरणम्" = 'समीपस्थागच्छ देवदत्त। आगच्छ। '
"विवरणम्" = ''


[[data]]
"अङ्गम्" = 'है हे'
"प्रत्ययः/ विवक्षा" = 'सम्बोधनं दूरात्'
"परिणामः" = 'टेः प्लुतः (एकश्रुतिः)'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = ' हैहेप्रयोगे हैहयोः'
"प्रभावोदाहरणम्" = '''है ३ देवदत्त।   
 हे ३ देवदत्त। 
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''


[[data]]
"अङ्गम्" = 'प्लुतान्वितं नाम|गोत्रं'
"प्रत्ययः/ विवक्षा" = 'सम्बोधनं दूरात्'
"परिणामः" = 'कस्यचन गुरोः ॠॡभिन्नस्य प्लुतो विकल्पेन'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'गुरोरनृतोऽनन्त्यस्याप्येकैकस्य प्राचाम्'
"प्रभावोदाहरणम्" = '''हे दे꣡३वदत्त  
देवद꣡३त्त
'''
"अभावोदाहरणम्" = 'कृष्णमि꣡३त्र'
"विवरणम्" = ''



[[data]]
"अङ्गम्" = 'ॐ'
"प्रत्ययः/ विवक्षा" = 'ग्रन्थारम्भे'
"परिणामः" = 'प्लुत उदात्तः'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'ओमभ्यादाने'
"प्रभावोदाहरणम्" = '''
ओ३म् अ॒॒ग्निमीले॑ पु॒॒रोहि॑तं य॒॒ज्ञस्य॑ दे॒॒वमृ॒॒त्विजं॑ ॥
'''
"अभावोदाहरणम्" = 'ओमित्येतदक्षरमुद्गीथमुपासीत'
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'ये'
"प्रत्ययः/ विवक्षा" = 'यजामहे इत्यस्मात् प्राक् यज्ञे'
"परिणामः" = 'प्लुत उदात्तः'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'ये यज्ञकर्मणि'
"प्रभावोदाहरणम्" = '''
ये3 यजामहे।
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''


[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'मन्त्रान्ते यज्ञे'
"परिणामः" = 'टेः ओ३म्'
"प्रासिद्ध्यम्" = '३'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'प्रणवष् टेः'
"प्रभावोदाहरणम्" = '''
 देवाञ् जिगाति सुम्नयो꣡ ३म् ॥
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''


[[data]]
"अङ्गम्" = 'याज्याऽन्तः'
"प्रत्ययः/ विवक्षा" = 'यज्ञकर्मणि'
"परिणामः" = 'टेः प्लुत उदात्तः'
"प्रासिद्ध्यम्" = '३'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'याज्याऽन्तः'
"प्रभावोदाहरणम्" = '''स्तोमैर्विधेमाग्नये३  
जिह्वामग्ने चकृषे हव्यवाहा३म्
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''


[[data]]
"अङ्गम्" = 'ब्रूहि, प्रेष्य, श्रौषट्, वौषट्, आवह'
"प्रत्ययः/ विवक्षा" = 'यज्ञकर्म्मणि'
"परिणामः" = 'आदेः प्लुत उदात्तः'
"प्रासिद्ध्यम्" = '३'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'ब्रूहिप्रेस्यश्रौषड्वौषडावहानाम् आदेः'
"प्रभावोदाहरणम्" = '''
प्रे꣡३ष्य, अस्तु श्रौ꣡३षट्; सोमस्याग्ने वीही३ वौ꣡३षट्, अग्निमा꣡३वह ॥
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''


[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'अग्नीत्-प्रेषणे यज्ञे'
"परिणामः" = 'आदेः परस्य च प्लुत उदात्तः'
"प्रासिद्ध्यम्" = '३'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'अग्नीत्प्रेषणे परस्य च'
"प्रभावोदाहरणम्" = '''
आ३श्रा३वय, ओ३श्रा३वय ॥
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''


[[data]]
"अङ्गम्" = 'हि'
"प्रत्ययः/ विवक्षा" = 'प्रतिवचने'
"परिणामः" = 'टेः प्लुतो वा'
"प्रासिद्ध्यम्" = '४'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'विभाषा पृष्टप्रतिवचने हेः'
"प्रभावोदाहरणम्" = '''
अकार्षीः कटं देवदत्त ? अकार्षं ही꣡ ३ or अकार्षं हि ॥ 
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''


[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'वादे निग्रहात् परम्'
"परिणामः" = 'टेः प्लुत उदात्तः वा'
"प्रासिद्ध्यम्" = '३'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'निगृह्यानुयोगे च'
"प्रभावोदाहरणम्" = '''
"अनित्यः शब्दः"। इत्यस्य प्रत्याख्याने - अनित्यः शब्द इत्यात्था꣡३ अनित्य शब्द इत्यात्थ ॥
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = 'स्वमतात्प्रच्यावनं निग्रहः ॥ अनुयोगस्तस्य मतस्याविष्करणम् ॥'


[[data]]
"अङ्गम्" = 'आम्रेडितं'
"प्रत्ययः/ विवक्षा" = 'भर्त्सने'
"परिणामः" = 'एकतरस्य टेः प्लुत उदात्तः'
"प्रासिद्ध्यम्" = '४'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'आम्रेडितं भर्त्सने'
"प्रभावोदाहरणम्" = '''चौर꣡ चौरा꣡३॥ चौर꣡ चौरा꣡३ ॥  
वृषल वृषला꣡३ बन्धयिष्यामि त्वा, दस्य दस्यो३
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''


[[data]]
"अङ्गम्" = 'अङ्ग + तिङन्तम्'
"प्रत्ययः/ विवक्षा" = 'भर्त्सनेे'
"परिणामः" = 'टेः प्लुत उदात्तः'
"प्रासिद्ध्यम्" = '३'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'अङ्गयुक्तं तिङ् आकाङ्क्षम्'
"प्रभावोदाहरणम्" = '''
अङ्ग कूजा꣡ ३ इदानीं ज्ञास्यसि जाल्म ॥'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''


[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'विचार्यमाणानाम् वेदे'
"परिणामः" = 'टेः प्लुत उदात्तः'
"प्रासिद्ध्यम्" = '४'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'विचार्यमाणानाम्'
"प्रभावोदाहरणम्" = '''
  होतव्यं दीक्षितस्य गृहा३इ न होतव्या꣡३म् 
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''


[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'विचार्यमाणानाम् भाषायाम्'
"परिणामः" = 'प्रथमविकल्पस्य टेः प्लुत उदात्तः'
"प्रासिद्ध्यम्" = '४'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'पूर्वं तु भाषायाम्'
"प्रभावोदाहरणम्" = '''
 अहिर् नू꣡३ रज्जुर् नु
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''


[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'प्रतिश्रवणे'
"परिणामः" = 'टेः प्लुत उदात्तः'
"प्रासिद्ध्यम्" = '४'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'प्रतिश्रवणे च'
"प्रभावोदाहरणम्" = '''
गां मे देहि भोः, 1. हन्त ते ददामि꣡ ३ ॥
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''


[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'प्रश्नान्ते अभिपूजिते '
"परिणामः" = 'टेः प्लुतो ऽनुदात्तः'
"प्रासिद्ध्यम्" = '३'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'अनुदात्तं प्रश्नान्ताभिपूजितयोः'
"प्रभावोदाहरणम्" = '''
अगमा꣡३ः पूर्वा꣡३म् ग्रामा꣡३न् अग्निभूता॒३इ  
शोभनः खल्वसि माणवका॒३ ॥ 
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''


[[data]]
"अङ्गम्" = 'चित् (उपमार्थे) .*'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'टेः  प्लुतो ऽनुदात्तः'
"प्रासिद्ध्यम्" = '३'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'चिदिति चोपमाऽर्थे प्रयुज्यमाने'
"प्रभावोदाहरणम्" = '''
 अग्निचिद् भाया॒३त्
'''
"अभावोदाहरणम्" = ' कथं चिद् आहुः ॥'
"विवरणम्" = ''


[[data]]
"अङ्गम्" = 'उपरिस्विदासीदिति च'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'टेः प्लुतो ऽनुदात्तः'
"प्रासिद्ध्यम्" = '१'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'उपरिस्विदासीदिति च'
"प्रभावोदाहरणम्" = '''
 उपरि स्विदासी॒३त्
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''


[[data]]
"अङ्गम्" = 'आम्रेडितम्'
"प्रत्ययः/ विवक्षा" = 'असूयायां सम्मतौ कोपे कुत्सने'
"परिणामः" = 'पूर्वस्य टेः प्लुतः स्वरितः'
"प्रासिद्ध्यम्" = '३'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'स्वरितमाम्रेडितेऽसूयासम्मतिकोपकुत्सनेषु'
"प्रभावोदाहरणम्" = '''
माणवका॑३ माणवक, अ꣡भिरूपका॑३ अभिरूपक शोभनः खल्वसि ॥
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''


[[data]]
"अङ्गम्" = 'तिङन्तं साकाङ्क्षं'
"प्रत्ययः/ विवक्षा" = 'आचारभेदः, आशीः, प्रेषः'
"परिणामः" = 'टेः प्लुतः स्वरितः'
"प्रासिद्ध्यम्" = '३'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = ' क्षियाऽऽशीःप्रैषेषु तिङ् आकाङ्क्षम्'
"प्रभावोदाहरणम्" = '''
स्वयं रथेन या꣡ति॑३, उपाध्यायं पदातिं गमयति ॥  
स्वयं ओदनं भुङ्क्ते३, उपाध्यायं सक्तून् पाययति ॥  
सुतांश्च लप्सीष्ठा३, धनं च तात; छन्दोध्येषीष्ठा॑३ व्याकरणं च, भद्र ॥  
कटं कुरू॑३ ग्रामं च गच्छ; यवान् लुनीहि॑३, सक्तू॑श्च पिब ॥
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''


[[data]]
"अङ्गम्" = 'तिङन्तं साकाङ्क्षं'
"प्रत्ययः/ विवक्षा" = 'प्रश्नाख्यानयोः'
"परिणामः" = 'पूर्वस्य टेः प्लुतः स्वरितः'
"प्रासिद्ध्यम्" = '३'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'अनन्त्यस्यापि प्रश्नाख्यानयोः'
"प्रभावोदाहरणम्" = '''
आगमा॑३ः पूर्वा॑३न् ग्रामा॑३न् अग्निभूता॑३इ?  
आगमा॑३ः पुर्वा॑३न् ग्रामा॑३न् भोः॑३ ॥
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''


[[data]]
"अङ्गम्" = 'प्लुत एच्'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'प्लुतः इद् |उत्'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'प्लुतावैच इदुतौ'
"प्रभावोदाहरणम्" = '''
अ + इ३, अ + उ३
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''



[[data]]
"अङ्गम्" = 'प्लुत एच् अप्रगृह्यः, ८३,९०,९७,१०० इति सूत्रेभ्यो लब्धः'
"प्रत्ययः/ विवक्षा" = 'अदूरात्'
"परिणामः" = 'पूर्वः प्लुतः + (इद् |उत्)'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'एचोऽप्रगृह्यस्यादूराद्धूते पूर्वस्यार्धस्यादुत्तरस्येदुतौ'
"प्रभावोदाहरणम्" = '''
अगमा३: पूर्वा३न् ग्रामा३न् अग्निभूता३इ꣡ ॥
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'प्लुत एच् अप्रगृह्यः, ८३,९०,९७,१०० इति सूत्रेभ्यो लब्धः'
"प्रत्ययः/ विवक्षा" = 'स्वरेण संहितायाम्'
"परिणामः" = 'य्|व्'
"प्रासिद्ध्यम्" = '४'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'तयोर्य्वावचि संहितायाम्'
"प्रभावोदाहरणम्" = '''
अग्ना३याशा, पटा३वाशा, अग्ना३यिन्द्रम्, पटा३वुदकम् ॥ 
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''