[[data]]
"वर्णः" = 'अ'
"स्थानम्" = 'कण्ठ'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = 'नासिका विकल्पेन'
"आभ्यन्तरप्रयत्नः" = '''
विवृत
प्रयोगे संवृतः ह्रस्वस्य।'''
"बाह्यप्रयत्नः" = 'उदात्त-अनुदात्त-स्वरित'
"प्राणः (बाह्यप्रयत्ने)" = 'ह्रस्व-दीर्घ-प्लुत'
"संज्ञा १" = 'अच् स्वरः'
"विवरणम्" = 'अकुहविसर्जनीयानां कण्ठः। इचुयशानां तालु। ऋटुरषाणां मूर्धा। ऌतुलसानां दन्ताः। उपूपध्मानीयानामोष्ठौ। ञमङणनानां नासिका च। एदैतोः कण्ठ तालु। ओदौतोः कण्ठोष्टम्। वकारस्य दन्तोष्ठम्। जिह्वामूलीयस्य जिह्वामूलम्। नासिकानुस्वारस्य।'

[[data]]
"वर्णः" = 'इ'
"स्थानम्" = 'तालु'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = 'नासिका विकल्पेन'
"आभ्यन्तरप्रयत्नः" = 'विवृत'
"बाह्यप्रयत्नः" = 'उदात्त-अनुदात्त-स्वरित'
"प्राणः (बाह्यप्रयत्ने)" = 'ह्रस्व-दीर्घ-प्लुत'
"संज्ञा १" = 'अच् स्वरः'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'उ'
"स्थानम्" = 'ओष्ठौ'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = 'नासिका विकल्पेन'
"आभ्यन्तरप्रयत्नः" = 'विवृत'
"बाह्यप्रयत्नः" = 'उदात्त-अनुदात्त-स्वरित'
"प्राणः (बाह्यप्रयत्ने)" = 'ह्रस्व-दीर्घ-प्लुत'
"संज्ञा १" = 'अच् स्वरः'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'ऋ'
"स्थानम्" = 'मूर्धा'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = 'नासिका विकल्पेन'
"आभ्यन्तरप्रयत्नः" = 'विवृत'
"बाह्यप्रयत्नः" = 'उदात्त-अनुदात्त-स्वरित'
"प्राणः (बाह्यप्रयत्ने)" = 'ह्रस्व-प्लुत'
"संज्ञा १" = 'अच् स्वरः'
"विवरणम्" = 'buzzing रेफः।'

[[data]]
"वर्णः" = 'ऌ'
"स्थानम्" = 'दन्त'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = 'नासिका विकल्पेन'
"आभ्यन्तरप्रयत्नः" = 'विवृत'
"बाह्यप्रयत्नः" = 'उदात्त-अनुदात्त-स्वरित'
"प्राणः (बाह्यप्रयत्ने)" = 'ह्रस्व-प्लुत'
"संज्ञा १" = 'अच् स्वरः'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'ए'
"स्थानम्" = 'कण्ठ'
"द्वितीयस्थानम्" = 'तालु'
"अपरं स्थानम्" = 'नासिका विकल्पेन'
"आभ्यन्तरप्रयत्नः" = 'विवृत'
"बाह्यप्रयत्नः" = 'उदात्त-अनुदात्त-स्वरित'
"प्राणः (बाह्यप्रयत्ने)" = 'दीर्घ-प्लुत'
"संज्ञा १" = 'अच् स्वरः, सन्ध्यक्षरः'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'ऐ'
"स्थानम्" = 'कण्ठ'
"द्वितीयस्थानम्" = 'तालु'
"अपरं स्थानम्" = 'नासिका विकल्पेन'
"आभ्यन्तरप्रयत्नः" = 'विवृत'
"बाह्यप्रयत्नः" = 'उदात्त-अनुदात्त-स्वरित'
"प्राणः (बाह्यप्रयत्ने)" = 'दीर्घ'
"संज्ञा १" = 'अच् स्वरः, सन्ध्यक्षरः, समाहारः'
"विवरणम्" = 'आइ इति केचित्।'

[[data]]
"वर्णः" = 'ओ'
"स्थानम्" = 'कण्ठ'
"द्वितीयस्थानम्" = 'ओष्ठ'
"अपरं स्थानम्" = 'नासिका विकल्पेन'
"आभ्यन्तरप्रयत्नः" = 'विवृत'
"बाह्यप्रयत्नः" = 'उदात्त-अनुदात्त-स्वरित'
"प्राणः (बाह्यप्रयत्ने)" = 'दीर्घ-प्लुत'
"संज्ञा १" = 'अच् स्वरः, सन्ध्यक्षरः'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'औ'
"स्थानम्" = 'कण्ठ'
"द्वितीयस्थानम्" = 'ओष्ठ'
"अपरं स्थानम्" = 'नासिका विकल्पेन'
"आभ्यन्तरप्रयत्नः" = 'विवृत'
"बाह्यप्रयत्नः" = 'उदात्त-अनुदात्त-स्वरित'
"प्राणः (बाह्यप्रयत्ने)" = 'दीर्घ'
"संज्ञा १" = 'अच् स्वरः, सन्ध्यक्षरः, समाहारः'
"विवरणम्" = 'आउ इति केचित्।'

[[data]]
"वर्णः" = 'क'
"स्थानम्" = 'कण्ठ'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'विवार-श्वास-अघोष'
"प्राणः (बाह्यप्रयत्ने)" = 'अल्प'
"संज्ञा १" = 'कु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'ख'
"स्थानम्" = 'कण्ठ'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'विवार-श्वास-अघोष'
"प्राणः (बाह्यप्रयत्ने)" = 'महा'
"संज्ञा १" = 'कु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'ग'
"स्थानम्" = 'कण्ठ'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'अल्प'
"संज्ञा १" = 'कु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'घ'
"स्थानम्" = 'कण्ठ'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'महा'
"संज्ञा १" = 'कु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'ङ'
"स्थानम्" = 'कण्ठ'
"द्वितीयस्थानम्" = 'नासिका'
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'अल्प'
"संज्ञा १" = 'कु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'च'
"स्थानम्" = 'तालु'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'विवार-श्वास-अघोष'
"प्राणः (बाह्यप्रयत्ने)" = 'अल्प'
"संज्ञा १" = 'चु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'छ'
"स्थानम्" = 'तालु'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'विवार-श्वास-अघोष'
"प्राणः (बाह्यप्रयत्ने)" = 'महा'
"संज्ञा १" = 'चु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'ज'
"स्थानम्" = 'तालु'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'अल्प'
"संज्ञा १" = 'चु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'झ'
"स्थानम्" = 'तालु'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'महा'
"संज्ञा १" = 'चु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'ञ'
"स्थानम्" = 'तालु'
"द्वितीयस्थानम्" = 'नासिका'
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'अल्प'
"संज्ञा १" = 'चु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'ट'
"स्थानम्" = 'मूर्धा'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'विवार-श्वास-अघोष'
"प्राणः (बाह्यप्रयत्ने)" = 'अल्प'
"संज्ञा १" = 'टु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'ठ'
"स्थानम्" = 'मूर्धा'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'विवार-श्वास-अघोष'
"प्राणः (बाह्यप्रयत्ने)" = 'महा'
"संज्ञा १" = 'टु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'ड'
"स्थानम्" = 'मूर्धा'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'अल्प'
"संज्ञा १" = 'टु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'ढ'
"स्थानम्" = 'मूर्धा'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'महा'
"संज्ञा १" = 'टु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'ण'
"स्थानम्" = 'मूर्धा'
"द्वितीयस्थानम्" = 'नासिका'
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'अल्प'
"संज्ञा १" = 'टु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'त'
"स्थानम्" = 'दन्त'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'विवार-श्वास-अघोष'
"प्राणः (बाह्यप्रयत्ने)" = 'अल्प'
"संज्ञा १" = 'तु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'थ'
"स्थानम्" = 'दन्त'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'विवार-श्वास-अघोष'
"प्राणः (बाह्यप्रयत्ने)" = 'महा'
"संज्ञा १" = 'तु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'द'
"स्थानम्" = 'दन्त'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'अल्प'
"संज्ञा १" = 'तु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'ध'
"स्थानम्" = 'दन्त'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'महा'
"संज्ञा १" = 'तु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'न'
"स्थानम्" = 'दन्त'
"द्वितीयस्थानम्" = 'नासिका'
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'अल्प'
"संज्ञा १" = 'तु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'प'
"स्थानम्" = 'ओष्ठौ'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'विवार-श्वास-अघोष'
"प्राणः (बाह्यप्रयत्ने)" = 'अल्प'
"संज्ञा १" = 'पु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'फ'
"स्थानम्" = 'ओष्ठौ'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'विवार-श्वास-अघोष'
"प्राणः (बाह्यप्रयत्ने)" = 'महा'
"संज्ञा १" = 'पु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'ब'
"स्थानम्" = 'ओष्ठौ'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'अल्प'
"संज्ञा १" = 'पु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'भ'
"स्थानम्" = 'ओष्ठौ'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'महा'
"संज्ञा १" = 'पु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'म'
"स्थानम्" = 'ओष्ठौ'
"द्वितीयस्थानम्" = 'नासिका'
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'स्पृष्ट'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'अल्प'
"संज्ञा १" = 'पु'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'य'
"स्थानम्" = 'तालु'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = 'नासिका विकल्पेन'
"आभ्यन्तरप्रयत्नः" = 'ईषत्स्पृष्ट'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'अल्प'
"संज्ञा १" = 'अन्तःस्था'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'र १'
"स्थानम्" = 'दन्तमूल्यम्'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = 'नासिका विकल्पेन'
"आभ्यन्तरप्रयत्नः" = 'ईषत्स्पृष्ट'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'अल्प'
"संज्ञा १" = 'अन्तःस्था'
"विवरणम्" = '''
दन्तमूल्यम् इति ऋग्वेदप्रातिशाख्यम्'''

[[data]]
"वर्णः" = 'र २'
"स्थानम्" = 'मूर्धा'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = 'नासिका विकल्पेन'
"आभ्यन्तरप्रयत्नः" = 'ईषत्स्पृष्ट'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'अल्प'
"संज्ञा १" = 'अन्तःस्था'
"विवरणम्" = 'मूर्धा इति पाणिनीयशिक्षा'

[[data]]
"वर्णः" = 'र ३'
"स्थानम्" = 'दन्तम्'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = 'नासिका विकल्पेन'
"आभ्यन्तरप्रयत्नः" = 'ईषत्स्पृष्ट'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'अल्प'
"संज्ञा १" = 'अन्तःस्था'
"विवरणम्" = 'कानिचन तन्त्राणि'

[[data]]
"वर्णः" = 'ल'
"स्थानम्" = 'दन्त'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = 'नासिका विकल्पेन'
"आभ्यन्तरप्रयत्नः" = 'ईषत्स्पृष्ट'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'अल्प'
"संज्ञा १" = 'अन्तःस्था'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'व'
"स्थानम्" = 'दन्त'
"द्वितीयस्थानम्" = 'ओष्ठ'
"अपरं स्थानम्" = 'नासिका विकल्पेन'
"आभ्यन्तरप्रयत्नः" = 'ईषत्स्पृष्ट'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'अल्प'
"संज्ञा १" = 'अन्तःस्था'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'श'
"स्थानम्" = 'तालु'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'ईषद्विवृत'
"बाह्यप्रयत्नः" = 'विवार-श्वास-अघोष'
"प्राणः (बाह्यप्रयत्ने)" = 'महा'
"संज्ञा १" = 'उष्माण'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'ष'
"स्थानम्" = 'मूर्धा'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'ईषद्विवृत'
"बाह्यप्रयत्नः" = 'विवार-श्वास-अघोष'
"प्राणः (बाह्यप्रयत्ने)" = 'महा'
"संज्ञा १" = 'उष्माण'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'स'
"स्थानम्" = 'दन्त'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'ईषद्विवृत'
"बाह्यप्रयत्नः" = 'विवार-श्वास-अघोष'
"प्राणः (बाह्यप्रयत्ने)" = 'महा'
"संज्ञा १" = 'उष्माण'
"विवरणम्" = ''

[[data]]
"वर्णः" = 'ह'
"स्थानम्" = 'कण्ठ, क्वचिद् उरः'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = 'ईषद्विवृत'
"बाह्यप्रयत्नः" = 'संवार-नाद-घोष'
"प्राणः (बाह्यप्रयत्ने)" = 'महा'
"संज्ञा १" = 'उष्माण'
"विवरणम्" = '''
पाणिनीय-शिक्षा - "अन्तस्थैर् वा पञ्चमैर् युक्तः उरस्कः, अन्यथा कण्ठजः।"  
"हकारं पञ्चमैर्युक्तं अन्तःस्थाभिश्च संयुतम् । उरस्यं तं विजानीयात् ....॥" -> इत्यनेन ह्मवचनं म्हवत् कार्यम् इति केचित् पाणिनीयशिक्षानुयायिनः।'''

[[data]]
"वर्णः" = ' ं'
"स्थानम्" = ''
"द्वितीयस्थानम्" = 'नासिका'
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = ''
"बाह्यप्रयत्नः" = ''
"प्राणः (बाह्यप्रयत्ने)" = ''
"संज्ञा १" = 'अयोगवाहः'
"विवरणम्" = 'अनुस्वारयमानाञ्च नासिकास्थानमुच्यते।'

[[data]]
"वर्णः" = ' ः'
"स्थानम्" = 'कण्ठ। पूर्वान्तसस्थानम्।'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = ''
"बाह्यप्रयत्नः" = ''
"प्राणः (बाह्यप्रयत्ने)" = ''
"संज्ञा १" = 'अयोगवाहः'
"विवरणम्" = '''
"विसर्जनीयानुस्वारौ भजेते पूर्वमक्षरम्" इति ऋग्वेदप्रातिशाख्ये।
"कण्ठस्थानौ हकारविसर्जनीयौ ४६ उदयस्वरादिसस्थानो हकारं एकेषाम् ४७ पूर्वान्तसस्थानो विसर्जनीयः।
ख़वत् क्वचित् श्रुतम्। " इति तैत्तिरीयप्रातिशाख्ये।
पूर्वस्वरस्य पुनरुच्चारणम् न भवतीति धनञ्जयः।'''

[[data]]
"वर्णः" = ' जिह्वामूलीयौ'
"स्थानम्" = 'जिह्वामूल'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = ''
"बाह्यप्रयत्नः" = ''
"प्राणः (बाह्यप्रयत्ने)" = ''
"संज्ञा १" = ''
"विवरणम्" = 'बालೱकरोति। जिह्वामूलस्य तालुमूले स्पर्श।'

[[data]]
"वर्णः" = ' उपद्मनीयौ'
"स्थानम्" = 'ओष्ठौ'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = ''
"बाह्यप्रयत्नः" = ''
"प्राणः (बाह्यप्रयत्ने)" = ''
"संज्ञा १" = ''
"विवरणम्" = 'बालೲपीबते'

[[data]]
"वर्णः" = 'ह्+अनुनासिकम्'
"स्थानम्" = 'उरस्'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = ''
"बाह्यप्रयत्नः" = ''
"प्राणः (बाह्यप्रयत्ने)" = ''
"संज्ञा १" = ''
"विवरणम्" = ''

[[data]]
"वर्णः" = 'ह्_यरलव'
"स्थानम्" = 'उरस्'
"द्वितीयस्थानम्" = ''
"अपरं स्थानम्" = ''
"आभ्यन्तरप्रयत्नः" = ''
"बाह्यप्रयत्नः" = ''
"प्राणः (बाह्यप्रयत्ने)" = ''
"संज्ञा १" = ''
"विवरणम्" = ''
