[[data]]
"अव्ययम्" = ''
"अर्थः" = ''
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = ''
"संज्ञा १" = ''
"संज्ञा ३" = ''
"नित्यता" = ''
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'अव्ययीभावः ।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = ''
"अर्थः" = ''
"अन्यपदस्थितिः" = 'अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु'
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययीभावः'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = ''
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '''
अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।
अव्ययम् इति योगविभागः।'''
"उदाहरण-विग्रहः" = 'दिशयोः मध्यः = दिशा अप'
"समस्तपदम् उदाहरणम्" = 'अपदिशा - अपदिश- अपदिशम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'अधि'
"अर्थः" = 'विभक्त्यर्थे'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = 'हरौ इति'
"समस्तपदम् उदाहरणम्" = 'अधिहरि'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'उप / समीपार्थे यत् न समया निकषा आरात्'
"अर्थः" = 'समीपार्थे'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = 'वृक्षस्य समीपम्'
"समस्तपदम् उदाहरणम्" = 'उपवृक्षम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'अति'
"अर्थः" = 'अत्ययार्थे = ध्वंसः'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '?‌अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = 'हिमस्य अत्ययः'
"समस्तपदम् उदाहरणम्" = 'अतिहिमम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'अति'
"अर्थः" = 'असंप्रत्यर्थे - न संप्रति युज्यते'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '?‌अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = 'निद्रा संप्रतिः न युज्यते'
"समस्तपदम् उदाहरणम्" = 'अतिनिद्रम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'अनु (न पश्चात्)'
"अर्थः" = 'पश्चादर्थे'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'न पश्चाद्विष्णुः इत्यादि - भाष्यप्रयोगबलात्।'
"उदाहरण-विग्रहः" = 'विष्णोः पश्चात्'
"समस्तपदम् उदाहरणम्" = 'अनुविष्णु'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'अनु'
"अर्थः" = 'योग्यतार्थे'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '?‌अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = '''
रूपस्य योग्यम्
'''
"समस्तपदम् उदाहरणम्" = 'अनुरूपम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'अनु'
"अर्थः" = 'आनुपूर्व्यर्थे'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '?‌अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = 'ज्येष्टम् अनुसृत्य'
"समस्तपदम् उदाहरणम्" = 'अनुज्येष्टम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'आ'
"अर्थः" = 'मर्यादार्थे'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '?‌अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = '''
आदिनम्
आहिमालयम्'''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'आ'
"अर्थः" = 'अभिविद्ध्यर्थे'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '?‌अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = 'आ बालेभ्यः (हरिभक्तिः)'
"समस्तपदम् उदाहरणम्" = 'आबालम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'इति'
"अर्थः" = 'प्रादुर्भावः'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '?‌अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = 'हरेः प्रकाशः/ कीर्तनम् अस्ति इति'
"समस्तपदम् उदाहरणम्" = 'इतिहरि'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'दुर्'
"अर्थः" = 'व्यृद्धिः'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '?‌अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = 'यवनानां व्यृद्धिः'
"समस्तपदम् उदाहरणम्" = 'दुर्यवनम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'निर्'
"अर्थः" = 'अभावे'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '?‌अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = 'यवनानाम् अभावः'
"समस्तपदम् उदाहरणम्" = 'निर्यवनम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = ''
"अर्थः" = ''
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = ''
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '?‌अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = 'अग्निम् अभिमुखः'
"समस्तपदम् उदाहरणम्" = 'अभ्यग्नि'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'पारे'
"अर्थः" = ''
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '?‌अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = 'गङ्गायाः पारे'
"समस्तपदम् उदाहरणम्" = 'पारेगङ्गम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'प्रति'
"अर्थः" = 'वीप्सार्थे'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '?‌अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = 'वृक्षं वृक्षं प्रति'
"समस्तपदम् उदाहरणम्" = 'प्रतिवृक्षम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'यथा असादृश्ये'
"अर्थः" = 'पदार्थानतिवृत्तिः'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '?‌अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = 'शक्तिम् अनतिक्रम्य'
"समस्तपदम् उदाहरणम्" = '''
यथाशक्ति
यथाकर्म'''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'यथा असादृश्ये'
"अर्थः" = 'योग्यता'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '?‌अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'यथा असादृश्ये'
"अर्थः" = 'वीप्सार्थे'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '?‌अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'सह कालवाचकः'
"अर्थः" = 'यौगपत्ये इत्यादौ'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '?‌अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = 'सहपूर्वाह्नम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'सं'
"अर्थः" = 'समृद्धिः'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = '२'
"परिणामः" = ''
"सूत्रम्" = '?‌अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = 'मद्राणाम् समृद्धिः'
"समस्तपदम् उदाहरणम्" = 'संमद्रम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'सह'
"अर्थः" = '''
सादृश्यार्थे
'''
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = '४'
"परिणामः" = ''
"सूत्रम्" = '?‌अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = 'हरिसदृशः'
"समस्तपदम् उदाहरणम्" = 'सहरि'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'सह'
"अर्थः" = 'संपत्त्यर्थे (अनुरूपः आत्मभावः)'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = '२'
"परिणामः" = ''
"सूत्रम्" = '?‌अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = 'क्षत्रियाणाम् अनुरूपं‌ कर्म'
"समस्तपदम् उदाहरणम्" = 'सक्षत्रम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'सह'
"अर्थः" = 'यौगपद्ये'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = '५'
"परिणामः" = ''
"सूत्रम्" = 'अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = 'सशक्रम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'सह'
"अर्थः" = 'साकल्यार्थे'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '?‌अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = 'सतृणम् खादति'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'सह'
"अर्थः" = 'अन्तवचनेषु'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '?‌अव्ययम् विभक्ति-समीप-समृद्धि-व्यृद्धि-अर्थाभाव-अत्यय-असंप्रति-शब्दप्रादुर्भाव-पश्चात्-यथा-आनुपूर्व्य-यौगपद्य-सादृश्य-सम्पत्ति-साकल्य-अन्तवचनेषु।'
"उदाहरण-विग्रहः" = 'अग्निग्रन्थपर्यन्तम् अधीते'
"समस्तपदम् उदाहरणम्" = 'साग्निः'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'यथा'
"अर्थः" = 'असादृश्ये'
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = ''
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'यथाऽसादृश्ये (एव समस्यते)'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'यावत् (अव्ययम्, नानव्ययम्)'
"अर्थः" = ''
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'यावत् अवधारणे'
"उदाहरण-विग्रहः" = 'यावन्तः श्लोकाः तावन्तः अच्युतप्रणामः'
"समस्तपदम् उदाहरणम्" = 'यावच्छोकम्'
"विवरणम्" = 'अवधारणम् = मात्रा स्पष्टा'
"अभावोदाहरणम्" = 'यावद् दत्तं‌तावद् भुक्तम्।'

[[data]]
"अव्ययम्" = 'प्रति'
"अर्थः" = 'मात्रार्थे'
"अन्यपदस्थितिः" = 'सुँप्'
"अव्यय-निपातः" = 'उत्तरम्'
"संज्ञा १" = 'अव्ययोत्तरपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'सुँप् प्रतिना मात्रार्थे।'
"उदाहरण-विग्रहः" = 'सूपस्य लेशः'
"समस्तपदम् उदाहरणम्" = 'सूपप्रति'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'परि'
"अर्थः" = ''
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = ''
"संज्ञा १" = ''
"संज्ञा ३" = ''
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'अक्षशलाकासंख्याः परिणा'
"उदाहरण-विग्रहः" = 'अक्षेण विपरीतं वृत्तम्'
"समस्तपदम् उदाहरणम्" = '''
अक्षपरि
एकपरि शलाकापरि'''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = ''
"अर्थः" = ''
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = ''
"संज्ञा १" = ''
"संज्ञा ३" = ''
"नित्यता" = ''
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'अक्षशलाकासंख्याः परिणा ।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = ''
"अर्थः" = ''
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = ''
"संज्ञा १" = ''
"संज्ञा ३" = ''
"नित्यता" = ''
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'विभाषा ।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'अप परि बहिः'
"अर्थः" = 'वर्जनार्थे'
"अन्यपदस्थितिः" = 'पञ्चम्यन्तम्'
"अव्यय-निपातः" = ''
"संज्ञा १" = ''
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'अनित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '''
अपपरिबहिरञ्चवः पञ्चम्या (विभाषा)।
अस्मादेव ज्ञापकाद् बहिर्योगे पञ्चमी (लसिकौ)'''
"उदाहरण-विग्रहः" = 'अप विष्णोः'
"समस्तपदम् उदाहरणम्" = '''
अपविष्णु संसारः
बहिर्वनम्'''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'अञ्चु = प्राक्'
"अर्थः" = ''
"अन्यपदस्थितिः" = 'पञ्चम्यन्तम्'
"अव्यय-निपातः" = ''
"संज्ञा १" = ''
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'अनित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '''
अपपरिबहिरञ्चवः पञ्चम्या (विभाषा)।

'''
"उदाहरण-विग्रहः" = 'प्राक् वनात्'
"समस्तपदम् उदाहरणम्" = 'प्राग्वनम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'आ'
"अर्थः" = 'मर्यादाभिविध्योः'
"अन्यपदस्थितिः" = '५-अन्तम्'
"अव्यय-निपातः" = ''
"संज्ञा १" = ''
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'अनित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'आङ् मर्यादाभिविध्योः'
"उदाहरण-विग्रहः" = 'आमुक्तेः'
"समस्तपदम् उदाहरणम्" = 'आमिक्ति'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'प्रति'
"अर्थः" = 'लक्षणे आभिमुख्ये च'
"अन्यपदस्थितिः" = '५-अन्तम्'
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'अनित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'लक्षणेनाभिप्रती आभिमुख्ये'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = 'प्रत्यग्नि'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'अभि'
"अर्थः" = 'लक्षणे आभिमुख्ये च'
"अन्यपदस्थितिः" = '५-अन्तम्'
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'अनित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'लक्षणेनाभिप्रती आभिमुख्ये'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = 'अभ्यग्नि'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'अनु'
"अर्थः" = 'लक्षणे सामिप्ये'
"अन्यपदस्थितिः" = '५-अन्तम्'
"अव्यय-निपातः" = ''
"संज्ञा १" = ''
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'अनित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'अनुर्यत्समया ।'
"उदाहरण-विग्रहः" = 'वनस्य समीपं गतः।'
"समस्तपदम् उदाहरणम्" = 'अनुवनम् अशनिर् गतः।'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'अनु'
"अर्थः" = 'लक्षणे दैर्घ्ये च'
"अन्यपदस्थितिः" = '५-अन्तम्'
"अव्यय-निपातः" = ''
"संज्ञा १" = ''
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'अनित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'यस्य चायामः ।'
"उदाहरण-विग्रहः" = 'गङ्गया अनु वाराणसी'
"समस्तपदम् उदाहरणम्" = 'अनुगङ्गं वाराणसी'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = ''
"अर्थः" = ''
"अन्यपदस्थितिः" = ''
"अव्यय-निपातः" = ''
"संज्ञा १" = 'तिष्ठद्गु'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'अनित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'तिष्ठद्गुप्रभृतीनि च ।'
"उदाहरण-विग्रहः" = 'तिष्ठन्ती गो अस्मिन् काले इति'
"समस्तपदम् उदाहरणम्" = '''
तिष्ठद्गु
आयतीगवम्'''
"विवरणम्" = 'निपातनम् इदम्।'
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'मध्य पार'
"अर्थः" = ''
"अन्यपदस्थितिः" = '६-अन्तम्'
"अव्यय-निपातः" = 'पूर्वम्'
"संज्ञा १" = 'अव्ययपूर्वपदम्'
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'अनित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'पारे मध्ये षष्ठ्या वा ।'
"उदाहरण-विग्रहः" = 'गङ्गायाः मध्ये'
"समस्तपदम् उदाहरणम्" = 'मध्येगङ्गम्'
"विवरणम्" = 'निपातनात् एकारान्तः।'
"अभावोदाहरणम्" = 'गङ्गामध्यात् आनय। इत्यस्मिन् तत्पुरुषः। '

[[data]]
"अव्ययम्" = 'सङ्ख्या'
"अर्थः" = ''
"अन्यपदस्थितिः" = 'वंश-सूचकेन'
"अव्यय-निपातः" = ''
"संज्ञा १" = ''
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'अनित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'संख्या वंश्येन ।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = 'त्रिमुनि'
"विवरणम्" = 'वंशः जन्मना वा विद्यया'
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = 'सङ्ख्या'
"अर्थः" = ''
"अन्यपदस्थितिः" = 'नदी'
"अव्यय-निपातः" = ''
"संज्ञा १" = ''
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'अनित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'नदीभिश्च ।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = 'सप्तगङ्गम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"अव्ययम्" = ''
"अर्थः" = ''
"अन्यपदस्थितिः" = 'नदी संज्ञायाम्'
"अव्यय-निपातः" = ''
"संज्ञा १" = ''
"संज्ञा ३" = 'समासविधानम्'
"नित्यता" = 'नित्यम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'अन्यपदार्थे च संज्ञायाम्‌ ।'
"उदाहरण-विग्रहः" = 'गङ्गा उन्मत्ता इव यत्र'
"समस्तपदम् उदाहरणम्" = 'उन्मत्तगङ्गम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''
