[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = ''
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'सरूपाणामेकशेष एकविभक्तौ ।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"अन्योदाहराणि" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = ''
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'वृद्धो यूना तल्लक्षणश्चेदेव विशेषः ।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"अन्योदाहराणि" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = ''
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'स्त्री पुंवच्च ।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"अन्योदाहराणि" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = ''
"अवधानावश्यकता" = '५'
"परिणामः" = ''
"सूत्रम्" = 'पुमान् स्त्रिया ।'
"उदाहरण-विग्रहः" = 'अजश्च अजा च अजौ । हंसश्च हंसी च हंसौ ।'
"समस्तपदम् उदाहरणम्" = ''
"अन्योदाहराणि" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = ''
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'भ्रातृपुत्रौ स्वसृदुहितृभ्याम् ।'
"उदाहरण-विग्रहः" = '''
 भ्रातरौ
पुत्रश्च पुत्री च पुत्रौ । 
भ्राता च स्वसा (=भगिनी) च
'''
"समस्तपदम् उदाहरणम्" = ''
"अन्योदाहराणि" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = ''
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'नपुंसकमनपुंसकेनैकवच्चास्यान्यतरस्याम् ।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"अन्योदाहराणि" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = ''
"अवधानावश्यकता" = '५'
"परिणामः" = ''
"सूत्रम्" = 'पिता मात्रा ।'
"उदाहरण-विग्रहः" = 'पित च माता च पितरौ ।'
"समस्तपदम् उदाहरणम्" = ''
"अन्योदाहराणि" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = ''
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'श्वशुरः श्वश्र्वा ।'
"उदाहरण-विग्रहः" = 'श्वशुरश्च श्वश्रूश्च श्वशुरौ ।'
"समस्तपदम् उदाहरणम्" = ''
"अन्योदाहराणि" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = ''
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'त्यदादीनि सर्वैर्नित्यम् ।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"अन्योदाहराणि" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = ''
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'ग्राम्यपशुसंघेषु अतरुणेषु स्त्री ।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"अन्योदाहराणि" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''
