[[data]]
"सङ्केतितम्" = 'सूत्रे प्रथमाविभ्क्तिवत्पदेन निर्दिष्टं पदम्।'
"गणः\n" = 'पूर्वनिपाते'
"परिणामः" = 'उपसर्जनम्'
"अवधानावश्यकता" = ''
"सूत्रम्" = 'प्रथमानिर्दिष्टं समास उपसर्जनम्'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = '''
"अव्ययं सुपा" इति सूत्रेण समस्यमाने - 
दिशा + अप इत्येतयोः‌ "अप" उपसर्जनम्।
पूर्वनिपाते उपयुज्यते।'''
"अभावोदाहरणम्" = ''

[[data]]
"सङ्केतितम्" = '''
विग्रहे यत् नियतविभक्तिकम्।
न एकदेशिसमासे षष्ठ्यन्तम्।'''
"गणः\n" = 'न पूर्वनिपाते'
"परिणामः" = 'उपसर्जनम्'
"अवधानावश्यकता" = ''
"सूत्रम्" = '''
एकविभक्ति चापूर्वनिपाते।
एक-विभक्ताव् अषष्ठ्यन्तवचनम् (वा)'''
"उदाहरण-विग्रहः" = """
दिशयोः‌ मध्यम्/ दिशयोर् मध्यात् 
इत्यादिषु 'दिशयोः'"""
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = '''
 समासे विधीयमाने यन् नियतविभक्तिकं, द्वितीये सम्बन्धिनि बहुभिर्विभक्तिभिर् युज्यमाने ऽप्येकयैव विभक्त्या युज्यते तदुपसर्जनसंज्ञं भवति अपूर्वनिपाते।
ह्रस्वः उपसर्जनस्य॥ इत्यत्र प्रयोजनम्।'''
"अभावोदाहरणम्" = 'पिप्पल्याः अर्धं = अर्धपिप्पली, पिप्पल्याः पूर्वं = पूर्वपिप्पली इत्यादौ न पिप्पली।'

[[data]]
"सङ्केतितम्" = 'समानाधिकरणम्'
"गणः\n" = 'सामानाधिकरण्यम्'
"परिणामः" = 'समानाधिकरणम्'
"अवधानावश्यकता" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"सङ्केतितम्" = 'न समानाधिकरणम्'
"गणः\n" = 'सामानाधिकरण्यम्'
"परिणामः" = 'व्यधिकरणम्'
"अवधानावश्यकता" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"सङ्केतितम्" = ''
"गणः\n" = 'समासः'
"परिणामः" = 'कर्मधारयः'
"अवधानावश्यकता" = ''
"सूत्रम्" = 'तत्पुरुषः समानाधिकरणः कर्मधारयः ।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"सङ्केतितम्" = ''
"गणः\n" = 'समासः'
"परिणामः" = 'नित्यः'
"अवधानावश्यकता" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = '''
"वृक्षं वृक्षं प्रति = प्रतिवृक्षम्" इत्यत्र नित्यसमासो न।
देवानांप्रियः (= मूर्खः)।
अव्ययीभावः, न प्रति वीप्सायां।'''
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = '''
प्रायः विभाषाधिकारे (= २.१.११-तः) अनन्तर्भूतत्वात् ।
अविग्रहो वा अस्वपदविग्रहो वा।
अविग्रहः कदाचिद् विशिष्टार्थत्वात्।'''
"अभावोदाहरणम्" = ''

[[data]]
"सङ्केतितम्" = ''
"गणः\n" = 'समासः'
"परिणामः" = 'केवलः'
"अवधानावश्यकता" = ''
"सूत्रम्" = '(सुप् सर्मर्थः)‌ सह सुपा।'
"उदाहरण-विग्रहः" = 'पूर्वम् भूतः = भूतपूर्वः शृतपूर्वा'
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = 'अन्यसंज्ञा-रहितः समासः।'
"अभावोदाहरणम्" = ''

[[data]]
"सङ्केतितम्" = 'विवरणवाक्यम्'
"गणः\n" = 'विग्रहवाक्यम्'
"परिणामः" = 'विग्रहवाक्यम्'
"अवधानावश्यकता" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"सङ्केतितम्" = ''
"गणः\n" = 'विग्रहवाक्यम्'
"परिणामः" = 'अस्वपदम्'
"अवधानावश्यकता" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"सङ्केतितम्" = ''
"गणः\n" = 'विग्रहवाक्यम्'
"परिणामः" = 'स्वपदम्'
"अवधानावश्यकता" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''
