[[data]]
"अङ्गम्" = '- (उपसर्गः +‌*आत्, अन्ये अपवादाः)'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'क्तिन्'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"सूत्रम्" = 'स्त्रियां क्तिन् ।'
"प्रभावोदाहरणम्" = 'कृतिः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'आबादिः (प्रयोगतो ज्ञातः)'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'क्तिन् स्त्रियाम्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'क्तिन्नाबादिभ्यश्च वक्तव्यः।  (वा)'
"प्रभावोदाहरणम्" = 'आप्तिः राद्धिः दीप्तिः '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'श्रु यजि स्तु'
"प्रत्ययः/ विवक्षा" = 'करणे'
"परिणामः" = 'क्तिन् स्त्रियाम्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'श्रुयजिस्तुभ्यः करणे। (वा)'
"प्रभावोदाहरणम्" = 'श्रूयते अनया इति श्रुतिः। इष्टिः। स्तुतिः। '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'ग्ला म्ला ज्या हा'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'निः'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = ' ग्लाम्लाज्याहाभ्यो निः। (वा)'
"प्रभावोदाहरणम्" = 'ग्लानिः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'ऋ'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'क्तिन्, निष्ठावत् नत्वम्'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = ' ऋ̄कारल्वादिभ्यः क्तिन् निष्ठावद् भवति इति वक्तव्यम्।  (वा)'
"प्रभावोदाहरणम्" = 'कीर्णिः। गीर्णिः। जीर्णिः। शीर्णिः। लूनिः। यूनिः।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'स्था गा पा पचां '
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'क्तिन् स्त्रियाम्'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = 'स्थागापापचां भावे ।'
"प्रभावोदाहरणम्" = ' प्रस्थितिः। उद्गीतिः। सङ्गीतिः। प्रपीतिः।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = '"आतश्चोपसर्गे"  इत्यस्यापवादः।'

[[data]]
"अङ्गम्" = 'मन्त्रे वृषेषपचमनविदभूवीरा'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'क्तिन् उदात्तः'
"प्रसिद्धिः" = '१'
"विधिप्रकारः" = ''
"सूत्रम्" = 'मन्त्रे वृषेषपचमनविदभूवीरा उदात्तः ।'
"प्रभावोदाहरणम्" = 'वृष्टिः। इष्टिः। पक्तिः। मतिः। वित्तिः। भूतिः। वीतिः। रातिः। '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'ऊतियूतिजूतिसातिहेतिकीर्तयश्च'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'क्तिन् उदात्तः'
"प्रसिद्धिः" = '१'
"विधिप्रकारः" = 'निपातनम्'
"सूत्रम्" = 'ऊतियूतिजूतिसातिहेतिकीर्तयश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'व्रज यज'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'क्यप् उदात्तः'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'व्रजयजोर्भावे क्यप्‌ ।'
"प्रभावोदाहरणम्" = 'व्रज्या। इज्या।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = 'क्तिनो ऽपवादः। '

[[data]]
"अङ्गम्" = 'समज निषद निपत मनविदषुञ्शीङ्भृञिणः'
"प्रत्ययः/ विवक्षा" = 'संज्ञायाम् स्त्रियाम् (=अधिकरणे प्रसिद्धे)'
"परिणामः" = 'क्यप् उदात्तः'
"प्रसिद्धिः" = '१'
"विधिप्रकारः" = ''
"सूत्रम्" = 'संज्ञायां समजनिषदनिपतमनविदषुञ्शीङ्भृञिणः ।  '
"प्रभावोदाहरणम्" = 'समजन्ति अस्यामिति समज्या। निषद्या। निपत्या। मन्या। विद्या। सुत्या। शय्या। भृत्या। इत्या। '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'कृ'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'क्तिन्, क्यप्, श'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = 'कृञः श च । (योगविभागः)'
"प्रभावोदाहरणम्" = ' क्रिया, कृत्या, कृतिः।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'इष् '
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'श'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = '''
इच्छा ।
'''
"प्रभावोदाहरणम्" = '''
इच्छा
'''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'परिचर्या परिसर्या मृगया अटाट्या'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'श'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'परिचर्यापरिसर्यामृगयाटाट्यानाम् उपसङ्ख्यानम्।'
"प्रभावोदाहरणम्" = 'परिचर्या। परिसर्या। मृगया। अटाट्या। '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'जागृ'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'श । क्यप्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'जागर्तेरकारो वा।  (वा)'
"प्रभावोदाहरणम्" = 'जागरा, जागर्या।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'प्रत्ययान्तेभ्यो धातुभ्यः'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'अ'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"सूत्रम्" = 'अ प्रत्ययात्‌ ।'
"प्रभावोदाहरणम्" = 'चिकीर्षा। जिहीर्षा। पुत्रीया। पुत्रकाम्या। लोलूया। कण्डूया।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = 'क्तिनो ऽपवादः। '

[[data]]
"अङ्गम्" = 'गुरुः स्वरः + हल्'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'अ'
"प्रसिद्धिः" = '४'
"विधिप्रकारः" = ''
"सूत्रम्" = 'गुरोश्च हलः ।'
"प्रभावोदाहरणम्" = 'कुण्डा। हुण्डा। ईहा। ऊहा। गुरोः इति किम्? भक्तिः। हलः इति किम्? नीतिः।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'षित् । भिदादिः'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'अङ्'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = 'षिद्भिदादिभ्योऽङ् ।'
"प्रभावोदाहरणम्" = '''
जृ̄ष् जरा। त्रपूष् त्रपा। 
भिदादिभ्यः खल्वपि भिदा। छिदा। विदा। क्षिपा। गुहा गिर्योषध्योः। श्रद्धा। मेधा। गोधा। आरा। हारा। कारा। क्षिया। तारा। धारा। लेखा। रेखा। चूडा। पीड। वपा। वसा। सृजा। क्रपेः सम्प्रसारणं च कृपा। भिदा विदारणे। भित्तिः अन्या। छिदा द्वैधीकरणे। छित्तिः अन्या। आरा शस्त्र्याम्। आर्तिः अन्या। धारा प्रपाते। धृतिः अन्या।'''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'चिति स्मृत्याम्, पूज पूजायाम्, कथ वाक्यप्रबन्धे, कुबि आच्छादने, चर्च अध्ययने चुरादिः'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'अङ् । युच्'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = 'चिन्तिपूजिकथिकुम्बिचर्चश्च ।'
"प्रभावोदाहरणम्" = 'चिन्ता। पूजा। कथा। कुम्बा। चर्चा। चकारात् युचपि भवति। चिन्तना।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = '(उपसर्गः | श्रद् | अन्तर्) + (आत् - स्था गा पा)'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'अङ्'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = '''
आतश्चोपसर्गे ।
श्रदतरोर् उपसर्गवत् वृत्तिः। (वा)
(स्थागापापचां भावे ।)'''
"प्रभावोदाहरणम्" = 'प्रदा उपदा प्रधा'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = '*णि । आस ।श्रन्थ'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'युच्'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"सूत्रम्" = 'ण्यासश्रन्थो युच् ।'
"प्रभावोदाहरणम्" = 'कारणा। हारणा। आसना। श्रन्थना।'
"अभावोदाहरणम्" = 'कथम् आस्या? ऋहलोर् ण्यत् ३।१।१२४ भविष्यति।'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'घट्टिवन्दिविधिभ्य'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'युच्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'घट्टिवन्दिविधिभ्य उपसङ्ख्यानम्।'
"प्रभावोदाहरणम्" = 'घट्टना। वन्दना। वेदना। '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'इषेरनिच्छार्थस्य'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'युच्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'इषेरनिच्छार्थस्य युज् वक्तव्यः। '
"प्रभावोदाहरणम्" = 'अध्येषणा। अन्वेषना।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'पर + इषेरनिच्छार्थस्य'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'युच्'
"प्रसिद्धिः" = '१'
"विधिप्रकारः" = ''
"सूत्रम्" = 'परेर्वा।'
"प्रभावोदाहरणम्" = ' पर्येषना, परीष्टिः।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ' रोगाख्यायां बहुलम्'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'ण्वुल्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'रोगाख्यायां ण्वुल् बहुलम् ।'
"प्रभावोदाहरणम्" = 'बहुलग्रहणं व्यभिचरार्थम्। प्रच्छर्दिका। प्रवाहिका। विचर्चिका। न च भवति। शिरोर्तिः। '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'धात्वर्थनिर्देशे'
"परिणामः" = 'ण्वुल्'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"सूत्रम्" = 'धात्वर्थनिर्देशे ण्वुल् (वा)'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'धातुनिर्देशे'
"परिणामः" = 'इक्'
"प्रसिद्धिः" = '४'
"विधिप्रकारः" = ''
"सूत्रम्" = 'इक्श्तिपौ धातुनिर्देशे (वा)'
"प्रभावोदाहरणम्" = 'अदिः दिशिः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'धातुनिर्देशे'
"परिणामः" = 'श्तिप्'
"प्रसिद्धिः" = '४'
"विधिप्रकारः" = ''
"सूत्रम्" = 'इक्श्तिपौ धातुनिर्देशे (वा)'
"प्रभावोदाहरणम्" = 'पचतिः वर्धतिः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''' "नित्यं करोतेः", "दधातेर्हिः" इत्यादिभिर् ज्ञापनम् - अत्रापि गणविकरणम् भवतीति। 
'''

[[data]]
"अङ्गम्" = 'वर्णः'
"प्रत्ययः/ विवक्षा" = 'निर्देशे'
"परिणामः" = 'कारः'
"प्रसिद्धिः" = '४'
"विधिप्रकारः" = ''
"सूत्रम्" = 'वर्णात् कारः  (वा)'
"प्रभावोदाहरणम्" = 'अकारः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = 'तद्धितपत्रे विवृतम्'

[[data]]
"अङ्गम्" = 'र'
"प्रत्ययः/ विवक्षा" = 'निर्देशे'
"परिणामः" = 'इफः'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = 'रात् इफः  (वा)'
"प्रभावोदाहरणम्" = 'रेफः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = 'तद्धितपत्रे विवृतम्'

[[data]]
"अङ्गम्" = 'मत्वर्थः'
"प्रत्ययः/ विवक्षा" = 'निर्देशे'
"परिणामः" = 'छः'
"प्रसिद्धिः" = '१'
"विधिप्रकारः" = ''
"सूत्रम्" = 'मत्वर्थात् छः  (वा)'
"प्रभावोदाहरणम्" = 'मत्वर्थीयः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'अच्*'
"प्रत्ययः/ विवक्षा" = 'निर्देशे'
"परिणामः" = 'इण्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'इण् अजादिभ्यः  (वा)'
"प्रभावोदाहरणम्" = 'आजिः। आतिः। आदिः।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'इञ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'इञ् वपादिभ्यः  (वा)'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'इक्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'इक् कृष्यादिभ्यः  (वा)'
"प्रभावोदाहरणम्" = 'कृषिः। किरिः।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'सम्पदादिः'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'क्विप् | क्तिन्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = '''
सम्पदादिभ्यः क्विप्।
 क्तिन्नपि इष्यते। (वा)'''
"प्रभावोदाहरणम्" = '''
सम्पत्तिः। विपत्तिः। 
सम्पद्। विपद्। प्रतिपद्।'''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'सम्पदादिभ्यः क्विप् (वा)'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् संज्ञायाम्'
"परिणामः" = 'ण्वुल्'
"प्रसिद्धिः" = '४'
"विधिप्रकारः" = ''
"सूत्रम्" = 'संज्ञायाम् ।'
"प्रभावोदाहरणम्" = 'उद्दालकपुष्पभञ्जिका। वरणपुष्पप्रचायिका। अभ्यूषखादिका। आचोषखादिका। शालभञ्जिका। तालभञ्जिका।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'स्त्रियाम् परिप्रश्ने आख्याने च गम्यमाने '
"परिणामः" = 'इञ्, *'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"सूत्रम्" = 'विभाषाऽऽख्यानपरिप्रश्नयोरिञ् च ।'
"प्रभावोदाहरणम्" = 'कां त्वं कारिमकार्षीः, कां कारिकाम् अकार्षीः, कां क्रियामकार्षीः, कां कृत्यामकार्षीः, का कृतिमकार्षीः? सर्वां कारिमकार्षम्, सर्वां कारिकाम् अकार्षम्, सर्वां क्रियामकार्षम्, सर्वां कृत्यामकार्षम्, सर्वां कृतिमकार्षम्। कां गणिमजीगणः, कां गणिकामजीगणः, कां गणनामजीगणः? सर्वां गणिमजीगणम्, सर्वां गणिकाम्, सर्वां गणनाम्। एवं कां याजिम्, कां याजिकाम्, कां याचिम्, कां यचिकाम्, कां पाचिम्, कां पाचिकाम् कां पचाम्, कां पक्तिम्, कां पाठिम्, कां पाठिकाम्, कां पठितिम् इति द्रष्टव्यम्। '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = '''
स्त्रियाम् ।
पर्यायः परिपाटीक्रमः। अर्हणमर्हः, तद्योग्यता। ऋणं तत् यत् परस्य धार्यते। उत्पत्तिः जन्म।'''
"परिणामः" = 'ण्वुच्, *'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"सूत्रम्" = 'पर्यायार्हर्णोत्पत्तिषु ण्वुच् ।'
"प्रभावोदाहरणम्" = 'पर्याये तावत् भवतः शायिका। भवतो ऽग्रग्रासिका। अर्हे अर्हति भवानिक्षुभक्षिकाम्। ऋणे इक्षुभक्षिकां मे धरयसि। ओदनभोजिकाम्। पयःपायिकाम्। उत्पत्तौ इक्षुभक्षिका मे उदपादि। ओदनभोजिका। पयःपायिका।'
"अभावोदाहरणम्" = ' विभाषा इत्येव, चिकीर्षा उत्पद्यते। '
"अन्यटिप्पनी" = 'ण्वुलि प्रकृते प्रत्ययान्तरकरनं स्वरार्थम्।'

[[data]]
"अङ्गम्" = 'नञि + धातुः'
"प्रत्ययः/ विवक्षा" = '''
स्त्रियाम् भावे, अकर्तरि कारके 
आक्रोशे'''
"परिणामः" = 'अनिः'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = 'आक्रोशे नञ्यनिः ।'
"प्रभावोदाहरणम्" = 'अकरणिस्ते वृषल भूयात्।'
"अभावोदाहरणम्" = 'आक्रोशे इति किम्? अकृतिस्तस्य कटस्य। नञि इति किम्? मृतिस्ते वृषल भूयात्।'
"अन्यटिप्पनी" = ''
