[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'भविष्यति'
"विधिः" = ''
"सूत्रम्" = 'भविष्यति गम्यादयः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'भविष्यति'
"विधिः" = ''
"सूत्रम्" = 'यावत्पुरानिपातयोर्लट् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'भविष्यति'
"विधिः" = ''
"सूत्रम्" = 'विभाषा कदाकर्ह्योः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'भविष्यति'
"विधिः" = ''
"सूत्रम्" = 'किंवृत्ते लिप्सायाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'भविष्यति'
"विधिः" = ''
"सूत्रम्" = 'लिप्स्यमानसिद्धौ च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'भविष्यति'
"विधिः" = ''
"सूत्रम्" = 'लोडर्थलक्षणे च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'भविष्यति'
"विधिः" = ''
"सूत्रम्" = 'लिङ् चोर्ध्वमौहूर्तिके ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'भविष्यति'
"विधिः" = ''
"सूत्रम्" = 'तुमुन्ण्वुलौ क्रियायां क्रियार्थायाम्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'भविष्यति'
"विधिः" = ''
"सूत्रम्" = 'भाववचनाश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'भविष्यति'
"विधिः" = ''
"सूत्रम्" = 'अण् कर्मणि च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'भविष्यति'
"विधिः" = ''
"सूत्रम्" = 'लृट् शेषे च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'भविष्यति'
"विधिः" = ''
"सूत्रम्" = 'लृटः सद् वा ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'भविष्यति'
"विधिः" = ''
"सूत्रम्" = 'अनद्यतने लुट् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''
