[[data]]
"अङ्गम्" = '- (अपवादाः = इ …)'
"प्रत्ययः/ विवक्षा" = '''
भावे
(क्रियासामान्यवाची)'''
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"सूत्रम्" = 'भावे (घञ्)।'
"प्रभावोदाहरणम्" = 'पाकः त्यागः रागः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = '(- कर्तरि) कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = '४'
"विधिप्रकारः" = ''
"सूत्रम्" = 'अकर्तरि च कारके संज्ञायाम् ।'
"प्रभावोदाहरणम्" = '''
आहरन्ति तस्माद् रसम् इति आहारः - संज्ञायां तक्षशिलाहारः, मधुराहारः।
रमते ऽस्मिन् योगिन इति रामः।'''
"अभावोदाहरणम्" = '''
अकर्तरि इति किम्? मिषत्यसौ मेषः।
सज्ञायाम् इति किम्? कर्तव्यः कटः।'''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'सङ्ख्यान्वितः धातुः'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'परिमाणाख्यायां सर्वेभ्यः ।'
"प्रभावोदाहरणम्" = 'द्वौ कारौ।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'दारि |‌जारि'
"प्रत्ययः/ विवक्षा" = 'कर्तरि, भावे,  अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = ' दारजारौ कर्तरि णिलुक् च। (वा)'
"प्रभावोदाहरणम्" = 'दारयन्ति इति दाराः। जरयन्ति इति जाराः। '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'इङ्'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'इङश्च ।'
"प्रभावोदाहरणम्" = '''
अध्यायः
। उपेत्यास्मादधीते उपाध्यायः।'''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'इङ्'
"प्रत्ययः/ विवक्षा" = 'अपादाने'
"परिणामः" = 'घञ् +‌ङीष्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'अपादाने स्त्रियाम् उपसङ्ख्यानं तदन्ताच् च वा ङीष्।  (वा)'
"प्रभावोदाहरणम्" = 'उपाध्याया, उपाध्यायी।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'शृ वायुवर्णनिवृतेषु'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = '१'
"विधिप्रकारः" = ''
"सूत्रम्" = 'शृ̄ वायुवर्णनिवृतेषु। (वा)'
"प्रभावोदाहरणम्" = 'शारो वायुः। शारो वर्णः। शारो निवृतम्। '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'उपसर्गः +‌रौ'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'उपसर्गे रुवः ।'
"प्रभावोदाहरणम्" = 'रंरावः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'सं + यु|द्रु|दु'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = '१'
"विधिप्रकारः" = ''
"सूत्रम्" = 'समि युद्रुदुवः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'अनुपसर्गे श्रि|णी|भू'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'श्रिणीभुवोऽनुपसर्गे ।'
"प्रभावोदाहरणम्" = 'श्रायः नायः भावः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'वि + क्षु|श्रु'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'वौ क्षुश्रुवः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'अव|उत् + नयतिः'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'अवोदोर्नियः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'प्र + द्रु | स्रु |‌स्तु'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'प्रे द्रुस्तुस्रुवः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'निर् + पू'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'निरभ्योः पूल्वोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'अभि‌ + लू'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'निरभ्योः पूल्वोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'उत् | नि + गॄ'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'उन्न्योर्ग्रः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'उत् | नी + कॄ धान्ये'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'कॄ धान्ये ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'सं + स्तु यज्ञे'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'यज्ञे समि स्तुवः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'प्र +‌स्तॄ अयज्ञे'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'प्रे स्त्रोऽयज्ञे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = '''
वि + स्तॄ 
(अशब्दे, विस्तीर्णतायाम्)'''
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'प्रथने वावशब्दे ।'
"प्रभावोदाहरणम्" = 'पटस्य विस्तारः'
"अभावोदाहरणम्" = 'तृणविस्तरः'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = '''
वि + स्तॄ 
छन्दोनाम्नि'''
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'छन्दोनाम्नि च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'उत् + गृह्'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'उदि ग्रहः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'सं + गृह् (मुष्टौ)'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'समि मुष्टौ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'परिन्योर्नीणोर्द्यूताभ्रेषयोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'परावनुपात्यय इणः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'व्युपयोः शेतेः पर्याये ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'हस्तादाने चेरस्तेये ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'निवासचितिशरीरोपसमाधानेष्वादेश्च कः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'संघे चानौत्तराधर्ये ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'कर्मव्यतिहारे णच् स्त्रियाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'अभिविधौ भाव इनुण् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'आक्रोशेऽवन्योर्ग्रहः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'प्रे लिप्सायाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'परौ यज्ञे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'नौ वृ धान्ये ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'उदि श्रयतियौतिपूद्रुवः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'विभाषाऽऽङि रुप्लुवोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'अवे ग्रहो वर्षप्रतिबन्धे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'प्रे वणिजाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'रश्मौ च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'वृणोतेराच्छादने ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'घञ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'परौ भुवोऽवज्ञाने ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'इ|ई'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'अच्'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"सूत्रम्" = 'एरच् ।'
"प्रभावोदाहरणम्" = 'अयः जयः  प्रणयः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'ॠ |‌ उ'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'अप्'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"सूत्रम्" = '''
ॠदोरप्‌ ।
[दकारः मुखसुखाय]'''
"प्रभावोदाहरणम्" = 'यवः। स्तवः। करः। शरः।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'ग्रहवृदृनिश्चिगमश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'उपसर्गः +‌ अद्|घस्'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'अप्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'उपसर्गेऽदः ।'
"प्रभावोदाहरणम्" = 'विघसः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'नि + अद् (→घस्)'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'अप् |‌ण्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'नौ ण च ।'
"प्रभावोदाहरणम्" = 'न्यादः | निघासः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = '(व्यध |जप) अनुपसर्गे'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'अप्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'व्यधजपोरनुपसर्गे ।'
"प्रभावोदाहरणम्" = 'व्यधः जपः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'स्वन हस'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = 'अप् | घञ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'स्वनहसोर्वा ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'यमः समुपनिविषु ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'नौ गदनदपठस्वनः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'क्वणो वीणायां च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'नित्यं पणः परिमाणे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'मदोऽनुपसर्गे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'प्रमदसम्मदौ हर्षे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'समुदोरजः पशुषु ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'अक्षेषु ग्लहः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'प्रजने सर्तेः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = '(नि|अभि|उप|वि) + ह्वा'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके संज्ञायाम्'
"परिणामः" = '''
सम्प्रसारणम् +
अप्'''
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'ह्वः सम्प्रसारणं च न्यभ्युपविषु ।'
"प्रभावोदाहरणम्" = 'निहवः अभिहवः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'आङ् + ह्वा'
"प्रत्ययः/ विवक्षा" = 'युद्धे'
"परिणामः" = 'अप्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'आङि युद्धे ।'
"प्रभावोदाहरणम्" = 'आहूयन्त अस्मिन्निति आहवः'
"अभावोदाहरणम्" = 'आह्वायः'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'आङ् + ह्वा'
"प्रत्ययः/ विवक्षा" = 'जलाधारे'
"परिणामः" = 'अप्'
"प्रसिद्धिः" = '१'
"विधिप्रकारः" = 'निपातनम्'
"सूत्रम्" = 'निपानमाहावः ।'
"प्रभावोदाहरणम्" = 'आहावः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'भावेऽनुपसर्गस्य ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'हनश्च वधः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'मूर्तौ घनः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'अन्तर्घनो देशे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'अगारैकदेशे प्रघणः प्रघाणश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'उद्घनोऽत्याधानम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'अपघनोऽङ्गम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'करणेऽयोविद्रुषु ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'स्तम्ब + हन्'
"प्रत्ययः/ विवक्षा" = 'करणे'
"परिणामः" = 'क | अप्'
"प्रसिद्धिः" = '१'
"विधिप्रकारः" = ''
"सूत्रम्" = 'स्तम्बे क च ।'
"प्रभावोदाहरणम्" = 'स्तम्बघ्नः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'परि + हन्'
"प्रत्ययः/ विवक्षा" = 'करणे'
"परिणामः" = '''
घ-आदेशः +
अप्'''
"प्रसिद्धिः" = '१'
"विधिप्रकारः" = ''
"सूत्रम्" = 'परौ घः ।'
"प्रभावोदाहरणम्" = 'परिघः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'उपघ्न आश्रये ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'संघोद्घौ गणप्रशंसयोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'निघो निमितम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'डु-इत्'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके'
"परिणामः" = 'क्त्रिमम्'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = '''
ड्वितः क्त्रिः ।
[क्त्रेर् मं नित्यम्॥]'''
"प्रभावोदाहरणम्" = 'पक्त्रित्रिमम् कृत्रिमम्'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'टु-इत् धातुः'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके'
"परिणामः" = 'अथुच्'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = 'ट्वितोऽथुच् ।'
"प्रभावोदाहरणम्" = 'वेपथुः, नन्दथुः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'यज-याच-यत-विच्छ-प्रच्छ-रक्षो'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके'
"परिणामः" = 'नङ्'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = 'यजयाचयतविच्छप्रच्छरक्षो नङ् ।'
"प्रभावोदाहरणम्" = 'यत्नः प्रश्नः याच्ञा'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'स्वप्'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके'
"परिणामः" = 'नन्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'स्वपो नन् ।'
"प्रभावोदाहरणम्" = 'स्वप्नः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = 'नकारः स्वरार्थः'

[[data]]
"अङ्गम्" = 'उपसर्गे घुः'
"प्रत्ययः/ विवक्षा" = 'भावे, अकर्तरि कारके'
"परिणामः" = 'किः'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'उपसर्गे घोः किः ।'
"प्रभावोदाहरणम्" = 'प्रदिः अन्तर्धिः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = '''
कर्मणि उपपदे 
घुः'''
"प्रत्ययः/ विवक्षा" = 'अधिकरणे'
"परिणामः" = 'किः'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'कर्मण्यधिकरणे च ।'
"प्रभावोदाहरणम्" = 'शराः धीयन्ते अस्मिन् शरधिः। जलधिः। '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''
