[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'ईश्वर शब्दे उपपदे तुमर्थे भावलक्षणे स्थादिभ्यो वा छन्दसि'
"परिणामः" = 'तोसुन्'
"प्रसिद्धिः" = ''
"सूत्रम्" = ''
"प्रभावोदाहरणम्" = 'ईश्वरोऽभिचरितोः (अभिचरितु समर्थ इत्यर्थः)। आसंस्थातोर्वेद्यां सोदन्ति। [आ समाप्तेः सीदन्तीत्यर्थः]॥'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'कृत्यार्थे छन्दसि'
"परिणामः" = 'त्वन्'
"प्रसिद्धिः" = ''
"सूत्रम्" = ''
"प्रभावोदाहरणम्" = 'कर्त्वं हविः (कर्त्तव्यम्)॥'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तुमर्थे छन्दसि'
"परिणामः" = 'मे'
"प्रसिद्धिः" = ''
"सूत्रम्" = ''
"प्रभावोदाहरणम्" = 'वक्षे रायः (धनानि वोढुम्)॥'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तुमर्थे छन्दसि'
"परिणामः" = 'शध्यै'
"प्रसिद्धिः" = ''
"सूत्रम्" = 'तुमर्थे सेसेनसेऽसेन्क्सेक्सेनध्यैअध्यैन्कध्यैकध्यैन्शध्यैशध्यैन्तवैतवेङ्तवेनः'
"प्रभावोदाहरणम्" = 'सह मादयध्यै॥'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तुमर्थे छन्दसि'
"परिणामः" = 'शध्यैन्'
"प्रसिद्धिः" = ''
"सूत्रम्" = ''
"प्रभावोदाहरणम्" = 'सह मादयध्यै॥'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तुमर्थे छन्दसि'
"परिणामः" = 'सेन्'
"प्रसिद्धिः" = ''
"सूत्रम्" = ''
"प्रभावोदाहरणम्" = 'ता वामेषे रथानाम् (युवां रथान् गमयितु समर्थो)॥'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तुमर्थे छन्दसि'
"परिणामः" = 'तवेङ्'
"प्रसिद्धिः" = ''
"सूत्रम्" = ''
"प्रभावोदाहरणम्" = 'दशमे मासि सूतवे॥'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तुमर्थे छन्दसि'
"परिणामः" = 'तवेन्'
"प्रसिद्धिः" = ''
"सूत्रम्" = ''
"प्रभावोदाहरणम्" = 'स्वर्देवेषु गन्तवे॥'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तुमर्थे छन्दसि'
"परिणामः" = 'तवै'
"प्रसिद्धिः" = ''
"सूत्रम्" = ''
"प्रभावोदाहरणम्" = 'ब्रह्मणेन न म्‍लेच्छितवै नापभाषितवै॥ ( or may be - सोममिन्द्राय पातवै)॥'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'कृत्यार्थे छन्दसि'
"परिणामः" = 'तवै'
"प्रसिद्धिः" = ''
"सूत्रम्" = ''
"प्रभावोदाहरणम्" = 'परिधातवै (परिधातव्यम्)॥'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''
