[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'करणाधिकरणयोश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'पुंसि संज्ञायां घः प्रायेण ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'गोचरसंचरवहव्रजव्यजापणनिगमाश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'अवे तॄस्त्रोर्घञ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'हलश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'अध्यायन्यायोद्यावसंहाराधारावयाश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'उदङ्कोऽनुदके ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'जालमानायः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'खनो घ च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''
