[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'धातुः - वस्'
"प्रत्ययः/ विवक्षा" = 'भावे, कर्मणि'
"परिणामः" = 'तव्यत्-तव्य-अनीयर्'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = 'कृत्यः तव्यत्-तव्य-अनीयर्'
"विधिः" = ''
"सूत्रम्" = '''
(तयोरेव कृत्यक्तखलर्थाः ।)
तव्यत्तव्यानीयरः ।'''
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = 'तव्यत् इत्यत्र तकारः, अनीयर् इत्यत्र रेफः स्वरार्थे।'

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'वस्'
"प्रत्ययः/ विवक्षा" = 'कर्तरि'
"परिणामः" = 'णिच् +‌तव्यत्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'वसेस् तव्यत् कर्तरि णिच् च। (वा)'
"प्रभावोदाहरणम्" = 'वास्तव्यः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = '''
कर्मकर्तरि।
भावे, कर्मणि'''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '''
केलिमर उपसङ्ख्यानम्। (वा)
कर्मकर्तरि चायमिष्यते॥ (वा)'''
"प्रभावोदाहरणम्" = 'पचेलिमाः माषाः। भिदेलिमानि काष्ठानि।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = 'न ऋ-हल्-अन्तः'
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'भावे, कर्मणि'
"परिणामः" = 'यत्'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = 'कृत्यः यत्'
"विधिः" = ''
"सूत्रम्" = '''
(तयोरेव कृत्यक्तखलर्थाः [भावे, कर्मणि च]॥)
अचो यत्॥'''
"प्रभावोदाहरणम्" = 'चेय = चेतव्य'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = 'ष्यञ् इति तद्धितप्रत्ययेन सह भ्रमो मास्तु!'

[[data]]
"अङ्गस्थितिः" = '''
तकिशसि-चतियतिजनीनाम् ।
'''
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'भावे, कर्मणि'
"परिणामः" = 'यत्'
"प्रसिद्धिः" = '१'
"विधिप्रकारः" = 'कृत्यः यत्'
"विधिः" = ''
"सूत्रम्" = 'तकिशसि-चतियतिजनीनाम् उपसंख्यानं (वा)'
"प्रभावोदाहरणम्" = ' तक्यम् । शस्यम् । चत्यम् । यत्यम्। जन्यम्।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = 'स्वरार्थम् सूत्रम्। ण्यत् अपि पर्याप्तं लोके।'

[[data]]
"अङ्गस्थितिः" = 'हन्।'
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'भावे, कर्मणि'
"परिणामः" = 'यत्/ ण्यत्'
"प्रसिद्धिः" = '१'
"विधिप्रकारः" = 'कृत्यः यत्'
"विधिः" = ''
"सूत्रम्" = 'हनो वा वध च (वा)'
"प्रभावोदाहरणम्" = 'हन् → घात्यम् (ण्यत्)/ वध्य (यत्)'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = 'पुँः अन्ते, अत् उपधायाम्'
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'भावे, कर्मणि'
"परिणामः" = 'यत्'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = 'कृत्यः यत्'
"विधिः" = ''
"सूत्रम्" = 'पोरदुपधात्‌  [यत्]।'
"प्रभावोदाहरणम्" = 'शप्यम् । लभ्यम् । रम्यम्'
"अभावोदाहरणम्" = 'कोप्यम्। काव्यम्।'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = 'शक्-सह्'
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'भावे, कर्मणि'
"परिणामः" = 'यत्'
"प्रसिद्धिः" = '४'
"विधिप्रकारः" = 'कृत्यः यत्'
"विधिः" = ''
"सूत्रम्" = 'शकिसहोश्च [यत्]।'
"प्रभावोदाहरणम्" = 'शक्यम्'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = 'गद-मद-चर-यमश्च अनुपसर्गे '
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'भावे, कर्मणि'
"परिणामः" = 'यत्'
"प्रसिद्धिः" = '४'
"विधिप्रकारः" = 'कृत्यः यत्'
"विधिः" = ''
"सूत्रम्" = ' गद-मद-चर-यमश्च अनुपसर्गे '
"प्रभावोदाहरणम्" = 'चर्य।'
"अभावोदाहरणम्" = 'कार्य।'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = 'आङ्+चर् अगुरौ'
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'भावे, कर्मणि'
"परिणामः" = 'यत्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = 'कृत्यः यत्'
"विधिः" = ''
"सूत्रम्" = 'चरेराङि चागुरौ (वा)'
"प्रभावोदाहरणम्" = 'आचर्यः देशः'
"अभावोदाहरणम्" = 'आचार्यः गुरुः।'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = '''
निपातनानि।
अवद्य (=पापे)। पण्य = पणितव्य। 
वर्या अनिरोधे।'''
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'भावे, कर्मणि'
"परिणामः" = 'यत्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = 'कृत्यः यत्'
"विधिः" = 'निपातनम्'
"सूत्रम्" = 'अवद्यपण्यवर्या गर्ह्यपणितव्यानिरोधेषु । 3.1.101'
"प्रभावोदाहरणम्" = 'अवद्यं पापम् ।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'वह्'
"प्रत्ययः/ विवक्षा" = 'करणे'
"परिणामः" = 'यत्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः यत्'
"विधिः" = 'निपातनम्'
"सूत्रम्" = 'वह्यं करणम्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'यत्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः यत्'
"विधिः" = ''
"सूत्रम्" = 'अर्यः स्वामिवैश्ययोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'यत्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः यत्'
"विधिः" = ''
"सूत्रम्" = 'उपसर्या काल्या प्रजने ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'यत्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः यत्'
"विधिः" = ''
"सूत्रम्" = 'अजर्यं संगतम्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = ''
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = ''
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्यप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः क्यप्'
"विधिः" = ''
"सूत्रम्" = 'वदः सुपि क्यप् च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्यप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः क्यप्'
"विधिः" = ''
"सूत्रम्" = 'भुवो भावे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्यप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः क्यप्'
"विधिः" = ''
"सूत्रम्" = 'हनस्त च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्यप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः क्यप्'
"विधिः" = ''
"सूत्रम्" = 'एतिस्तुशस्वृदृजुषः क्यप्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्यप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः क्यप्'
"विधिः" = ''
"सूत्रम्" = 'ऋदुपधाच्चाकॢपिचृतेः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्यप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः क्यप्'
"विधिः" = ''
"सूत्रम्" = 'ई च खनः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्यप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः क्यप्'
"विधिः" = ''
"सूत्रम्" = 'भृञोऽसंज्ञायाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्यप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः क्यप्'
"विधिः" = ''
"सूत्रम्" = 'मृजेर्विभाषा ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्यप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः क्यप्'
"विधिः" = ''
"सूत्रम्" = 'राजसूयसूर्यमृषोद्यरुच्यकुप्यकृष्टपच्याव्यथ्याः'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्यप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः क्यप्'
"विधिः" = ''
"सूत्रम्" = 'भिद्योद्ध्यौ नदे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्यप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः क्यप्'
"विधिः" = ''
"सूत्रम्" = 'पुष्यसिद्ध्यौ नक्षत्रे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्यप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः क्यप्'
"विधिः" = ''
"सूत्रम्" = 'विपूयविनीयजित्या मुञ्जकल्कहलिषु ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्यप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः क्यप्'
"विधिः" = ''
"सूत्रम्" = 'प्रत्यपिभ्यां ग्रहेश्छन्दसि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्यप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः क्यप्'
"विधिः" = ''
"सूत्रम्" = 'पदास्वैरिबाह्यापक्ष्येषु च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्यप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः क्यप्'
"विधिः" = ''
"सूत्रम्" = 'विभाषा कृवृषोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्यप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः क्यप्'
"विधिः" = ''
"सूत्रम्" = 'युग्यं च पत्त्रे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्यप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः क्यप्'
"विधिः" = ''
"सूत्रम्" = 'अमावस्यदन्यतरस्याम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्यप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः क्यप्'
"विधिः" = ''
"सूत्रम्" = 'छन्दसि निष्टर्क्यदेवहूयप्रणीयोन्नीयोच्छिष्य'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = 'ऋ-हल्-अन्तः आक्षेपाभावे'
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'भावे, कर्मणि'
"परिणामः" = 'ण्यत्'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = 'कृत्यः ण्यत्'
"विधिः" = ''
"सूत्रम्" = 'ऋहलोर्ण्यत्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = 'उ/ऊ-कारान्तः आक्षेपाभावे'
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'भावे, कर्मणि'
"परिणामः" = 'ण्यत्'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = 'कृत्यः ण्यत्'
"विधिः" = ''
"सूत्रम्" = 'ओरावश्यके ।'
"प्रभावोदाहरणम्" = '''
लू + ण्यत् = 
लौ + य (वान्तो यि प्रत्यये) = लाव्य'''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ण्यत्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः ण्यत्'
"विधिः" = ''
"सूत्रम्" = 'आसुयुवपिरपिलपित्रपिचमश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ण्यत्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः ण्यत्'
"विधिः" = ''
"सूत्रम्" = 'आनाय्योऽनित्ये ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ण्यत्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः ण्यत्'
"विधिः" = ''
"सूत्रम्" = 'प्रणाय्योऽसंमतौ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ण्यत्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः ण्यत्'
"विधिः" = ''
"सूत्रम्" = 'पाय्यसान्नाय्यनिकाय्यधाय्या मानहविर्निवाससामिधेनीषु ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ण्यत्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः ण्यत्'
"विधिः" = ''
"सूत्रम्" = 'क्रतौ कुण्डपाय्यसंचाय्यौ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ण्यत्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः ण्यत्'
"विधिः" = ''
"सूत्रम्" = 'अग्नौ परिचाय्योपचाय्यसमूह्याः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ण्यत्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कृत्यः ण्यत्'
"विधिः" = ''
"सूत्रम्" = 'चित्याग्निचित्ये च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ण्वुल्-तृचौ'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'ण्वुल्-तृचौ'
"विधिः" = ''
"सूत्रम्" = 'ण्वुल्तृचौ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''
