[[data]]
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'वर्तमाने।'
"परिणामः" = 'लँट्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = 'सार्वधातुकादेशवान्'
"सूत्रम्" = 'वर्तमाने लँट् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'लटः शतृशानचावप्रथमासमानाधिकरणे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'सम्बोधने च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'लक्षणहेत्वोः क्रियायाः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'तौ सत्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'पूङ्यजोः शानन् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'ताच्छील्यवयोवचनशक्तिषु चानश् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'इङ् धारि'
"प्रत्ययः/ विवक्षा" = 'अकृच्छ्रकर्तरि'
"परिणामः" = 'शतृ'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'इङ्धार्योः शत्रकृच्छ्रिणि ।'
"प्रभावोदाहरणम्" = 'अधीयन् पारायणम्। धारयन्नुपनिषदम्।'
"अभावोदाहरणम्" = 'अकृच्छ्रिणि इति किम्? कृच्छ्रेण अधीते। कृच्छ्रेण धरयति।'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'द्विष्'
"प्रत्ययः/ विवक्षा" = 'कर्तरि'
"परिणामः" = 'शतृ'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'द्विषोऽमित्रे ।'
"प्रभावोदाहरणम्" = 'द्विषत्'
"अभावोदाहरणम्" = 'अमित्रे इति किम्? द्वेष्टि भार्या पतिम्।'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'सु'
"प्रत्ययः/ विवक्षा" = 'कर्तरि यज्ञसम्बन्धे'
"परिणामः" = 'शतृ'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'सुञो यज्ञसंयोगे ।'
"प्रभावोदाहरणम्" = 'सर्वे सुन्वन्तः।'
"अभावोदाहरणम्" = ' यज्ञसंयोगे इति किम्? सुनोति सुराम्।'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'अर्हः पूजायाम् ।'
"प्रभावोदाहरणम्" = 'अर्हन्निह भवान् विद्याम्।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'आक्वेस्तच्छीलतद्धर्मतत्साधुकारिषु ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'तृन् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'अलंकृञ्निराकृञ्प्रजनोत्पचोत्पतोन्मदरुच्यपत्रपवृतुवृधुसहचर इष्णुच् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'णेश्छन्दसि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'भुवश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'ग्लाजिस्थश्च ग्स्नुः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'त्रसिगृधिधृषिक्षिपेः क्नुः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'शमित्यष्टाभ्यो घिनुण् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'संपृचानुरुधाङ्यमाङ्यसपरिसृसंसृजपरिदेविसंज्वरपरिक्षिपपरिरटपरिवदपरिदहपरिमुहदुषद्विषद्रुहदुहयुजाक्रीडविविचत्यजरजभजातिचरापचरामुषाभ्याहनश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'वौ कषलसकत्थस्रम्भः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'अपे च लषः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'प्रे लपसृद्रुमथवदवसः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'निन्दहिंसक्लिशखादविनाशपरिक्षिपपरिरटपरिवादिव्याभाषासूञो वुञ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'देविक्रुशोश्चोपसर्गे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'चलनशब्दार्थादकर्मकाद्युच् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'अनुदात्तेतश्च हलादेः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'जुचङ्क्रम्यदन्द्रम्यसृगृधिज्वलशुचलषपतपदः ।  '
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'क्रुधमण्डार्थेभ्यश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'न यः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'सूददीपदीक्षश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'लषपतपदस्थाभूवृषहनकमगमशॄभ्य उकञ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'जल्पभिक्षकुट्टलुण्टवृङः षाकन् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'प्रजोरिनिः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'जिदृक्षिविश्रीण्वमाव्यथाभ्यमपरिभूप्रसूभ्यश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'स्पृहिगृहिपतिदयिनिद्रातन्द्राश्रद्धाभ्य आलुच् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'दाधेट्सिशदसदो रुः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'सृघस्यदः क्मरच् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'भञ्जभासमिदो घुरच् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'विदिभिदिच्छिदेः कुरच् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'इण्नश्जिसर्त्तिभ्यः क्वरप्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'गत्वरश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'जागुरूकः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'यजजपदशां यङः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'नमिकम्पिस्म्यजसकमहिंसदीपो रः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'सनाशंसभिक्ष उः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'विन्दुरिच्छुः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'क्याच्छन्दसि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'आदृगमहनजनः किकिनौ लिट् च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'स्वपितृषोर्नजिङ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'शॄवन्द्योरारुः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'भियः क्रुक्लुकनौ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'स्थेशभासपिसकसो वरच् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'यश्च यङः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने ताच्छील्य-अर्थ-अधिकारः'
"विधिः" = ''
"सूत्रम्" = 'भ्राजभासधुर्विद्युतोर्जिपॄजुग्रावस्तुवः क्विप्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'अन्येभ्योऽपि दृश्यते ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'भुवः संज्ञाऽन्तरयोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'विप्रसम्भ्यो ड्वसंज्ञायाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'धः कर्मणि ष्ट्रन् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'दाम्नीशसयुयुजस्तुतुदसिसिचमिहपतदशनहः करणे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'हलसूकरयोः पुवः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'अर्तिलूधूसूखनसहचर इत्रः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'पुवः संज्ञायाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'कर्तरि चर्षिदेवतयोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'ञीतः क्तः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'मतिबुद्धिपूजार्थेभ्यश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'वर्तमाने'
"विधिः" = ''
"सूत्रम्" = 'उणादयो बहुलम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''
