[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'कर्मणि उपपदे'
"परिणामः" = 'अण्'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् अण्'
"विधिः" = ''
"सूत्रम्" = '''
(उपपदम् अतिङ्)
कर्मण्यण् ।'''
"प्रभावोदाहरणम्" = 'कुम्भकारः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'शीलिकामिभक्ष्याचरिभ्यो णः (वार्तिकम्)'
"प्रभावोदाहरणम्" = 'मांसशीला । मांसकामा । मांसभक्षा । कल्याणाचारा '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'ईक्षिक्षमिभ्यां च (वार्तिकम्) ॥'
"प्रभावोदाहरणम्" = 'सुखप्रतीक्षा । बहुक्षामा ।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'कर्मणि उपपदे'
"परिणामः" = 'क'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् क'
"विधिः" = ''
"सूत्रम्" = 'ह्वावामश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'कर्मणि उपपदे'
"परिणामः" = 'क'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् क'
"विधिः" = ''
"सूत्रम्" = 'आतोऽनुपसर्गे कः ।'
"प्रभावोदाहरणम्" = 'तोयदः। जलप्रः। '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'कर्मणि उपपदे'
"परिणामः" = 'क'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् क'
"विधिः" = ''
"सूत्रम्" = 'सुपि स्थः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'कर्मणि उपपदे'
"परिणामः" = 'क'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् क'
"विधिः" = ''
"सूत्रम्" = 'तुन्दशोकयोः परिमृजापनुदोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'कर्मणि उपपदे'
"परिणामः" = 'क'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् क'
"विधिः" = ''
"सूत्रम्" = 'प्रे दाज्ञः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'कर्मणि उपपदे'
"परिणामः" = 'क'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् क'
"विधिः" = ''
"सूत्रम्" = 'समि ख्यः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'कर्मणि उपपदे'
"परिणामः" = 'ट'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् ट'
"विधिः" = ''
"सूत्रम्" = 'गापोष्टक् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'कर्मणि उपपदे'
"परिणामः" = 'अच्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् अच्'
"विधिः" = ''
"सूत्रम्" = 'हरतेरनुद्यमनेऽच् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'कर्मणि उपपदे'
"परिणामः" = 'अच्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् अच्'
"विधिः" = ''
"सूत्रम्" = 'वयसि च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'कर्मणि उपपदे'
"परिणामः" = 'अच्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् अच्'
"विधिः" = ''
"सूत्रम्" = 'आङि ताच्छील्ये ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'कर्मणि उपपदे'
"परिणामः" = 'अच्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् अच्'
"विधिः" = ''
"सूत्रम्" = 'अर्हः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'कर्मणि उपपदे'
"परिणामः" = 'अच्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् अच्'
"विधिः" = ''
"सूत्रम्" = 'स्तम्बकर्णयोः रमिजपोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'शं + धातुः'
"प्रत्ययः/ विवक्षा" = '''
संज्ञायाम्
कर्मणि उपपदे'''
"परिणामः" = 'अच्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् अच्'
"विधिः" = ''
"सूत्रम्" = 'शमि धातोः संज्ञायाम् ।'
"प्रभावोदाहरणम्" = 'शङ्करः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अच्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् अच्'
"विधिः" = ''
"सूत्रम्" = 'अधिकरणे शेतेः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ट'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् ट'
"विधिः" = ''
"सूत्रम्" = 'चरेष्टः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ट'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् ट'
"विधिः" = ''
"सूत्रम्" = 'भिक्षासेनाऽऽदायेषु च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ट'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् ट'
"विधिः" = ''
"सूत्रम्" = 'पुरोऽग्रतोऽग्रेषु सर्तेः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ट'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् ट'
"विधिः" = ''
"सूत्रम्" = 'पूर्वे कर्तरि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ट'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् ट'
"विधिः" = ''
"सूत्रम्" = 'कृञो हेतुताच्छील्यानुलोम्येषु ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ट'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् ट'
"विधिः" = ''
"सूत्रम्" = 'दिवाविभानिशाप्रभाभास्करान्तानन्तादिबहुनान्दीकिम्लिपिलिबिबलिभक्तिकर्तृचित्रक्षेत्रसंख्याजङ्घाबाह्वहर्यत्तत्धनुररुष्षु ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ट'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् ट'
"विधिः" = ''
"सूत्रम्" = 'कर्मणि भृतौ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ट'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् ट'
"विधिः" = ''
"सूत्रम्" = 'न शब्दश्लोककलहगाथावैरचाटुसूत्रमन्त्रपदेषु ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'इन्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् इन्'
"विधिः" = ''
"सूत्रम्" = 'स्तम्बशकृतोरिन् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'इन्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् इन्'
"विधिः" = ''
"सूत्रम्" = 'हरतेर्दृतिनाथयोः पशौ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'इन्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् इन्'
"विधिः" = ''
"सूत्रम्" = 'फलेग्रहिरात्मम्भरिश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'इन्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् इन्'
"विधिः" = ''
"सूत्रम्" = 'छन्दसि वनसनरक्षिमथाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'खश्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खश्'
"विधिः" = ''
"सूत्रम्" = 'एजेः खश् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'खश्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खश्'
"विधिः" = ''
"सूत्रम्" = 'नासिकास्तनयोर्ध्माधेटोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'खश्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खश्'
"विधिः" = ''
"सूत्रम्" = 'नाडीमुष्ट्योश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'खश्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खश्'
"विधिः" = ''
"सूत्रम्" = 'उदि कूले रुजिवहोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'खश्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खश्'
"विधिः" = ''
"सूत्रम्" = 'वहाभ्रे लिहः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'खश्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खश्'
"विधिः" = ''
"सूत्रम्" = 'परिमाणे पचः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'खश्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खश्'
"विधिः" = ''
"सूत्रम्" = 'मितनखे च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'खश्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खश्'
"विधिः" = ''
"सूत्रम्" = 'विध्वरुषोः तुदः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'खश्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खश्'
"विधिः" = ''
"सूत्रम्" = 'असूर्यललाटयोर्दृशितपोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'खश्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खश्'
"विधिः" = ''
"सूत्रम्" = 'उग्रम्पश्येरम्मदपाणिन्धमाश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'मुम् + खच्'
"प्रसिद्धिः" = '४'
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खच्'
"विधिः" = ''
"सूत्रम्" = 'प्रियवशे वदः खच् । (अरुर्द्विषदजन्तस्य मुम्। खचि ह्रस्वः। …)'
"प्रभावोदाहरणम्" = 'प्रियं वदति = प्रिय + वद् + खच् → प्रिय + मुम् + वद् + अ → प्रियंवद'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'मुम् + खच् (+डित्)'
"प्रसिद्धिः" = '४'
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खच्'
"विधिः" = ''
"सूत्रम्" = 'गमेः सुपि वाच्यः। खच्च डिद्वा वाच्यः। (वार्तिकम्) (अरुर्द्विषदजन्तस्य मुम्। खचि ह्रस्वः। …)'
"प्रभावोदाहरणम्" = 'मितङ्गमो हस्ती ← मित + मुम् + गम् + खच्। डिति -  भुज + मुम् + गम् + खच् + डित् → भुजङ्ग'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'खच्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खच्'
"विधिः" = ''
"सूत्रम्" = 'द्विषत्परयोस्तापेः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'खच्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खच्'
"विधिः" = ''
"सूत्रम्" = 'वाचि यमो व्रते ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'खच्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खच्'
"विधिः" = ''
"सूत्रम्" = 'पूःसर्वयोर्दारिसहोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'खच्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खच्'
"विधिः" = ''
"सूत्रम्" = 'सर्वकूलाभ्रकरीषेषु कषः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'खच्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खच्'
"विधिः" = ''
"सूत्रम्" = 'मेघर्तिभयेषु कृञः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'खच्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खच्'
"विधिः" = ''
"सूत्रम्" = 'क्षेमप्रियमद्रेऽण् च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'खच्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खच्'
"विधिः" = ''
"सूत्रम्" = 'आशिते भुवः करणभावयोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'खच्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खच्'
"विधिः" = ''
"सूत्रम्" = 'संज्ञायां भृतॄवृजिधारिसहितपिदमः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'सुपि उपपदे + गम्'
"प्रत्ययः/ विवक्षा" = 'संज्ञायां'
"परिणामः" = 'खच्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खच्'
"विधिः" = ''
"सूत्रम्" = 'गमश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = '{अन्त अत्यन्त अध्व दूर पार सर्व} उपपदे +‌गम्'
"प्रत्ययः/ विवक्षा" = 'कर्मणि उपपदे'
"परिणामः" = 'ड'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् ड'
"विधिः" = ''
"सूत्रम्" = 'अन्तात्यन्ताध्वदूरपारसर्वानन्तेषु डः ।'
"प्रभावोदाहरणम्" = '''
 = पार ङस् + गम् + अ 1-3-7, 1-3-9
= पार ङस् + ग् + अ By 6-4-143 टेः। डित्वसामर्थ्यादभस्यापि टेर्लोपः।
= पार ङस् + ग'''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'उरस्'
"प्रत्ययः/ विवक्षा" = 'करणे उपपदे'
"परिणामः" = 'ड'
"प्रसिद्धिः" = '१'
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् ड'
"विधिः" = ''
"सूत्रम्" = ' उरसो लोपश्च। (वा)'
"प्रभावोदाहरणम्" = 'उरगः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'शिष्ठप्रयुक्त-उपपदानि +‌गम्'
"प्रत्ययः/ विवक्षा" = 'कर्मणि उपपदे'
"परिणामः" = 'ड'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् ड'
"विधिः" = ''
"सूत्रम्" = 'अन्यत्रापि दृश्यत इति वक्तव्यम्। '
"प्रभावोदाहरणम्" = 'ग्रामगः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ड'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् ड'
"विधिः" = ''
"सूत्रम्" = 'आशिषि हनः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ड'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् ड'
"विधिः" = ''
"सूत्रम्" = 'अपे क्लेशतमसोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'णिनि'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् णिनि'
"विधिः" = ''
"सूत्रम्" = 'कुमारशीर्षयोर्णिनिः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'टक्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् टक्'
"विधिः" = ''
"सूत्रम्" = 'लक्षणे जायापत्योष्टक् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'टक्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् टक्'
"विधिः" = ''
"सूत्रम्" = 'अमनुष्यकर्तृके च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'टक्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् टक्'
"विधिः" = ''
"सूत्रम्" = 'शक्तौ हस्तिकपाटयोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'टक्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् टक्'
"विधिः" = ''
"सूत्रम्" = 'पाणिघताडघौ शिल्पिनि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'खुन्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'कर्मणि उपपदे कृत् खुन्'
"विधिः" = ''
"सूत्रम्" = 'आढ्यसुभगस्थूलपलितनग्नान्धप्रियेषु च्व्य्र्थेष्वच्वौ कृञः करणे ख्युन् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'खिष्णुच्-खुकञ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = 'खिष्णुच्-खुकञ्'
"विधिः" = ''
"सूत्रम्" = 'कर्तरि भुवः खिष्णुच्खुकञौ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'इगुपधज्ञाप्रीकिरः कः'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = 'https://docs.google.com/spreadsheets/d/1RLjgNfdlXUicMbR6x9XEfxlgTL-qbqIY9jNtpcX2mHA/edit#gid=6'

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'आतश्चोपसर्गे'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = 'https://docs.google.com/spreadsheets/d/1RLjgNfdlXUicMbR6x9XEfxlgTL-qbqIY9jNtpcX2mHA/edit#gid=6'

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = '४'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'पाघ्राध्माधेट्दृशः शः'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = 'https://docs.google.com/spreadsheets/d/1RLjgNfdlXUicMbR6x9XEfxlgTL-qbqIY9jNtpcX2mHA/edit#gid=6'

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''
