[[data]]
"समासः" = ''
"समासविशेषः" = ''
"परिणामः" = ''
"अवधानावश्यकता" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'चार्थे द्वन्द्वः (अनेकम्)॥'
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = 'द्वन्द्वः इतरेतरः'
"समासविशेषः" = ''
"परिणामः" = ''
"अवधानावश्यकता" = ''
"विधिप्रकारः" = 'द्विपदद्वन्द्वः'
"सूत्रम्" = 'चार्थे द्वन्द्वः (अनेकम्)॥'
"समस्तपदम् उदाहरणम्" = 'रामलक्ष्मणौ रामश्च लक्ष्मणश्च'
"विवरणम्" = 'मिलितानाम् अन्वयः इतरेतरः। '
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = 'द्वन्द्वः समाहारः'
"समासविशेषः" = 'समाहारः'
"परिणामः" = ''
"अवधानावश्यकता" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'चार्थे द्वन्द्वः (अनेकम्)॥'
"समस्तपदम् उदाहरणम्" = 'पुत्रपौत्रम्'
"विवरणम्" = 'समूहः समाहारः।'
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = ''
"समासविशेषः" = ''
"परिणामः" = ''
"अवधानावश्यकता" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = 'द्विगुः'
"समासविशेषः" = ''
"परिणामः" = 'एकवचनम्'
"अवधानावश्यकता" = '५'
"विधिप्रकारः" = 'एकवद्भावः द्विगुद्वन्द्वयोः वचननिर्णयः'
"सूत्रम्" = 'द्विगुरेकवचनम्‌ ।'
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = ''
"समासविशेषः" = ''
"परिणामः" = ''
"अवधानावश्यकता" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = '''

समाहारग्रहणं कर्तव्यम् (वा)'''
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = 'द्वन्द्वः समाहारः'
"समासविशेषः" = 'प्राणि-तूर्य-सेना-अङ्गः'
"परिणामः" = 'एकवचनम्'
"अवधानावश्यकता" = '४'
"विधिप्रकारः" = 'एकवद्भावः द्विगुद्वन्द्वयोः वचननिर्णयः'
"सूत्रम्" = 'द्वंद्वश्च प्राणितूर्यसेनाङ्गानाम्‌ ।'
"समस्तपदम् उदाहरणम्" = 'प्राण्यङ्गानां तावत् पाणिपादम्। शिरोग्रीवम्। तूर्याङ्गानाम् मार्दङ्गिकपाणविकम्। वीणावदकपरिवादकम्। सेनाऽङ्गानाम् रथिकाश्वारोहम्। रथिकपादातम्। '
"विवरणम्" = 'समाहारस्यैकत्वादेकत्वे सिद्धे नियमार्थं प्रकरणम्। (इतरेतरद्वन्द्वो न भवितुमर्हति अत्र।)'
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = 'द्वन्द्वः समाहारः'
"समासविशेषः" = 'स्था-इण्-धात्वोः‌ लुङ्-रूपेण साकं योगे'
"परिणामः" = ''
"अवधानावश्यकता" = '१'
"विधिप्रकारः" = 'एकवद्भावः द्विगुद्वन्द्वयोः वचननिर्णयः'
"सूत्रम्" = '''
अनुवादे चरणानाम्‌ ।
स्थेणोरद्यतन्यां चेति वक्तव्यम्।  (वा)'''
"समस्तपदम् उदाहरणम्" = '''
उदगात् कठकालापम्।
प्रत्यष्ठात् कठकौथुमम्। '''
"विवरणम्" = 'शाखाध्येतृविशेषाः चरणाः।'
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = 'द्वन्द्वः समाहारः'
"समासविशेषः" = 'यजुर्वेदक्रतुः अनपुंसकलिङ्गकः'
"परिणामः" = ''
"अवधानावश्यकता" = '१'
"विधिप्रकारः" = 'एकवद्भावः द्विगुद्वन्द्वयोः वचननिर्णयः'
"सूत्रम्" = 'अध्वर्युक्रतुरनपुंसकम्. ।'
"समस्तपदम् उदाहरणम्" = 'अर्काश्वमेधम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = 'द्वन्द्वः समाहारः'
"समासविशेषः" = '''
वेद-अध्ययनक्रमे-समीपस्थाः
संहिता-पद-क्रम-विकृति…'''
"परिणामः" = ''
"अवधानावश्यकता" = '१'
"विधिप्रकारः" = 'एकवद्भावः द्विगुद्वन्द्वयोः वचननिर्णयः'
"सूत्रम्" = 'अध्ययनतोऽविप्रकृष्टाख्यानाम्‌ ।'
"समस्तपदम् उदाहरणम्" = 'पदकक्रमकम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = 'द्वन्द्वः समाहारः'
"समासविशेषः" = '''
प्राणिवर्ज-जातिः द्रव्य-जातिः।
(वृक्ष-मृगादिषु विप्रतिषेधाभावे)'''
"परिणामः" = ''
"अवधानावश्यकता" = '३'
"विधिप्रकारः" = 'एकवद्भावः द्विगुद्वन्द्वयोः वचननिर्णयः'
"सूत्रम्" = 'जातिरप्राणिनाम्‌ ।'
"समस्तपदम् उदाहरणम्" = 'धाना-शष्कुलि (चक्कुलि)'
"विवरणम्" = ''
"अभावोदाहरणम्" = '''
प्राणिनां तु - विट्-शूद्राः।
जातिविवक्षाभावे - बदरामलकानि'''

[[data]]
"समासः" = 'द्वन्द्वः समाहारः'
"समासविशेषः" = '''
भिन्नलिङ्गकाः
नदयः / देशाः अग्रामाः'''
"परिणामः" = ''
"अवधानावश्यकता" = '२'
"विधिप्रकारः" = 'एकवद्भावः द्विगुद्वन्द्वयोः वचननिर्णयः'
"सूत्रम्" = 'विशिष्टलिङ्गो नदीदेशोऽग्रामाः ।'
"समस्तपदम् उदाहरणम्" = 'सरस्वतीब्रह्मपुत्रम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = 'द्वन्द्वः समाहारः'
"समासविशेषः" = 'क्षुद्रजन्तवः '
"परिणामः" = ''
"अवधानावश्यकता" = '३'
"विधिप्रकारः" = 'एकवद्भावः द्विगुद्वन्द्वयोः वचननिर्णयः'
"सूत्रम्" = 'क्षुद्रजन्तवः ।'
"समस्तपदम् उदाहरणम्" = 'यूकलिक्षम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = 'द्वन्द्वः समाहारः'
"समासविशेषः" = 'विरोधिनः द्रव्यवाचिनः'
"परिणामः" = ''
"अवधानावश्यकता" = '४'
"विधिप्रकारः" = 'एकवद्भावः द्विगुद्वन्द्वयोः वचननिर्णयः'
"सूत्रम्" = '''
येषां च विरोधः शाश्वतिकः ।
[विप्रतिषिद्धं चानधिकरणवाचि ।]'''
"समस्तपदम् उदाहरणम्" = 'अहिनकुलम्'
"विवरणम्" = 'च-कारः "विभाषा वृक्ष…" इत्यादेः बाधनार्थम्।'
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = 'द्वन्द्वः समाहारः'
"समासविशेषः" = 'शूद्राः अबहिष्कृताः'
"परिणामः" = ''
"अवधानावश्यकता" = '३'
"विधिप्रकारः" = 'एकवद्भावः द्विगुद्वन्द्वयोः वचननिर्णयः'
"सूत्रम्" = 'शूद्राणामनिरवसितानाम्‌ ।'
"समस्तपदम् उदाहरणम्" = 'तक्षायस्कारम्'
"विवरणम्" = 'यैर् भुक्तं पात्रं संस्कारेन शुध्यति, ते ऽनिरवसिताः।'
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = 'द्वन्द्वः समाहारः'
"समासविशेषः" = 'गवाश्वप्रभृतीनि'
"परिणामः" = ''
"अवधानावश्यकता" = '२'
"विधिप्रकारः" = 'एकवद्भावः द्विगुद्वन्द्वयोः वचननिर्णयः'
"सूत्रम्" = 'गवाश्वप्रभृतीनि च ।'
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = 'च-कारः "विभाषा वृक्ष…" इत्यादेः बाधनार्थम्।'
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = 'द्वन्द्वः समाहारः वा'
"समासविशेषः" = '''
वृक्ष मृग तृण धन्य व्यञ्जन पशु शकुनि अश्ववडव पूर्वापर अधरोत्तर
(विप्रतिषेधाभावे स्वजातौ)'''
"परिणामः" = ''
"अवधानावश्यकता" = '४'
"विधिप्रकारः" = 'एकवद्भावः द्विगुद्वन्द्वयोः वचननिर्णयः'
"सूत्रम्" = '''
विभाषा वृक्षमृगतृणधान्यव्यञ्जनपशुशकुन्यश्ववडवपूर्वापराधरोत्तराणाम्‌ ।
वृक्षादौ विशेषाणामेव ग्रहणम् (वा)'''
"समस्तपदम् उदाहरणम्" = 'पलाशन्यग्रोधम् | पलाशन्यग्रोधौ'
"विवरणम्" = '''
"जातिरप्राणिनाम्‌" इत्यस्य प्रतिषेधार्थम्।
'''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = 'द्वन्द्वः समाहारः न।'
"समासविशेषः" = '''
मृगाणां अमृगैस् सह|‌
शकुनीनां अशकुनिभिस् सह |
पूर्व (^अपर)|
अधर (^उत्तर)'''
"परिणामः" = ''
"अवधानावश्यकता" = '४'
"विधिप्रकारः" = 'एकवद्भावः द्विगुद्वन्द्वयोः वचननिर्णयः'
"सूत्रम्" = '''
विभाषा वृक्षमृगतृणधान्यव्यञ्जनपशुशकुन्यश्ववडवपूर्वापराधरोत्तराणाम्‌ ।
वृक्षादौ विशेषाणामेव ग्रहणम् (वा)।
(उपरि मृग-शकुनि-पूर्वापर-अधरोत्तर-ग्रहणं नियमार्थम्।)'''
"समस्तपदम् उदाहरणम्" = 'मृगपक्षिणः'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = 'द्वन्द्वः समाहारः न।'
"समासविशेषः" = 'फल-सेना-वनस्पति-मृग-शकुनि-क्षुद्र-जन्तु-धान्य-तृणानां द्विप्रकृतित्वे'
"परिणामः" = ''
"अवधानावश्यकता" = '३'
"विधिप्रकारः" = 'एकवद्भावः द्विगुद्वन्द्वयोः वचननिर्णयः'
"सूत्रम्" = 'फले-सेना-वनस्पति-मृग-शकुनि-क्षुद्र-जन्तु-धान्य-तृणानां बहुप्रकृतिरेव द्वन्द्व एकवदिति वाच्यम्।'
"समस्तपदम् उदाहरणम्" = 'रथिकाश्वारोहौ बदरामलके। '
"विवरणम्" = 'रथिकाश्वरुहम् |‌रथिकाश्वरुहाः'
"अभावोदाहरणम्" = 'रथिकाश्वारोहौ'

[[data]]
"समासः" = 'द्वन्द्वः समाहारः वा'
"समासविशेषः" = 'विरोधिनः अद्रव्यवाचिनः'
"परिणामः" = ''
"अवधानावश्यकता" = '४'
"विधिप्रकारः" = 'एकवद्भावः द्विगुद्वन्द्वयोः वचननिर्णयः'
"सूत्रम्" = 'विप्रतिषिद्धं चानधिकरणवाचि ।'
"समस्तपदम् उदाहरणम्" = 'शीतोष्णम् |‌शीतोष्णे'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = 'द्वन्द्वः समाहारः न।'
"समासविशेषः" = 'दधिपयाअदीनि'
"परिणामः" = ''
"अवधानावश्यकता" = '२'
"विधिप्रकारः" = '  द्विगुद्वन्द्वयोः वचननिर्णयः'
"सूत्रम्" = 'न दधिपयआदीनि ।'
"समस्तपदम् उदाहरणम्" = 'दधिपयसी ऋक्सामे वाङ्मनसे'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = 'द्वन्द्वः समाहारः न।'
"समासविशेषः" = 'द्रव्य-सङ्ख्यावगमे'
"परिणामः" = ''
"अवधानावश्यकता" = '३'
"विधिप्रकारः" = '  द्विगुद्वन्द्वयोः वचननिर्णयः'
"सूत्रम्" = 'अधिकरणैतावत्त्वे च ।'
"समस्तपदम् उदाहरणम्" = 'दश दन्तोष्ठाः।'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = 'द्वन्द्वः समाहारः वा'
"समासविशेषः" = 'द्रव्य-समीपसङ्ख्यावगमे'
"परिणामः" = ''
"अवधानावश्यकता" = '३'
"विधिप्रकारः" = '  द्विगुद्वन्द्वयोः वचननिर्णयः'
"सूत्रम्" = 'विभाषा समीपे ।'
"समस्तपदम् उदाहरणम्" = '''
उपदशं दन्तोष्ठम्।
उपदशाः दन्तोष्ठाः।'''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = '''
द्विगु-समाहारः|
द्वन्द्व-समाहारः'''
"समासविशेषः" = ''
"परिणामः" = 'क्लौब्यम्'
"अवधानावश्यकता" = '५'
"विधिप्रकारः" = 'नपुंसकम्  द्विगु-द्वन्द्व-अव्ययीभावानां लिङ्गनिर्णयः'
"सूत्रम्" = 'स नपुंसकम् ।'
"समस्तपदम् उदाहरणम्" = 'संज्ञापरिभाषम् इति द्वन्द्वे।'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = 'अव्ययीभावः'
"समासविशेषः" = ''
"परिणामः" = 'क्लौब्यम्'
"अवधानावश्यकता" = '५'
"विधिप्रकारः" = 'नपुंसकम्  द्विगु-द्वन्द्व-अव्ययीभावानां लिङ्गनिर्णयः'
"सूत्रम्" = 'अव्ययीभावश्च ।'
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = ''
"समासविशेषः" = ''
"परिणामः" = ''
"अवधानावश्यकता" = ''
"विधिप्रकारः" = 'नपुंसकम्  तत्पुरुषे'
"सूत्रम्" = 'तत्पुरुषोऽनञ्‌ कर्मधारयः ।'
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = ''
"समासविशेषः" = ''
"परिणामः" = ''
"अवधानावश्यकता" = ''
"विधिप्रकारः" = 'नपुंसकम्'
"सूत्रम्" = 'संज्ञायां कन्थोशीनरेषु ।'
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = ''
"समासविशेषः" = ''
"परिणामः" = ''
"अवधानावश्यकता" = ''
"विधिप्रकारः" = 'नपुंसकम्'
"सूत्रम्" = 'उपज्ञोपक्रमं तदाद्याचिख्यासायाम्‌ ।'
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = ''
"समासविशेषः" = ''
"परिणामः" = ''
"अवधानावश्यकता" = ''
"विधिप्रकारः" = 'नपुंसकम्'
"सूत्रम्" = 'छाया बाहुल्ये ।'
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = ''
"समासविशेषः" = ''
"परिणामः" = ''
"अवधानावश्यकता" = ''
"विधिप्रकारः" = 'नपुंसकम्'
"सूत्रम्" = 'सभा राजाऽमनुष्यपूर्वा ।'
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = ''
"समासविशेषः" = ''
"परिणामः" = ''
"अवधानावश्यकता" = ''
"विधिप्रकारः" = 'नपुंसकम्'
"सूत्रम्" = 'अशाला च ।'
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = ''
"समासविशेषः" = ''
"परिणामः" = ''
"अवधानावश्यकता" = ''
"विधिप्रकारः" = 'नपुंसकम्'
"सूत्रम्" = 'विभाषा सेनासुराछायाशालानिशानाम्‌ ।'
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = '''
इतरेतरद्वन्द्वः |
तत्पुरुषः'''
"समासविशेषः" = 'अपवादाभावे'
"परिणामः" = 'परवत्'
"अवधानावश्यकता" = '५'
"विधिप्रकारः" = 'द्वन्द्व-तत्पुरुषयोः लिङ्गनिर्णयः'
"सूत्रम्" = 'परवल्लिङ्गं द्वन्द्वतत्पुरुषयोः ।'
"समस्तपदम् उदाहरणम्" = '''
कुक्कुटमयूर्यौ/मयूरीकुक्कुटौ
अर्धपिप्पली'''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = 'द्विगुसमासः'
"समासविशेषः" = ''
"परिणामः" = ''
"अवधानावश्यकता" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = ''
"समस्तपदम् उदाहरणम्" = 'पञ्चकपालः'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = '''
इतरेतरद्वन्द्वः |
तत्पुरुषः'''
"समासविशेषः" = 'प्राप्त'
"परिणामः" = '- परवत्'
"अवधानावश्यकता" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'द्विगुप्राप्तापन्नालम्पूर्वगतिसमासेषु प्रतिषेधो वाच्यः (वा)'
"समस्तपदम् उदाहरणम्" = 'प्राप्तजीविकः'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = '''
इतरेतरद्वन्द्वः |
तत्पुरुषः'''
"समासविशेषः" = 'आपन्न'
"परिणामः" = '- परवत्'
"अवधानावश्यकता" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'द्विगुप्राप्तापन्नालम्पूर्वगतिसमासेषु प्रतिषेधो वाच्यः (वा)'
"समस्तपदम् उदाहरणम्" = 'आपन्नजीविकः'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = '''
इतरेतरद्वन्द्वः |
तत्पुरुषः'''
"समासविशेषः" = 'अलम्'
"परिणामः" = '- परवत्'
"अवधानावश्यकता" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'द्विगुप्राप्तापन्नालम्पूर्वगतिसमासेषु प्रतिषेधो वाच्यः (वा)'
"समस्तपदम् उदाहरणम्" = 'अलङ्क्लुमारिः'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = '''
इतरेतरद्वन्द्वः |
तत्पुरुषः'''
"समासविशेषः" = 'गतिसमासः'
"परिणामः" = '- परवत्'
"अवधानावश्यकता" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'द्विगुप्राप्तापन्नालम्पूर्वगतिसमासेषु प्रतिषेधो वाच्यः (वा)'
"समस्तपदम् उदाहरणम्" = 'निष्कौशाम्बिः'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = ''
"समासविशेषः" = ''
"परिणामः" = ''
"अवधानावश्यकता" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = ''
"समासविशेषः" = 'अश्ववडवौ'
"परिणामः" = 'पूर्ववत् |‌नपुम्'
"अवधानावश्यकता" = ''
"विधिप्रकारः" = 'द्वन्द्व-तत्पुरुषयोः लिङ्गनिर्णयः'
"सूत्रम्" = '''
पूर्ववदश्ववडवौ ।
[विभाषा वृक्षमृग …]'''
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = ''
"समासविशेषः" = ''
"परिणामः" = ''
"अवधानावश्यकता" = '१'
"विधिप्रकारः" = 'द्वन्द्व-तत्पुरुषयोः लिङ्गनिर्णयः'
"सूत्रम्" = 'हेमन्तशिशिरावहोरात्रे च च्छन्दसि ।'
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = ''
"समासविशेषः" = ''
"परिणामः" = ''
"अवधानावश्यकता" = ''
"विधिप्रकारः" = 'द्वन्द्व-तत्पुरुषयोः लिङ्गनिर्णयः'
"सूत्रम्" = 'रात्राह्नाहाः पुंसि ।'
"समस्तपदम् उदाहरणम्" = 'सप्ताहः।'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = ''
"समासविशेषः" = ''
"परिणामः" = ''
"अवधानावश्यकता" = '२'
"विधिप्रकारः" = 'द्वन्द्व-तत्पुरुषयोः लिङ्गनिर्णयः'
"सूत्रम्" = 'अपथं नपुंसकम्‌ ।'
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = ''
"समासविशेषः" = ''
"परिणामः" = ''
"अवधानावश्यकता" = '१'
"विधिप्रकारः" = 'द्वन्द्व-तत्पुरुषयोः लिङ्गनिर्णयः '
"सूत्रम्" = 'अर्धर्चाः पुंसि च ।'
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = ''
"समासविशेषः" = ''
"परिणामः" = ''
"अवधानावश्यकता" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = ''
"समासविशेषः" = ''
"परिणामः" = 'क्लैब्यम्'
"अवधानावश्यकता" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = '''
पात्राद्यन्तस्य न।
सङ्ख्यापूर्वं रात्रं क्लीबम्।'''
"समस्तपदम् उदाहरणम्" = 'पञ्चपात्रम्, त्रिभुवनम्, चतुर्युगम् ।'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासः" = ''
"समासविशेषः" = ''
"परिणामः" = '''
ईकारादेशः
स्त्रीत्वम्'''
"अवधानावश्यकता" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = '''
अकारान्तोत्तरपदो द्विगुः स्त्रियाम् इष्टः [वा]
द्विगोः (ङीप्)'''
"समस्तपदम् उदाहरणम्" = 'त्रिलोकी, पञ्चवटी ।'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''
