[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परिणामः" = 'अनुनासिकस्वरो वा'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'रुँ, पूर्वस्यानुनासिको वा'
"विधिः" = 'अधिकारसूत्रम्।'
"सूत्रम्" = 'अत्रानुनासिकः पूर्वस्य तु वा (अधिकारसूत्रम्)'
"उदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = 'छान्दसो व्यत्ययः - इत उत्तरं यस्य स्थाने रुँः विधीयते ततः पूर्वस्य तु वर्णस्य वा अनुनासिको भवति।'

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'आत्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अट् (=अच् + हयवरट्)'
"परिणामः" = 'अनुनासिकस्वरः'
"प्रामुख्यम्" = '३'
"विधिप्रकारः" = 'रुँ, पूर्वस्यानुनासिकः'
"विधिः" = ''
"सूत्रम्" = 'आतोऽटि नित्यम् ।'
"उदाहरणम्" = '''म॒हाँ इन्द्रः॑।  
महान् असि → 
महारुँ असि [दीर्घादटि समानपादे]→  
महाँय् असि [भोभगोअघोअपूर्वस्य योऽशि] →  
महाँ असि [लोपः शाकल्यस्य]
'''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = '''
अभावः - देवां ऋतुभिः कल्पयाति (कृष्णयजुर्वेदः १.१.१४)।  
'''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = '(-अनुनासिकः)'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'रुँ'
"परिणामः" = ' + ं'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'रुँ, पूर्वस्यानुनासिको वा'
"विधिः" = 'परिभाषा सूत्रम्'
"सूत्रम्" = 'अनुनासिकात्‌ परोऽनुस्वारः ।'
"उदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'सम्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'सुँट्'
"परिणामः" = ' + ं, रुँ | ँ रुँ'
"प्रामुख्यम्" = '४'
"विधिप्रकारः" = 'रुँ, पूर्वस्यानुनासिको वा'
"विधिः" = ''
"सूत्रम्" = 'समः सुटि ।'
"उदाहरणम्" = '''सँस्कर्ता। सँस्कर्तुम्। सँस्कर्तव्यम्। संस्स्कर्ता। संस्स्कर्तुम्। संस्स्कर्तव्यम्।  
सम् + सुट् + कर्तृ (सम्परिभ्यां करोतौ भूषणे) → सँ रुँ + स् + कर्तृ / सं रुँ स् कर्तृ'''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'पुम्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'खय् + अम् प्रत्याहारः'
"परिणामः" = ' + ं, रुँ | ँ रुँ'
"प्रामुख्यम्" = '४'
"विधिप्रकारः" = 'रुँ, पूर्वस्यानुनासिको वा'
"विधिः" = ''
"सूत्रम्" = 'पुमः खय्यम्परे ।'
"उदाहरणम्" = 'पुँस्कामा, पुंस्कामा ।  पुँस्कोकिलः / पुंस्कोकिलः।'
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = '*न् (-प्रशान्)'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अम् (vowel, semi-vowel and nasal) प्रत्याहारौ + छव् (छ ठ थ च ट त) '
"परिणामः" = ' + ं, रुँ | ँ रुँ'
"प्रामुख्यम्" = '५'
"विधिप्रकारः" = 'रुँ, पूर्वस्यानुनासिको वा'
"विधिः" = ''
"सूत्रम्" = 'नश् छव्य् अप्रशान् ।'
"उदाहरणम्" = 'भवांश्चरति, भवाँश्चरति। भवांस्तरति, भवाँस्तरति ।'
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = '*न्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अम् (vowel, semi-vowel and nasal) प्रत्याहारौ + छव् (छ ठ थ च ट त) '
"परिणामः" = ' + ं, रुँ | ँ रुँ'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'रुँ, पूर्वस्यानुनासिको वा| ०'
"विधिः" = ''
"सूत्रम्" = 'उभयथा +ऋक्षु ।'
"उदाहरणम्" = 'तस्मिंस्त्वा दधाति, तस्मिँस्त्वा दधाति, तस्मिन् त्वा दधाति।'
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'दीर्घः+ न्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अट्'
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'रुँ, पूर्वस्यानुनासिको वा| ०'
"विधिः" = ''
"सूत्रम्" = 'दीर्घादटि समानपदे (ऋक्षु)।'
"उदाहरणम्" = 'दे॒वां अच्छा॑ सुम॒ती। दे॒वाँ अच्छा॑ सुम॒ती। आ॒दित्यान्या॑चिषामहे।'
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'रुँ, पूर्वस्यानुनासिको वा| ०'
"विधिः" = ''
"सूत्रम्" = 'नॄन् पे ।'
"उदाहरणम्" = ' नॄन्पाहि । नॄँः पाहि / नॄंः पाहि / नॄँः≍पाहि / नॄंः≍पाहि'
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'स्वतवान्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'पायु'
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'रुँ, पूर्वस्यानुनासिको वा|०'
"विधिः" = ''
"सूत्रम्" = 'स्वतवान् पायौ ।'
"उदाहरणम्" = 'स्वतवान्पायुः। स्वतवाँः पायुः / स्वतवांः पायुः।'
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'कान्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'कान्'
"परिणामः" = ''
"प्रामुख्यम्" = '५'
"विधिप्रकारः" = 'रुँ, पूर्वस्यानुनासिको वा'
"विधिः" = ''
"सूत्रम्" = 'कानाम्रेडिते ।'
"उदाहरणम्" = 'काँस्कान्, कांस्कान्'
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

