[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = '''
ह्
[अपवाद उक्तः]'''
"उत्तराक्षरम् सन्धिपूर्वम्" = 'झल्/ अवसाने'
"परवर्णस्थितिः" = ''
"परिणामः" = 'ढ्'
"प्रामुख्यम्" = '५'
"विधिप्रकारः" = 'हकारादेशः'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''

हो ढः [पदस्य अन्ते च (अपदान्ते) झलि]'''
"उदाहरणम्" = '''
बाबृंह्‌ + सि → हो ढः → बाबृढ्‌ + सि → एकाचो बशो भष्‌ झषन्तस्य स्ध्वोः → बाभृंढ्‌ + सि → षढोः कः सि → बाभृंक्‌ + सि → आदेशप्रत्यययोः → बाभृंक्‌ + षि → बाभृंक्षि
अतृणेह्त् - अतृणेह् - अतृणेढ्'''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = 'दादिः धातुः'
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'ह्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'झल्/ अवसाने'
"परवर्णस्थितिः" = ''
"परिणामः" = 'घ्'
"प्रामुख्यम्" = '४'
"विधिप्रकारः" = 'हकारादेशः'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''
हो ढः।
दादेर्धातोर्घः  [हो पदस्य अन्ते च (अपदान्ते) झलि]'''
"उदाहरणम्" = '''
दोग्धुम्
(झलां जश् झशि इत्यस्मात् घ् -> ग्)
दह्‌ + स्यति → धक्‌ + ष्यति → धक्ष्यति
अदोह्‌ + त्‌ → अदोह्‌ → अदोघ्‌ -> अधोघ्'''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'नह्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'झल्/ अवसाने'
"परवर्णस्थितिः" = ''
"परिणामः" = 'ध्'
"प्रामुख्यम्" = '१'
"विधिप्रकारः" = 'हकारादेशः'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''
हो ढः।
नहो धः [हो पदस्य अन्ते च (अपदान्ते) झलि]'''
"उदाहरणम्" = '''
नह्‌ + स्यति → नहो धः → नध्‌ + स्यति → खरि च → नत्‌ + स्यति → नत्स्यति
अनानह्‌ + त्‌ → अनानह्‌ → अनानध्‌'''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = 'द्रुह्‌, मुह्‌, ष्णुह्‌, ष्णिह्‌ धातुः + '
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'ह्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'झल्/ अवसाने'
"परवर्णस्थितिः" = ''
"परिणामः" = 'ढ् घ् वा'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'हकारादेशः'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''
हो ढः।
वा द्रुहमुहष्णुहष्णिहाम् [हो पदस्य अन्ते च (अपदान्ते) झलि]'''
"उदाहरणम्" = 'अस्नेनेह्‌ → अस्नेनेघ्‌ / अस्नेनेढ्‌'
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ' - नह् / दादिः'
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'ह्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'स्'
"परवर्णस्थितिः" = ''
"परिणामः" = 'क्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'हकारादेशः'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''
हो ढः।
वा द्रुहमुहष्णुहष्णिहाम् [हो पदस्य अन्ते च (अपदान्ते) झलि]॥
षढोः कः सि॥'''
"उदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = 'बशादिः धातुः'
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'झष् अन्ते'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'स् ध्व'
"परवर्णस्थितिः" = ''
"परिणामः" = 'भष्'
"प्रामुख्यम्" = '३'
"विधिप्रकारः" = ''
"विधिः" = 'आदेशः आदिवर्णस्य'
"सूत्रम्" = 'एकाचो बशो भष्‌ झषन्तस्य स्ध्वोः (धातोः, पदस्य अन्ते वा)'
"उदाहरणम्" = 'बुध् + स्यति = बोध् + स्यति = भोध् + स्यति = भोत्स्यति (खरि च)'
"पश्चात्तनक्रिया" = ''
"विवरणम्" = '३४ → ४४'

[[data]]
"पूर्वाक्षरस्थितिः" = ' एकाच्‌-बशादि-झषन्तः'
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'बश्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'स्/ ध्व/ अवसाने'
"परवर्णस्थितिः" = ''
"परिणामः" = 'भष्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = 'एकाचो बशो भष्‌ झषन्तस्य स्ध्वोः'
"उदाहरणम्" = 'अदोह्‌ + त्‌ → अदोह्‌ → अदोघ्‌ -> अधोघ्'
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'स्/श्/ष् कु +‌हल्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'झल्/ अवसाने'
"परवर्णस्थितिः" = ''
"परिणामः" = 'लोपः'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = 'आदेशः‌ पूर्वस्य'
"सूत्रम्" = 'स्कोः संयोगाद्योरन्ते च [लोपः पदस्य अन्ते झलि]।'
"उदाहरणम्" = '''
अबरीब्रस्ज् - अबरीब्रज्
अवाव्रश्च् - अवाव्रच्'''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = '''
चुँ
[अपवादाः उक्तः]'''
"उत्तराक्षरम् सन्धिपूर्वम्" = '(झल् - स्)/ अवसाने'
"परवर्णस्थितिः" = ''
"परिणामः" = 'कुँ'
"प्रामुख्यम्" = '५'
"विधिप्रकारः" = 'श्चोः कुत्वम्'
"विधिः" = 'आदेशः परस्य'
"सूत्रम्" = '(पदान्ते च) चोः कुः (झलि च)।'
"उदाहरणम्" = '''
भुंज् + तः = भुङ्क्तः
वाच्+भ्याम् = वाग्भ्याम् (पदसंज्ञायाम्)
रुज्+विनिश्चयः = रुग्विनिश्चयः
'''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = '''
व्रश्च भ्रस्ज सृज मृज यज राज भ्राज
वा छ/श-कारान्त-धातुः'''
"उत्तराक्षरम् सन्धिपूर्वम्" = 'स्'
"परवर्णस्थितिः" = ''
"परिणामः" = 'क्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'श्चोः कुत्वम्'
"विधिः" = 'आदेशः‌पूर्वस्य'
"सूत्रम्" = '''
[(पदान्ते च) चोः कुः (झलि च)।]
व्रश्चभ्रस्जसृजमृजयजराजभ्राजच्छशां षः ।
[षढोः कः सि॥]'''
"उदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = '''
व्रश्च भ्रस्ज सृज मृज यज राज भ्राज
वा छ/श-कारान्त-धातुः'''
"उत्तराक्षरम् सन्धिपूर्वम्" = 'झल्/ अवसाने'
"परवर्णस्थितिः" = ''
"परिणामः" = 'ष्'
"प्रामुख्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = 'आदेशः‌पूर्वस्य'
"सूत्रम्" = '''
[(पदान्ते च) चोः कुः (झलि च)।]
व्रश्चभ्रस्जसृजमृजयजराजभ्राजच्छशां षः ।'''
"उदाहरणम्" = 'अवाव्रश्च् - अवाव्रच् - अवाव्रष्'
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

