[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'प्रत्ययः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'परश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'आद्युदात्तश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'अनुदत्तौ सुप्पितौ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = '''
गुप् तिज् कित्
निन्दा-क्षमा-व्याधि-प्रतीकारेषु'''
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'सन्'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = '''
गुप्तिज्किद्भ्यः सन् ।
निन्दा-क्षमा-व्याधि-प्रतीकारेषु सन्निष्यते  
ऽन्यत्र यथा प्राप्तं प्रत्यया भवन्ति।'''
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = '''
मानेर् जिज्ञासायाम्, बधेर् वैरूप्ये,
दानेरार्जवे, शानेर् निशाने।'''
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'सन्, अभ्यासस्य दीर्घः'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = '''
मान्बधदान्शान्भ्यो दीर्घश्चाभ्यासस्य ।
अत्रापि सन्नर्थविशेष इष्यते।'''
"प्रभावोदाहरणम्" = 'मीमांसते।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'धातुः - इच्छासन्नन्तः'
"प्रत्ययः/ विवक्षा" = 'इच्छायाम्'
"परिणामः" = 'सन्'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"सूत्रम्" = '''
धातोः कर्मणः समानकर्तृकादिच्छायां वा ।
(इच्छासन्नन्तात् प्रतिषेधो वक्तव्यः।)'''
"प्रभावोदाहरणम्" = '''
जिगमिषति, चखादिषति
लभ् - लिप्सति
दा - दित्सति
धा - धित्सति
मीमांसिषते।'''
"अभावोदाहरणम्" = 'चिकीर्षितुम् इच्छति।'
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'धातुः - इच्छासन्नन्तः'
"प्रत्ययः/ विवक्षा" = 'आशङ्कायाम्'
"परिणामः" = 'सन् वा'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = '''
आशङ्कायाम् उपसंख्यानम्।
(इच्छासन्नन्तात् प्रतिषेधो वक्तव्यः।)'''
"प्रभावोदाहरणम्" = 'आशङ्के पतिष्यति कूलम्, पिपतिषति कूलम्।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = 'न मान्तम् अव्ययम्। कर्मसंज्ञा'
"अङ्गम्" = 'सुबन्तम्'
"प्रत्ययः/ विवक्षा" = '''
इच्छा आत्मसम्बद्धा
(न अन्याय)'''
"परिणामः" = 'क्यच्'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"सूत्रम्" = '''
सुप आत्मनः क्यच् ।
क्यचि मान्ताव्ययप्रतिषेधो वक्तव्यः।'''
"प्रभावोदाहरणम्" = 'पुत्रीयति = आत्मनो पुत्रम् इच्छति।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = 'कर्मसंज्ञा'
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्यच्'
"प्रसिद्धिः" = '१'
"विधिप्रकारः" = ''
"सूत्रम्" = 'छन्दसि परेच्छायाम् इति वक्तव्यम्।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = 'कर्मसंज्ञा'
"अङ्गम्" = 'सुबन्तम्'
"प्रत्ययः/ विवक्षा" = '''
इच्छा आत्मसम्बद्धा
(न अन्याय)'''
"परिणामः" = 'काम्यच्'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = 'काम्यच्च ।'
"प्रभावोदाहरणम्" = 'पुत्रकाम्यति'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = 'कर्मसंज्ञा'
"अङ्गम्" = 'सुबन्तम्'
"प्रत्ययः/ विवक्षा" = '* इव आचरणे'
"परिणामः" = '''
क्यच्
अकर्मकत्वम्'''
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"सूत्रम्" = '''
उपमानादाचारे ।
'''
"प्रभावोदाहरणम्" = '''
पुत्रम् इवाचरति शिष्यम् = पुत्रीयति
विष्णूयति द्विजम्॥'''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = 'अधिकरणसंज्ञा'
"अङ्गम्" = 'सुबन्तम्'
"प्रत्ययः/ विवक्षा" = '* इव करोति'
"परिणामः" = 'क्यच्'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = 'अधिकरणाच् चेति वक्तव्यम्।'
"प्रभावोदाहरणम्" = 'प्रासादीयति कुट्याम्। पर्यङ्कीयति मञ्चके।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'सुबन्तम्, कर्ता'
"प्रत्ययः/ विवक्षा" = '* इव आचरणे'
"परिणामः" = '''
क्यङ्,
स्-लोपः (पयस्-विहाय),
अकर्मकत्वम्'''
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"सूत्रम्" = '''
(उपमानाद् आचारे॥)
कर्तुः क्यङ् सलोपश्च॥
(ओजसो ऽप्सरसो नित्यं पयसस्तु विभाषया।
{सकारस्येष्यते लोपः})'''
"प्रभावोदाहरणम्" = '''
विशेष इव आचरति = विशेषाय + ते।
'''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'सुबन्तम्, कर्ता'
"प्रत्ययः/ विवक्षा" = '* इव आचरणे'
"परिणामः" = '''
क्विप्
अकर्मकत्वम्'''
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"सूत्रम्" = '''
आचारे ऽवगल्भक्लीबहोडेभ्यः क्विब् वा वक्तव्यः।
सर्वप्रातिपदिकेभ्य इत्येके।
(आचरतेः अकर्मकत्वम्।)'''
"प्रभावोदाहरणम्" = '''
गर्दभायते, गर्दभति।
अवगल्भते (न *ति??), अवगल्भायते। क्लीबते, क्लीबायते। होडते, होडायते।
'''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = 'ओजस् अप्सरस् पयस्'
"अङ्गम्" = 'सुबन्तम्, कर्ता'
"प्रत्ययः/ विवक्षा" = '* इव आचरणे'
"परिणामः" = '''
क्यङ्,
स्-लोपः
अकर्मकत्वम्
'''
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = '''
ओजसो ऽप्सरसो नित्यं पयसस्तु विभाषया।
{सकारस्येष्यते लोपः शब्दशास्त्रविचक्षणैः}
(आचरतेः अकर्मकत्वम्।)'''
"प्रभावोदाहरणम्" = ' ओजायते, अप्सरायते। पयायते, पयस्यते।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = 'भृश। शीघ्र। मन्द। चपल। पण्डित। उत्सुक। उन्मनस्। अभिमनस्। सुमनस्। दुर्मनस्। रहस्। रेहस्। शश्वत्। बृहत्। वेहत्। नृषत्। शुधि। अधर। ओजस्। वर्चस्। भृशादिः।'
"अङ्गम्" = 'सुबन्तम् - च्वि-अन्तम्'
"प्रत्ययः/ विवक्षा" = 'अभूततद्भावे'
"परिणामः" = '''
क्यङ्,
हलो लोपः'''
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = 'भृशादिभ्यो भुव्यच्वेर्लोपश्च हलः ।'
"प्रभावोदाहरणम्" = 'अभृशो भृशो भवति भृशायते। शीघ्रायते।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = '''
व्यक्तशब्दानुकृतिर् अनेकाच् डाजन्तः|
(लोहित। नील। हरित। पीत। मद्र। फेन। मन्द इत्याकृतिगणः)'''
"अङ्गम्" = 'सुबन्तम्, डाच्-अन्तम्।'
"प्रत्ययः/ विवक्षा" = 'भवति इत्यर्थे'
"परिणामः" = 'क्यष्'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"सूत्रम्" = 'लोहितादिडाज्भ्यः क्यष्।'
"प्रभावोदाहरणम्" = 'लोहितायते/ति। पटपटायते।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = '''
लोहित। नील। हरित। पीत। मद्र। फेन। मन्द।
आकृतिगणो ऽयम्।'''
"अङ्गम्" = 'सुबन्तम्'
"प्रत्ययः/ विवक्षा" = 'भवति इत्यर्थे'
"परिणामः" = 'क्यङ्'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = '''
लोहितादिडाज्भ्यः क्यष्।
यानि लोहितादिषु पठ्यन्ते तेभ्यः क्यङेव, अपरिपठितेभ्यस् तु क्यषेव भवति। (??)'''
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'कष्टाय'
"प्रत्ययः/ विवक्षा" = '''
चतुर्थीसमर्थात् क्रमणे ऽर्थे
ऽनार्जवे'''
"परिणामः" = 'क्यङ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'कष्टाय क्रमणे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'स्त्र-कष्ट-कक्ष-कृच्छ्र-गहनेभ्यः '
"प्रत्ययः/ विवक्षा" = 'पापचिकीर्षायाम्'
"परिणामः" = 'क्यङ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'स्त्रकष्टकक्षकृच्छ्रगहनेभ्यः कण्वचिकीर्षायाम् इति वक्तव्यम्।'
"प्रभावोदाहरणम्" = 'स्त्रायते। कष्तायते। कक्षायते। कृच्छ्रायते। गहनायते।'
"अभावोदाहरणम्" = 'कण्वचिकीर्षायाम् इति किम्? अजः कष्टम् क्रामति।'
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'रोमन्थ-तपोभ्यां'
"प्रत्ययः/ विवक्षा" = 'वर्ति-चरोः'
"परिणामः" = 'क्यङ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = '''
कर्मणः रोमन्थतपोभ्यां वर्तिचरोः ।
हनुचलने इति वक्तव्यम्।
तपसः परस्मैपदम् च।'''
"प्रभावोदाहरणम्" = '''
रोमन्थं वर्तयति रोमन्थायते गौः।
तपशचरति तपस्यति।'''
"अभावोदाहरणम्" = 'हनुचलने इति वक्तव्यम्। इह मा भूत्, कीटो रोमन्थं वर्तयति। '
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = '''
बाष्पोष्माभ्यां,
फेनात्'''
"प्रत्ययः/ विवक्षा" = 'उद्वमने'
"परिणामः" = 'क्यङ्'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = '''
बाष्पोष्माभ्यां उद्वमने ।
फेनाच्चेति वक्तव्यम्।'''
"प्रभावोदाहरणम्" = 'बाष्पम् उद्वमति बाष्पायते। ऊष्मायते।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = '''
शब्द वैर कलह अभ्र कन्व मेघ
सुदिन दुर्दिन नीहर'''
"अङ्गम्" = 'सुबन्तम्'
"प्रत्ययः/ विवक्षा" = 'करोत्यर्थे'
"परिणामः" = 'क्यङ्'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = '''
शब्दवैरकलहाभ्रकण्वमेघेभ्यः करणे ।
सुदिनदुर्दिननीहरेभ्यश्चेति वक्तव्यम्।
'''
"प्रभावोदाहरणम्" = 'शब्दायते। वैरायते। कलहायते। अभ्रायते। कण्वायते। मेघायते। '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = 'अटाट्टाशीकाकोटापोटासोटाप्रुष्टाप्लुष्टा'
"अङ्गम्" = 'सुबन्तम्'
"प्रत्ययः/ विवक्षा" = 'करोत्यर्थे'
"परिणामः" = 'क्यङ्'
"प्रसिद्धिः" = '१'
"विधिप्रकारः" = ''
"सूत्रम्" = 'अटाट्टाशीकाकोटापोटासोटाप्रुष्टाप्लुष्टाग्रहणं कर्तव्यम्।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = 'सुख। दुःख। तृप्त। गहन। कृच्छ्र। अस्र। अलीक। प्रतीप। करुण। कृपण। सोढ।'
"अङ्गम्" = '''
सुबन्तम्
कर्म'''
"प्रत्ययः/ विवक्षा" = 'कर्तृवेदनायाम्'
"परिणामः" = 'क्यङ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'सुखादिभ्यः कर्तृवेदनायाम् ।'
"प्रभावोदाहरणम्" = 'सुखं वेदयते सुखायते। दुःखायते।'
"अभावोदाहरणम्" = 'कर्तृग्रहणं किम्? सुखं वेदयते प्रसाधको देवदत्तस्य।'
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = 'नमस् वरिवस् चित्रङित्येतेभ्यो'
"अङ्गम्" = '''
सुबन्तम्
कर्म'''
"प्रत्ययः/ विवक्षा" = 'करोत्यर्थे पूजादौ। '
"परिणामः" = 'क्यच्'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = 'नमोवरिवश्चित्रङः क्यच् ।'
"प्रभावोदाहरणम्" = 'नमसः पूजायाम् नमस्यति देवान्। वरिवसः परिचर्यायाम् वरिवस्यति गुरून्। चित्रङ आश्चर्ये चित्रीयते। ङकार आत्मनेपदार्थः।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = 'पुच्छ भाण्ड चीवर'
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'करोत्यर्थे'
"परिणामः" = 'णिङ्'
"प्रसिद्धिः" = '१'
"विधिप्रकारः" = ''
"सूत्रम्" = 'पुच्छभाण्डचीवराण्णिङ् ।'
"प्रभावोदाहरणम्" = 'पुच्छादुदसने पर्यसने वा। उत्पुच्छयते। परिपुच्छयते। भाण्डात् समाचयने। सम्भान्डयते। चीवरादर्जने परिधाने वा। सञ्चीवरयते भिक्षुः।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = 'ङकार आत्मनेपदार्थः। णकारः सामान्यग्रहणार्थः, णेरनिटि ६।४।५१ इति।'

[[data]]
"अङ्गस्थितिः" = 'मुण्ड मिश्र श्लक्ष्ण लवण व्रत वस्त्र हल कल कृत तूस्त'
"अङ्गम्" = 'सुबन्तम्'
"प्रत्ययः/ विवक्षा" = 'करोत्यर्थे'
"परिणामः" = 'णिच्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'मुण्ड-मिश्र-श्लदणलवण-व्रत-वस्त्र-हल-कल-कृत-तूस्तेभो  णिच्॥'
"प्रभावोदाहरणम्" = 'मुण्डं करोति मुण्डयति। मिश्रयति। श्लक्ष्णयति। लवणयति। व्रतात् भोजने तन्निवृत्तौ च पयो व्रतयति। वृषलान्नं व्रतयति। वस्त्रात् समाच्छादने संवस्त्रयति। हलिं गृह्णाति हलयति। कलिं गृह्णाति कलयति। कृतं गृह्णाति कृतयति। तूस्तानि विहन्ति वितूस्तयति केशान्। विशदीकरोति इत्यर्थः।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = 'हलिकल्योरदन्तत्वनिपातनं सन्वद्भावप्रतिषेधार्यम्। अजहलत्। अचकलत्। '

[[data]]
"अङ्गस्थितिः" = '''
एकाच् हलादिः उपसर्गरहितः
- वकारन्ताः + र्व्-अन्ताः +‌स्रिव् मव् मव्य् (राल्लोपः इत्यनेन वान्ताः)
(प्रागुपयोगानुसारम्)'''
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = '''
पौनःपुन्ये
भृशार्थे'''
"परिणामः" = 'यङ्'
"प्रसिद्धिः" = '४'
"विधिप्रकारः" = ''
"सूत्रम्" = 'धातोरेकाचो हलादेः क्रियासमभिहारे यङ् ।'
"प्रभावोदाहरणम्" = 'नरिनृत्यते बोभूयते।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = 'सूचि-सूत्र-मूत्र्यट्यर्त्यशूर्णोतीनां'
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = '''
पौनःपुन्ये
भृशार्थे'''
"परिणामः" = 'यङ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'सूचिसूत्रमूत्र्यट्यर्त्यशूर्णोतीनां ग्रहनं यङ्विधानवेकाजहलाद्यर्थम्।'
"प्रभावोदाहरणम्" = 'सोसूच्यते। सोसूत्र्यते। मोमूत्र्यते। अटाट्यते। अरार्यते। अशाश्यते। प्रोर्णोनूयते।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = 'गत्यर्थकः'
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'कौटिल्ये गतौ'
"परिणामः" = 'यङ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'नित्यं कौटिल्ये गतौ ।'
"प्रभावोदाहरणम्" = 'कुटिलं क्रामति चङ्क्रम्यते। दन्द्रम्यते।'
"अभावोदाहरणम्" = 'नित्यग्रहणं विषयनियमार्थं, गतिवचनान् नित्यम् कौटिल्य एव भवति, न तु क्रियासमभिहारे। भृशं क्रामति।'
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = '''
लुप-सद-चर
जप-जभ-दह-दश
गॄ'''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'धात्वर्थगर्हायां'
"परिणामः" = 'यङ्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'लुपसदचरजपजभदहदशगॄभ्यो भावगर्हायाम् ।'
"प्रभावोदाहरणम्" = 'जञ्जप्यते। जञ्जभ्यते। दन्दह्यते। दन्दश्यते। निजेगिल्यते।'
"अभावोदाहरणम्" = 'भावगर्हायाम् इति किम्? साधु जपति। भावग्रहणम् किम्? साधनगर्हायां मा भूत्, मन्त्रं जपति वृषलः।'
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = 'सत्याप, पाश, रूप, वीणा, तूल, श्लोक, सेना, लोम, त्वच, वर्म, वर्ण, चूर्ण'
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'कथावचने'
"परिणामः" = 'णिच्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = '''
सत्यापपाशरूपवीणातूलश्लोकसेनालोमत्वचवर्मवर्णचूर्णचुरादिभ्यो णिच् ।
अर्थवेदसत्यानाम् आपुग् वक्तव्यः।'''
"प्रभावोदाहरणम्" = '''
सत्यम् आचष्टे सत्यापयति।
अर्थम् आचष्टे अर्थापयति। देवापयति। '''
"अभावोदाहरणम्" = ' पाशाद् विमोचने विपाशयति। रूपाद् दर्शने रूपयति। वीणयोपगायति उपवीणयति। तूलेनानुकुष्णाति अनुतूलयति। श्लोकैरुपस्तौति उपश्लोकयति। सेनयाभियाति अभिषेणयति। लोमान्यनुमार्ष्टि अनुलोमयति। त्वचं गृह्णाति त्वचयति। अकारान्तस् त्वचशब्दः। वर्मणा सन्नह्यति संवर्मयति। वर्णम् गृह्णाति वर्णयति। चूर्णैः अवध्वंसयति अवचूर्णयति। '
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'चुरादिः'
"प्रत्ययः/ विवक्षा" = 'स्वार्थे'
"परिणामः" = 'णिच्'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"सूत्रम्" = 'सत्यापपाशरूपवीणातूलश्लोकसेनालोमत्वचवर्मवर्णचूर्णचुरादिभ्यो णिच् ।'
"प्रभावोदाहरणम्" = 'चोरयति'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = ' प्रेरणार्थे'
"परिणामः" = 'णिच्'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"सूत्रम्" = 'हेतुमति च।'
"प्रभावोदाहरणम्" = 'भू प्राप्तौ - भावि'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = 'पूर्वप्रयोगानुसारम्'
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तत्करोति इत्यर्थे।'
"परिणामः" = 'णिच्'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"सूत्रम्" = 'तत् करोति इत्युपसङ्ख्यानं सूत्रयति इत्याद्यर्थम्।'
"प्रभावोदाहरणम्" = 'सूत्रं करोति सूत्रयति।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = 'समस्तपदे सुबन्तं +‌कृदन्तम्'
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'कथावचने'
"परिणामः" = '''
णिच्।
प्रकृतिवत् कारकम्।'''
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"सूत्रम्" = 'आख्यानात् कृतस् तदाचष्ट इति णिच् कृल्लुक् प्रकृतिप्रत्यापत्तिः प्रकृतिवच् च कारकम्।'
"प्रभावोदाहरणम्" = ' कंसवधम् आचष्टे कंसं घातयति। बलिबन्धम् आचष्टे बलिं बन्धयति। राजागमनम् आचष्टे राजानम् आगमयति। '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'णिच्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'आङ्लोपश्च कालात्यन्तसंयोगे मर्यादायाम्।'
"प्रभावोदाहरणम्" = 'आरात्रि विवासम् आचश्टे रात्रिं विवासयति। '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनीः" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'णिच्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'चित्रीकरणे प्रापि।'
"प्रभावोदाहरणम्" = ' उज्जयिन्याः प्रस्थितो माहिष्मत्यां सूर्योद्गमनं सम्भावयते सूर्यम् उद्गमयति। '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'णिच्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'नक्षत्रयोगे ज्ञि। '
"प्रभावोदाहरणम्" = 'पुष्ययोगं जानाति पुष्येण योजयति। मघभिर् योजयति।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'कण्ड्वादिः'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'यक्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'कण्ड्वादिभ्यो यक् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'सुबन्तम्'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आय्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'गुपूधूपविच्छिपणिपनिभ्य आयः ।'
"प्रभावोदाहरणम्" = 'बोभवीति।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'सुबन्तम्'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ईयङ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'ऋतेरीयङ् ।'
"प्रभावोदाहरणम्" = 'पुत्रीयति'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'कम्'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'णिङ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'कमेर्णिङ् ।'
"प्रभावोदाहरणम्" = 'कामयते'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'आयादय आर्धद्धातुके वा ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'सनाद्यन्ता धातवः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = ''
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = 'कर्तरि'
"अङ्गम्" = 'वा आधृष-गणात्'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'णिच् वा'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'आधृषाद्वा ???'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = 'कर्तरि'
"अङ्गम्" = 'शिष्टप्रयोगयुक्ताः'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'णिच्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = ''
"प्रभावोदाहरणम्" = 'परिवेशयति इत्यत्र साहसः कृतः शिष्टप्रयोगाभावे'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'सुबन्तम्'
"प्रत्ययः/ विवक्षा" = '''
धात्वर्थ् 
'''
"परिणामः" = 'णिच्, पुंवद्भाव-रभाव-टिलोप-विन्मतुब्लोप-यणादिलोप-प्रस्थ-स्फाद्यादेश-भसंज्ञाः'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"सूत्रम्" = '''
प्रातिपदिकाद्धात्वर्थे बहुलमिष्ठवच्च।
[धातुपाठे चुरादौ गणसूत्रम्।]'''
"प्रभावोदाहरणम्" = """टिलोपः → पटुमाचष्टे पटयति, लघुमाचष्टे लघयति। अपीपटत्., अलीलघत् ।  
पुंवद्भावः - श्येनी → श्येनयति। रभावः - पृथु → प्रथयति।  
यणादिपरम् - स्थूलमाचष्टे - स्थवयति ॥  भारद्वाजमतेन -  
विन् मतोलृक् -  स्रग्विणमाचष्टे = स्रजयति, वसुमन्तंमाचष्टे = वसयति।  
प्रादि - प्रियमाचष्टे — प्रापयति
"""
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = 'आदिवृद्धिः कुतो न?'

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'सुबन्तम्'
"प्रत्ययः/ विवक्षा" = '''
तत्करोति तदाचष्टे। 
'''
"परिणामः" = 'णिच्'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"सूत्रम्" = '''
तत्करोति तदाचष्टे। [धातुपाठे चुरादौ गणसूत्रम्।]'''
"प्रभावोदाहरणम्" = 'शतशाख - शतशाखि - शतशाखयति।  पटुमाचष्टे पटयति लघुमाचष्टे लघयति अपीपटत्., अलीलघत् । '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''


[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'सुबन्तम्'
"प्रत्ययः/ विवक्षा" = '''
तेनातिक्रामति। 
'''
"परिणामः" = 'णिच्'
"प्रसिद्धिः" = '४'
"विधिप्रकारः" = ''
"सूत्रम्" = '''
तेनातिक्रामति। [धातुपाठे चुरादौ गणसूत्रम्।]'''
"प्रभावोदाहरणम्" = 'अश्वेनातिक्रामति अश्वयति । हस्तिनातिक्रामति हस्तयति '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''