[[data]]
"संज्ञा" = 'संवार'
"गणः" = ''
"उपगणः" = 'बाह्यप्रयत्नः'
"गृहितानि/ उदाहरणम्" = 'झश्'
"प्रामुख्यम्" = ''
"विवरणम्" = 'संवारे कण्ठमणिः अवरुद्धः । नाद-घोषकरणे अवरोधः आवश्यकः एव ।  In saMvAra, the larynx is constricted. for creating the hum - called by english phoneticians as "voicing" - उदाहरणायः ग'
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'विवारौ'
"गणः" = ''
"उपगणः" = 'बाह्यप्रयत्नः'
"गृहितानि/ उदाहरणम्" = 'खय्'
"प्रामुख्यम्" = ''
"विवरणम्" = 'विवारे अनावरुद्धः कण्ठमणिः। '
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'नाद'
"गणः" = ''
"उपगणः" = 'बाह्यप्रयत्नः'
"गृहितानि/ उदाहरणम्" = 'झश्'
"प्रामुख्यम्" = ''
"विवरणम्" = 'अभ्यन्तर-स्पर्शादि प्रयत्नात्पूर्वमपि कण्ठमणौ नादः भवति।'
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'श्वास'
"गणः" = ''
"उपगणः" = 'बाह्यप्रयत्नः'
"गृहितानि/ उदाहरणम्" = 'खय्'
"प्रामुख्यम्" = ''
"विवरणम्" = 'नादो न भवति तत्र श्वासः ।'
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'घोष'
"गणः" = ''
"उपगणः" = 'बाह्यप्रयत्नः'
"गृहितानि/ उदाहरणम्" = 'झश्'
"प्रामुख्यम्" = ''
"विवरणम्" = 'अभ्यन्तर-स्पर्शादि प्रयत्नात् परमपि कण्ठमणौ घोषो भवति।'
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'अघोष'
"गणः" = ''
"उपगणः" = 'बाह्यप्रयत्नः'
"गृहितानि/ उदाहरणम्" = 'खय्'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'अल्पप्राण'
"गणः" = ''
"उपगणः" = 'बाह्यप्रयत्नः'
"गृहितानि/ उदाहरणम्" = 'क् ग् ङ् च् ज् ञ् ...'
"प्रामुख्यम्" = ''
"विवरणम्" = ' यत्र अल्पा सा संवेदना, स प्रयत्नः अल्पप्राणः ।'
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'महाप्राणः'
"गणः" = ''
"उपगणः" = 'बाह्यप्रयत्नः'
"गृहितानि/ उदाहरणम्" = 'ख् घ् छ् झ् ...'
"प्रामुख्यम्" = ''
"विवरणम्" = 'यदा वायुः जठरात् महाप्रयत्नेन उद्गच्छति इति संवेदना स प्रयत्नः महाप्राणः'
"सूत्रम्" = ''
"उदाहरणम्" = ''

