[[data]]
"संज्ञा" = 'लौकिकसंज्ञा'
"गणः" = ''
"उपगणः" = 'संज्ञा'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = 'सुप्-तिङन्तम् पदम्'

[[data]]
"संज्ञा" = 'अलौकिकसंज्ञा'
"गणः" = ''
"उपगणः" = 'संज्ञा'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = 'स्वादिषु असर्वनामस्थाने॥'

[[data]]
"संज्ञा" = 'सूत्रम्'
"गणः" = 'प्रमाणम्'
"उपगणः" = 'सूत्रम्'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'परिभाषा'
"गणः" = 'प्रमाणम्'
"उपगणः" = 'सूत्रम्'
"गृहितानि/ उदाहरणम्" = '''उदाहरणाय 'शष्टि-विभ्क्त्यां प्रयुक्ते स्थाने इत्यर्थः' इत्येतत् 'इकः यण् अचि' अवगन्तुं आवश्यकं।'''
"विवरणम्" = '१३३ प्रख्याताः परिभाषाः पाणिनेः पूर्वमेव विरचिताः, तेन स्वीकृताः च। '
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'अधिकार'
"गणः" = 'प्रमाणम्'
"उपगणः" = 'सूत्रम्'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = '''क्रमानुसारं केषुचित् सूत्रेषु  अनुवृत्त्यां कश्चन पदं संयोक्तव्यं इति वदन्ति, उदाहरणाय '२.१.१ - प्रत्ययः'।'''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'संज्ञा'
"गणः" = 'प्रमाणम्'
"उपगणः" = 'सूत्रम्'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = " 'definitions'"
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'विधिः'
"गणः" = 'प्रमाणम्'
"उपगणः" = 'सूत्रम्'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = '''
(generation rules)  सर्व-मुख्य-सूत्राणि।
आदेशः (replacement) च आगमः (addition/ insertion) च लोपः'''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'नियम'
"गणः" = 'प्रमाणम्'
"उपगणः" = 'सूत्रम्'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = '''
विधिसूत्राणाम् प्रयोगस्य योग्यता-वचनम्।
कार्यक्षेत्र-सङ्कोचनम्।'''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'अधिकारः'
"गणः" = 'प्रमाणम्'
"उपगणः" = 'सूत्रम्'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = 'सूत्रमहासङ्ग्रहः'
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'परसूत्रम्'
"गणः" = 'प्रमाणम्'
"उपगणः" = 'सूत्रम्'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = 'द्वयोस् सूत्रयोः परतमम्।'
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'उत्सर्गः'
"गणः" = 'प्रमाणम्'
"उपगणः" = 'सूत्रम्'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = 'आधारोऽधिकरणम्।'

[[data]]
"संज्ञा" = 'अपवादः'
"गणः" = 'प्रमाणम्'
"उपगणः" = 'सूत्रम्'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = '[आधारोऽधिकरणम्।] अधिशीङ्स्थासां कर्म।'

[[data]]
"संज्ञा" = 'वार्त्तिकम्'
"गणः" = 'प्रमाणम्'
"उपगणः" = 'वार्त्तिकम्'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'उपसङ्ख्यानम्'
"गणः" = 'प्रमाणम्'
"उपगणः" = 'वार्त्तिकम्'
"गृहितानि/ उदाहरणम्" = 'कस्यचित् सूत्रस्य व्याप्तेः प्रसारणम्।'
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'प्रयोगबलम्'
"गणः" = 'प्रमाणम्'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'महाभाष्यादौ प्रयोगः।'
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'परिभाषा'
"गणः" = 'प्रमाणम्'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = '''
पातञ्जला इमे इति केचित्। तत्पूर्वा इति अन्ये।
परिभाषासूत्राणीव।'''
"सूत्रम्" = ''
"उदाहरणम्" = '''
प्रातिपदिकग्रहणे लिङ्गविशिष्टस्यापि ग्रहणम्।
कृग्रहणे गतिकारकपूर्वस्यापि ग्रहणम्।'''

[[data]]
"संज्ञा" = 'योगविभागः'
"गणः" = 'प्रमाणम्'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = '''
सूत्रस्य छेदः प्रयोगसमर्थनार्थम् अनन्यगतिकतया।
'''
"सूत्रम्" = ''
"उदाहरणम्" = '''
"पर्वतो वह्निमान् धूमात्।" इति समर्थितुम् "विभाषा गुणेऽस्त्रियाम्" इति सूत्रस्य स्थाने "विभाषा गुणे। अस्त्रियाम्।"।
'''

[[data]]
"संज्ञा" = 'प्रकरणम्'
"गणः" = ''
"उपगणः" = 'सूत्रसङ्ग्रहः'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'उणादिसूत्राणि'
"गणः" = ''
"उपगणः" = 'सूत्रसङ्ग्रहः'
"गृहितानि/ उदाहरणम्" = ' सीमितप्रभाव-प्रत्ययविधेयकानि।'
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'प्रक्रिया-पाठः'
"गणः" = ''
"उपगणः" = 'सूत्रसङ्ग्रहः'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = 'लघुसिद्धान्तकौमुद्यादिषु प्रकरणम्।'
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'उपदेशाः'
"गणः" = ''
"उपगणः" = 'सूत्रभाषा'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = 'प्रयोजनम्॥ वृत्तिसमवायार्थ उपदेशः।'
"सूत्रम्" = '''
प्रत्ययाः शिवसूत्राणि आदेशा आगमास्तथा।
धातुपाठो गणपाठ उपदेशाः प्रकीर्तिताः॥
उपदेश आद्युच्चारणम्।
'''
"उदाहरणम्" = 'डुकृङ् ( न कृ)।'

[[data]]
"संज्ञा" = 'बहुलम्'
"गणः" = ''
"उपगणः" = 'सूत्रभाषा'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = 'क्वचित् (अनिर्दिष्टेऽपि) प्रवृत्तिः, क्वचित् (निर्दिष्टेऽपि) अप्रवृत्तिः, क्वचिद् अन्यत् एव।'
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'विभाषा'
"गणः" = ''
"उपगणः" = 'सूत्रभाषा'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'अतिदेश'
"गणः" = 'विधिः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''' 'अन्य-शब्द-परिवर्तन-वत् अत्रापि भवति' इति वदन्ति।'''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'अन्तरङ्गकार्यं/ बहिरङ्गकार्यम्'
"गणः" = 'विधिः'
"उपगणः" = 'प्रक्रिया'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = '''
एकाय कार्याय अमुकनिमित्तमपेक्षितम् चेत्, अपराय इतोऽपि एकमपेक्षितं चेत् प्रथमं अन्तरङ्गम्।

'''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'निषेधः'
"गणः" = 'विधिः'
"उपगणः" = 'अपवादः'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'प्रतिप्रसवः'
"गणः" = 'विधिः'
"उपगणः" = 'अपवादः'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = 'निषेधे ऽपवादः'
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'सूत्रबलम्'
"गणः" = ''
"उपगणः" = 'प्रयोग-क्रमः'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = '''
विशेषसूत्रं बलवत्तरम्।
प्रतिपदोक्तसूत्रम् बलवत्तरम्।
यदि क्रमानुसरणेन पाणिनेः काचित् संज्ञा व्यर्था भवति, तर्हि क्रमः चिन्तनीयः।'''
"सूत्रम्" = '''
पर-नित्य-अन्तरङ्ग-अपवादानां उत्तरोत्तरबलीयः ॥
अङ्गकार्यम् वर्णकार्यात् बलवत्तरम्।

'''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'प्रयोग-क्रमः'
"गणः" = ''
"उपगणः" = 'प्रयोग-क्रमः'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = '''
तुल्यबलविरोधे १-८.१* - परसूत्रप्रभावो प्रथमः।
अन्यथा प्रथमसूत्रप्रभावः प्रथमः।'''
"सूत्रम्" = 'तुल्यबलविरोधे विप्रतिशेधे परम् कार्यम्॥'
"उदाहरणम्" = 'द्विष् + धि (झलां जश् झषि, ष्टुनाः ष्टुः इत्येतयोः प्रसक्तिरस्ति युगपत्)'

[[data]]
"संज्ञा" = 'सूत्रासिद्धिः'
"गणः" = 'असिद्धम्'
"उपगणः" = 'प्रयोग-क्रमः'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = '''
१-८.१* च ८.२-८.४ इत्यस्य प्रसक्तिरस्ति चेत्, पूर्वसूत्रस्य प्रभावः प्रथमम्।
(पूर्वसूत्रस्य दृष्ट्या परसूत्रं नास्ति।)
८.२-८.४ - पूर्वसूत्रप्रभावो प्रथमः।
(पूर्वसूत्रस्य दृष्ट्या परसूत्रं नास्ति।)'''
"सूत्रम्" = 'पूर्वत्रासिद्धम्॥ ८.२.१। शास्त्रासिद्धम् इति।'
"उदाहरणम्" = '''
रामस् + इति → राम इति अन्तिमपादस्य प्रभावेण।
राम इति → रामेति इति न भवति ।
(आद्गुणः इति ६-अध्यायस्य सूत्रस्य दृष्ट्या न तत्र ८-अध्याय-सूत्राणां कार्यसिद्धिः।)'''

[[data]]
"संज्ञा" = 'कार्यासिद्धिः'
"गणः" = 'असिद्धम्'
"उपगणः" = 'प्रयोग-क्रमः'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = 'परसूत्रस्य दृष्ट्या पूर्वतनसूत्रस्य कार्यं न जातम्।'
"सूत्रम्" = 'पूर्वत्रासिद्धम्। ८.२.१।'
"उदाहरणम्" = '''

नश्चापदान्तस्य झलि । (८.३.२४)
रषाभ्यां नो णः समानपदे। (८.४.१)
अनुस्वारस्य ययि परसवर्णः । (८.४.५८)
एतेषां प्रसक्तिर् अस्ति कृंत् → कृन्त् इत्यत्र।
परन्तु (८.४.१) इत्येतस्य दृष्ट्या कृंत् इत्येव रूपम्।'''

[[data]]
"संज्ञा" = 'प्रयोग-निवर्तनम्'
"गणः" = ''
"उपगणः" = 'प्रयोग-क्रमः'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = '''
पाप्रच्छ्‌* + हि → हुझल्भ्यो हेर्धिः → पाप्रच्छ्‌ + धि  → पाप्रष्‌* + धि
[न पाप्रच्ष् इति - च्कारस्य निमित्तमासीत् छकारः।]  '''

[[data]]
"संज्ञा" = 'अन्य्ऽन्य-आश्रयः'
"गणः" = ''
"उपगणः" = 'दोषः'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = 'संज्ञासूत्रेषु अन्योऽन्यः आश्रयः'
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'अनुवृत्तिः'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = '''
पदग्रहणम् पाणिनीयक्रमे पूर्वतनेभ्यः समीपस्थेभ्यः स्वीक्रीयन्ते ।
'अर्ध-मात्रा-लाघवेन पुत्रोत्सवं मन्यन्ते वय्याकरणाः'।
यथा साधारणसंभाषणे पूर्ववाक्यानि विना नावगन्तुम् शक्यते चितवाक्यस्य आशयः।'''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'मण्डूकप्लुतिः'
"गणः" = ''
"उपगणः" = 'अनुवृत्तिः'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = 'अनन्यगतिकया क्रियते क्वचित्।'
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'प्रकृतिः / अङ्गम्'
"गणः" = ''
"उपगणः" = 'उत्पादनम्'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = 'प्रत्ययेन योग्यः शब्दः'
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'व्युत्पत्तिः प्रक्रिया'
"गणः" = ''
"उपगणः" = 'उत्पादनम्'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = 'एक-शब्दात् अन्यस्य शब्दस्य उत्पत्तेः नाम व्युत्पत्तिः।'
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'निपातनम्'
"गणः" = ''
"उपगणः" = 'उत्पादनम्'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = '''
प्रक्रियातीतता। प्रक्रियां विना शब्दसिद्धिः।
अनिर्दिष्टे स्थाने सूत्रप्रयोगेन शब्दसिद्धिः वा।'''
"सूत्रम्" = ''
"उदाहरणम्" = 'तिष्ठद्गु प्रभृतीनि च अव्ययीभावः इति पाणिनिः। क्वचित् प्रयोगबलात् पदस्वीकृतिः।'

[[data]]
"संज्ञा" = 'आकृति-गणः'
"गणः" = ''
"उपगणः" = 'सङ्ग्रहः'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = '''
असंपूर्णतां दृष्ट्वा आधुनिकाः वर्धनम् कुर्युः।
गणपाठे, गणस्य अन्ते लिखितं भवति-- अयम्‌ आकृतिगणः।'''
"सूत्रम्" = ''
"उदाहरणम्" = 'शाकन्ध्वादि-गणः। शाकपार्थिवादि-गणः।'

[[data]]
"संज्ञा" = 'परिगणित-गणः'
"गणः" = ''
"उपगणः" = 'सङ्ग्रहः'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = 'सर्व-आदि-गणः'

[[data]]
"संज्ञा" = 'गणपाठः'
"गणः" = ''
"उपगणः" = 'सङ्ग्रहः'
"गृहितानि/ उदाहरणम्" = '''
विविधप्रातिपदिकगणानाम्। (उपसर्गा अपि।)
'''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'धातुपाठः'
"गणः" = ''
"उपगणः" = 'सङ्ग्रहः'
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'विभक्तिः'
"गणः" = ''
"उपगणः" = 'प्रत्ययः'
"गृहितानि/ उदाहरणम्" = 'तिङ् सुप्'
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'सर्वनामस्थानम्'
"गणः" = 'विभक्तिः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'शि सर्वनामस्थानम् ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'सर्वनामस्थानम्'
"गणः" = 'विभक्तिः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'सुडनपुंसकस्य ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'पद-वृत्तिः'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'कृत्‌ (उणादिसूत्रविहिताः अत्र अन्तर्भूताः) तद्धित समास एकशेष सनाद्यन्त'
"विवरणम्" = '''

शब्दस्य विग्रहः यया भवति, सा वृत्तिः।
असापेक्षावयवाः स्युः, तेषु एकार्थीभावसामर्थ्यम् स्यात्।
अर्थबोधे वृत्तिर् अन्या!
सामर्थ्य-विवरणम् अत्र - https://is.gd/hAkfOp'''
"सूत्रम्" = '''
विशिष्ट-एकार्थप्रतिपादिका वृत्तिः।
"समर्थः पदविधिः।
""सविशेषणानां वृत्तिर् न। वृत्तस्य वा विशेषणयोगो न॥"" इति भाष्ये।"'''
"उदाहरणम्" = '''
"सुन्दर्याः सीतायाः‌पतिः" != "सुन्दर्याः सीतापतिः।"
"गच्छ ग्रामम्। रामो गतः।" = ग्रामगतः इति न।"'''

[[data]]
"संज्ञा" = 'पद-वृत्तिः'
"गणः" = 'असापेक्षा'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = '''

'''
"विवरणम्" = '''
वृत्तिषु  एकार्थीभाव-सामर्थ्यम्।
तेन नूतनार्थः सृष्टः।
तेन विशेषणं न एकेन उपपदेन अन्वेति।
वाक्यार्थ-विपरिणामो न स्यात्।'''
"सूत्रम्" = ''
"उदाहरणम्" = '''
समर्थः पदविधिः।
"सविशेषणानां वृत्तिर् न। वृत्तस्य वा विशेषणयोगो न॥" इति भाष्ये।'''

[[data]]
"संज्ञा" = 'पद-वृत्तिः'
"गणः" = 'सापेक्षा'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = '''
"उपसर्जनस्य नित्यसापेक्षत्वम् |
अवयव-संस्पर्शेन समुदायेन सम्बन्धः।"
इत्यनेन गमकत्वम् (=अर्थावबोधे न बाधा)'''
"विवरणम्" = ''
"सूत्रम्" = '''
"देवदत्तस्य गुरुकुल"मित्यत्र तु उपसर्जनस्य नित्यसापेक्षत्वात्समासः।
यद्वा गुरुवद्देवदत्तोऽपि विशेष्ये प्रदाने कुल एवान्वेति। तत्र गुरुणा कुलस्य उत्पाद्यत्वसंबन्धेनान्वयः। देवदत्तेन तु कुलस्य तदीयगुरूत्पाद्यतयाऽन्वयो गुरुगर्भः। '''
"उदाहरणम्" = '''
समर्थः पदविधिः। (अपवादाः)
उक्तं च हरिणा-"संबन्धिशब्दः सापेक्षो नित्यं सर्वः समस्यते। वाक्यवत्सा व्यपेक्षा हि वृत्तावपि न हीयते।" इति।
समुदायेन संबन्धो येषां गुरुकलादिना। संस्पृश्यावयवांस्ते तु युज्यन्ते तद्वता सह।" इति च।'''

[[data]]
"संज्ञा" = 'पद-वृत्तिः'
"गणः" = 'सापेक्षा'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'सामर्थ्याभावे गमकत्वम् (=अर्थावबोधे न बाधा)'
"विवरणम्" = ''
"सूत्रम्" = '''
अपुनर् गेयाः श्लोकाः।
असूर्यं पश्याः राजधाराः।
शास्त्रेऽपि - sudanapumsakasya (anapumsakasya =napumsakasya na bhavati).
"sphutopamam bhUtisitena sambhuna" इति माघः। (sphutasambhUpamam ityarthah)'''
"उदाहरणम्" = '''
समर्थः पदविधिः। (अपवादाः)
‘सापेक्षत्वेऽपि गमकत्वात् समासः’’'''
