[[data]]
"अङ्गम्" = 'अनिट् धातुः'
"प्रत्ययः/ विवक्षा" = '''
लुङ् → सिच्
परस्मैपदे'''
"परिणामः" = '''
सीत् स्ताम् सुः।
सीः स्तम् स्त।
सम् स्व स्म।'''
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = 'प्रत्ययसिद्धिः'
"सूत्रम्" = 'अन्यत्र विवृतम्'
"प्रभावोदाहरणम्" = 'अस्तिसिचोः अपृक्ते सार्वधातुके हलि ईट्॥'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'सेट् धातुः'
"प्रत्ययः/ विवक्षा" = '''
लुङ् → सिच्
परस्मैपदे'''
"परिणामः" = '''
ईत् इष्टाम् इषुः।
ईः इष्टम् इष्ट।
इषम् इष्व इष्म।'''
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = 'प्रत्ययसिद्धिः'
"सूत्रम्" = 'अन्यत्र विवृतम्'
"प्रभावोदाहरणम्" = '''
अस्तिसिचोः अपृक्ते सार्वधातुके हलि ईट्॥
इट ईटि सस्य लोपः।
ईत् इष्टाम् इषुः
'''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = ''
"प्रभावोदाहरणम्" = 'अन्यसूत्राणि'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = '''
यम रम नम
आत्'''
"प्रत्ययः/ विवक्षा" = '''
लुङ् → सिच्
परस्मैपदे'''
"परिणामः" = 'सक् + सेट्-वत्-प्रत्ययाः'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = 'प्रत्ययसिद्धिः'
"सूत्रम्" = 'अन्यत्र विवृतम्'
"प्रभावोदाहरणम्" = 'यमरमनमातां सक् च ।'
"अभावोदाहरणम्" = 'अज्ञासिषम्'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'लुङ्'
"परिणामः" = 'सिच्'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = 'आगमः'
"प्रभावोदाहरणम्" = '''
च्लि लुङि ।
च्लेः सिच् ।'''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = '''
शल्-अन्ताः इगुपधा 
अनिट् - दृश्।
श्लिष् आलिङ्गने।'''
"प्रत्ययः/ विवक्षा" = 'लुङ्'
"परिणामः" = 'क्स'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = 'आगमः'
"प्रभावोदाहरणम्" = '''
च्लि लुङि ।
शल इगुपधादनिटः क्सः ।
श्लिष आलिङ्गने ।
न दृशः ।'''
"अभावोदाहरणम्" = 'अ+ कृष् + सत् → अकृक्षत्'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = '''
णिजन्ताः|
श्रि-द्रु-स्रुभ्यः'''
"प्रत्ययः/ विवक्षा" = 'लुङ्'
"परिणामः" = 'कर्तरि चङ्'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = 'आगमः'
"प्रभावोदाहरणम्" = 'णिश्रिद्रुस्रुभ्यः कर्तरि चङ् ।'
"अभावोदाहरणम्" = 'अ + द्रु + चङ् + त् → अदुद्रुवत्'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'धेट् श्वि गुप्'
"प्रत्ययः/ विवक्षा" = 'लुङ्'
"परिणामः" = 'कर्तरि चङ्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = 'आगमः विकल्पेन'
"प्रभावोदाहरणम्" = '''
विभाषा धेट्श्व्योः ।
गुपेश्छन्दसि ।'''
"अभावोदाहरणम्" = '''
अ+  श्वि + चङ् + त् → अशिश्वयत्
अ+ श्वि + इट् + सिच् + त् → 
अश्वि + ईत् → अश्वयीत्'''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = '''
णिजन्तम्
- ऊनयति-ध्वनयति-एलयति-अर्दयति 
छन्दसि'''
"प्रत्ययः/ विवक्षा" = 'लुङ्'
"परिणामः" = 'कर्तरि चङ्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = 'आगमः'
"प्रभावोदाहरणम्" = 'न ऊनयति-ध्वनयत्येलयत्यर्दयतिभ्यः छन्दसि'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'अस्यति-वक्ति-ख्याति'
"प्रत्ययः/ विवक्षा" = 'लुङ्'
"परिणामः" = 'अङ्'
"प्रासिद्ध्यम्" = '४'
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = 'आगमः'
"प्रभावोदाहरणम्" = 'अस्यतिवक्तिख्यातिभ्यः अङ् ।'
"अभावोदाहरणम्" = '''
आस्थत् (अस्यतेस् थुक्)
अवोचत् (वुम् आगमः)।
अख्यत् (आतो लोपः इटि च किति ङिति)'''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'लिपि-सिचि-ह्व'
"प्रत्ययः/ विवक्षा" = 'लुङ्'
"परिणामः" = 'अङ्'
"प्रासिद्ध्यम्" = '३'
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = 'आगमः'
"प्रभावोदाहरणम्" = 'लिपिसिचिह्वश्च ।'
"अभावोदाहरणम्" = '''
अलिपत् असिचत् 
अह्वे → अह्वा (आतो लोपः)→ अह्वत्'''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'लिपि-सिचि-ह्व आत्मनेपदेषु'
"प्रत्ययः/ विवक्षा" = 'लुङ्'
"परिणामः" = 'अङ्'
"प्रासिद्ध्यम्" = '२'
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = 'आगमः विकल्पेन'
"प्रभावोदाहरणम्" = 'आत्मनेपदेष्वन्यतरस्याम् ।'
"अभावोदाहरणम्" = 'अलिपत / अलिप्त (सिच्)'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = '''
पुषादि-द्युतादि
ऌदितः 
परस्मैपदेषु'''
"प्रत्ययः/ विवक्षा" = 'लुङ्'
"परिणामः" = 'अङ्'
"प्रासिद्ध्यम्" = '४'
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = 'आगमः'
"प्रभावोदाहरणम्" = 'पुषादिद्युताद्यॢदितः परस्मैपदेषु ।'
"अभावोदाहरणम्" = 'अपुषत्'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'सृ शास् ऋ'
"प्रत्ययः/ विवक्षा" = 'लुङ्'
"परिणामः" = 'अङ्'
"प्रासिद्ध्यम्" = '२'
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = 'आगमः'
"प्रभावोदाहरणम्" = 'सर्त्तिशास्त्यर्तिभ्यश्च ।'
"अभावोदाहरणम्" = '''
असरत् (ऋदृशः अङि गुणः)
अशिसत् (शास इद् अङ्-हलोः)
ऋ'''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'इर्-इत्-वान् १४ धातवः'
"प्रत्ययः/ विवक्षा" = 'लुङ्'
"परिणामः" = 'अङ्'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = 'आगमः विकल्पेन'
"प्रभावोदाहरणम्" = 'इरितो वा ।'
"अभावोदाहरणम्" = 'भिधिर् → अभिधत् | अभैत्सीत्'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = '''
जॄ-स्तम्भु-म्रुचु-म्लुचु
-ग्रुचु-ग्लुचु-ग्लुञ्चु-
श्विभ्यश्च'''
"प्रत्ययः/ विवक्षा" = 'लुङ्'
"परिणामः" = 'अङ्'
"प्रासिद्ध्यम्" = '२'
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = 'आगमः विकल्पेन'
"प्रभावोदाहरणम्" = 'जॄ-स्तन्भु-म्रुचु-म्लुचु-ग्रुचु-ग्लुचु-ग्लुञ्चु-श्विभ्यश्च ।'
"अभावोदाहरणम्" = 'अजरत् अस्तभत् (अन् इदिताम् …)'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'कृ-मृदृरुहिभ्यश्छन्दसि ।'
"प्रत्ययः/ विवक्षा" = 'लुङ्'
"परिणामः" = 'अङ्'
"प्रासिद्ध्यम्" = '१'
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = ''
"प्रभावोदाहरणम्" = 'कृमृदृरुहिभ्यश्छन्दसि ।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'पद्'
"प्रत्ययः/ विवक्षा" = 'लुङ् आ प्र १ → त'
"परिणामः" = 'चिण्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = 'आदेशः विकल्पेन'
"प्रभावोदाहरणम्" = '''
चिण् ते पदः ।
(चिणो लुक् ।)'''
"अभावोदाहरणम्" = 'अपादि (त-लोपः - चिणो लुक्।)'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = '''
दीप-जन-बुध-पूरि
तायि-प्यायिभ्यो'''
"प्रत्ययः/ विवक्षा" = 'लुङ् आ प्र १ → त'
"परिणामः" = 'चिण्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = 'आदेशः विकल्पेन'
"प्रभावोदाहरणम्" = 'दीपजनबुधपूरितायिप्यायिभ्योऽन्यतरस्याम् ।'
"अभावोदाहरणम्" = 'अदीपि / अदीपिष्ट'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'अच्-अन्तः'
"प्रत्ययः/ विवक्षा" = 'लुङ् आ प्र १ → त'
"परिणामः" = 'चिण्'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = 'आदेशः विकल्पेन'
"प्रभावोदाहरणम्" = 'अचः कर्मकर्तरि ।'
"अभावोदाहरणम्" = 'अकारि कटः स्वयमेव (बनगयि कट् [विना श्रम])।'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'दुह्'
"प्रत्ययः/ विवक्षा" = '''
लुङ् आ प्र १ → त
कर्मकर्तरि'''
"परिणामः" = 'चिण्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = 'आदेशः विकल्पेन'
"प्रभावोदाहरणम्" = 'दुहश्च ।'
"अभावोदाहरणम्" = 'अदोहि गौः स्वयमेव'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'रुधिर् आवरणे'
"प्रत्ययः/ विवक्षा" = '''
लुङ् आ प्र १ → त
कर्मकर्तरि'''
"परिणामः" = '- चिण्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = 'निषेधः'
"प्रभावोदाहरणम्" = 'न रुधः ।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = 'अन्वावारोधि गौः गोपालकेन'

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = '''
लुङ् आ प्र १ → त
कर्मकर्तरि'''
"परिणामः" = '- चिण्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = 'निषेधः'
"प्रभावोदाहरणम्" = 'तपोऽनुतापे च ।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = '''
लुङ् आ प्र १ → त
कर्मकर्तरि'''
"परिणामः" = 'चिण्'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = ''
"प्रभावोदाहरणम्" = 'चिण् भावकर्मणोः ।'
"अभावोदाहरणम्" = '''
अशायि भवता।
अकारि कटो रामेण।'''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = '''
गा-स्था-गुप्-भू
परस्मैपदे'''
"प्रत्ययः/ विवक्षा" = 'लुङ्'
"परिणामः" = 'सिच् → लुक्'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = 'आदेशः'
"प्रभावोदाहरणम्" = 'गातिस्थागुपाभूभ्यः सिचः परस्मैपदेषु'
"अभावोदाहरणम्" = 'गा  अगात् अभूत्'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = '''
घ्रा-धेट् शा
छा सा '''
"प्रत्ययः/ विवक्षा" = 'लुङ्'
"परिणामः" = 'सिच् → लुक्'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = 'आदेशः वा'
"प्रभावोदाहरणम्" = 'विभाषा घ्राधेट्शाच्छासः सिचः परस्मैपदेषु'
"अभावोदाहरणम्" = 'घ्रा अघ्रात्'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = '''
तनादिः आत्मनेपदम्
'''
"प्रत्ययः/ विवक्षा" = 'लुङ् → त थास्'
"परिणामः" = 'सिच् → लुक्'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = 'विकरणम्'
"सूत्रम्" = 'आदेशः विकल्पेन'
"प्रभावोदाहरणम्" = 'तनादिभ्यः तथासोः सिचः विभाषा'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'क्स'
"परिणामः" = 'अच्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लुङि प्रत्ययसिद्धिः'
"सूत्रम्" = 'आदेशः'
"प्रभावोदाहरणम्" = 'क्सस्याचि  (अतो लोपः)।'
"अभावोदाहरणम्" = 'अदुह् + आताम् → अदुहाताम् (अतो लोपः नास्ति चेद् प्रत्ययः इताम् अभविष्यत्)'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = '''
दुह-दिह-लिह-गुह 
आमात्मनेपदे'''
"प्रत्ययः/ विवक्षा" = 'क्स'
"परिणामः" = 'दन्त्ये = त | थास् | ध्वम् | व'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लुङि प्रत्ययसिद्धिः'
"सूत्रम्" = 'आदेशः विकल्पेन'
"प्रभावोदाहरणम्" = 'लुग्वा दुहदिहलिहगुहामात्मनेपदे ।'
"अभावोदाहरणम्" = 'अदुग्ध /अधुक्षत'
"अन्यटिप्पनी" = ''
