[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'र्/द्'
"प्रत्ययः/ विवक्षा" = 'क्त क्तवतु'
"परिणामः" = 'द+*'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'निष्ठा-तकारादेशः'
"विधिः" = ''
"सूत्रम्" = 'रदाभ्यां निष्ठातो नः पूर्वस्य च दः ।'
"प्रभावोदाहरणम्" = 'शॄ → शीर्ण (ॠदित् धातोः। हलि च)'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = '''
संयोगादिः यण्-वान्
आत्'''
"प्रत्ययः/ विवक्षा" = 'क्त क्तवतु'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'निष्ठा-तकारादेशः'
"विधिः" = ''
"सूत्रम्" = 'संयोगादेरातो धातोर्यण्वतः ।'
"प्रभावोदाहरणम्" = 'ग्ला → ग्लान'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = '''
लू-आदिः (~३० धातवः)
'''
"प्रत्ययः/ विवक्षा" = 'क्त क्तवतु'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'निष्ठा-तकारादेशः'
"विधिः" = ''
"सूत्रम्" = 'ल्वादिभ्यः ।'
"प्रभावोदाहरणम्" = 'लूनः धूनः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'क्त क्तवतु'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'निष्ठा-तकारादेशः'
"विधिः" = ''
"सूत्रम्" = 'ओदितश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'क्त क्तवतु'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'निष्ठा-तकारादेशः'
"विधिः" = ''
"सूत्रम्" = 'क्षियो दीर्घात्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'क्त क्तवतु'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'निष्ठा-तकारादेशः'
"विधिः" = ''
"सूत्रम्" = 'श्योऽस्पर्शे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'क्त क्तवतु'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'निष्ठा-तकारादेशः'
"विधिः" = ''
"सूत्रम्" = 'अञ्चोऽनपादाने ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'क्त क्तवतु'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'निष्ठा-तकारादेशः'
"विधिः" = ''
"सूत्रम्" = 'दिवोऽविजिगीषायाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'क्त क्तवतु'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'निष्ठा-तकारादेशः'
"विधिः" = ''
"सूत्रम्" = 'निर्वाणोऽवाते ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'क्त क्तवतु'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'निष्ठा-तकारादेशः'
"विधिः" = ''
"सूत्रम्" = 'शुषः कः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'क्त क्तवतु'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'निष्ठा-तकारादेशः'
"विधिः" = ''
"सूत्रम्" = 'पचो वः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'क्त क्तवतु'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'निष्ठा-तकारादेशः'
"विधिः" = ''
"सूत्रम्" = 'क्षायो मः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'क्त क्तवतु'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'निष्ठा-तकारादेशः'
"विधिः" = ''
"सूत्रम्" = 'प्रस्त्योऽन्यतरस्याम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'क्त क्तवतु'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'निष्ठा-तकारादेशः'
"विधिः" = ''
"सूत्रम्" = 'अनुपसर्गात्‌ फुल्लक्षीबकृशोल्लाघाः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'क्त क्तवतु'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'निष्ठा-तकारादेशः'
"विधिः" = ''
"सूत्रम्" = 'नुदविदोन्दत्राघ्राह्रीभ्योऽन्यतरस्याम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'क्त क्तवतु'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'निष्ठा-तकारादेशः'
"विधिः" = ''
"सूत्रम्" = 'न ध्याख्यापॄमूर्छिमदाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'क्त क्तवतु'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'निष्ठा-तकारादेशः'
"विधिः" = ''
"सूत्रम्" = 'वित्तो भोगप्रत्यययोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'क्त क्तवतु'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'निष्ठा-तकारादेशः'
"विधिः" = ''
"सूत्रम्" = 'भित्तं शकलम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'क्त क्तवतु'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'निष्ठा-तकारादेशः'
"विधिः" = ''
"सूत्रम्" = 'ऋणमाधमर्ण्ये ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'क्त क्तवतु'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'निष्ठा-तकारादेशः'
"विधिः" = ''
"सूत्रम्" = 'नसत्तनिषत्तानुत्तप्रतूर्तसूर्तगूर्तानि छन्दसि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'वेर् अपृक्तस्य (लोपः)'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'हु/ झलन्तम्'
"प्रत्ययः/ विवक्षा" = 'लोट् म १'
"परिणामः" = 'धि'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लँस्य प्रत्ययादेशः'
"विधिः" = ''
"सूत्रम्" = '''
हुझल्भ्यो हेर्धिः ।
'''
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लँस्य प्रत्ययादेशः'
"विधिः" = ''
"सूत्रम्" = 'श्रुशृणुपॄकृवृभ्यश्छन्दसि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लँस्य प्रत्ययादेशः'
"विधिः" = ''
"सूत्रम्" = 'अङितश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'चिण्'
"प्रत्ययः/ विवक्षा" = 'लट् प्र १'
"परिणामः" = 'लुक्'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = 'लँस्य प्रत्ययादेशः'
"विधिः" = ''
"सूत्रम्" = '''
चिणो लुक् ।
[तप्रत्यये परे]'''
"प्रभावोदाहरणम्" = 'अगामि अवादि'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'अदन्तम् '
"प्रत्ययः/ विवक्षा" = 'लोट् म १'
"परिणामः" = 'लुक्'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = 'लँस्य प्रत्ययादेशः'
"विधिः" = ''
"सूत्रम्" = 'अतो हेः ।'
"प्रभावोदाहरणम्" = 'गच्छ'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'लोट् म १'
"परिणामः" = 'लुक्'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = 'लँस्य प्रत्ययादेशः'
"विधिः" = ''
"सूत्रम्" = 'उतश्च प्रत्ययादसंयोगपूर्वात्‌ ।'
"प्रभावोदाहरणम्" = 'कुरु चिनु'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = ''
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = ''
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = 'आत्'
"अङ्गम्" = 'अङ्गम्'
"प्रत्ययः/ विवक्षा" = 'लिट् प्र १'
"परिणामः" = 'औ'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = 'लँस्य प्रत्ययादेशः'
"विधिः" = ''
"सूत्रम्" = 'आत औ णलः ।'
"प्रभावोदाहरणम्" = 'ययौ ददौ तस्थौ'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'लोट् प्र १ आशिषि'
"परिणामः" = 'तु (पित्) | तात्'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = 'लँस्य प्रत्ययादेशः'
"विधिः" = 'आदेशः'
"सूत्रम्" = 'तुह्योस्तातङाशिष्यन्यतरस्याम् ।'
"प्रभावोदाहरणम्" = 'पठतु/ पठतात्'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'हु/ झलन्तम्'
"प्रत्ययः/ विवक्षा" = 'लोट् म १ आशिषि'
"परिणामः" = 'धि | तात्'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = 'लँस्य प्रत्ययादेशः'
"विधिः" = ''
"सूत्रम्" = '''
(हुझल्भ्यो हेर्धिः ।)
तुह्योस्तातङ्ङाशिष्यन्यतरस्याम्‌ (७.१.३५)'''
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'अदन्तम् | चिण्'
"प्रत्ययः/ विवक्षा" = 'लोट् म १ आशिषि'
"परिणामः" = 'लुक् | तात्'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = 'लँस्य प्रत्ययादेशः'
"विधिः" = ''
"सूत्रम्" = '''
(अतो हेः।)
तुह्योस्तातङ्ङाशिष्यन्यतरस्याम्‌ (७.१.३५)'''
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'विद्'
"प्रत्ययः/ विवक्षा" = 'शतृँ'
"परिणामः" = 'वसुँ'
"प्रासिद्ध्यम्" = '३'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'विदेः शतुर्वसुः ।'
"प्रभावोदाहरणम्" = 'विद्वस् → विद्वान्'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'समासे - अङ्पूर्वे'
"प्रत्ययः/ विवक्षा" = 'क्त्वा'
"परिणामः" = 'ल्यप्'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'समासेऽनञ्पूर्वे क्त्वो ल्यप्‌ ।'
"प्रभावोदाहरणम्" = 'प्रकृत्य'
"अभावोदाहरणम्" = 'अकृत्वा'
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'समासे - अङ्पूर्वे छन्दसि'
"प्रत्ययः/ विवक्षा" = 'क्त्वा'
"परिणामः" = 'क्त्वा वा'
"प्रासिद्ध्यम्" = '१'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'क्त्वाऽपि छन्दसि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = '''
असंयोगपूर्वः उः।
न हु चल्-ज्ञु।'''
"अङ्गम्" = 'धातुः + श्नु/ उ'
"प्रत्ययः/ विवक्षा" = 'लोटि म १'
"परिणामः" = 'लोपः'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'प्रत्ययसिद्धिः'
"विधिः" = 'हिलोपः'
"सूत्रम्" = '''
उतश्च प्रत्ययादसंयोगपूर्वात्॥
हु-चल्-ज्ञो-आक्षेपः।'''
"प्रभावोदाहरणम्" = 'चिनु। कृ+उ+लोट्=कुरु।'
"अभावोदाहरणम्" = '''
चिनुहि इति न।
जुहु। '''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = '''
अनदन्तम्
परस्मैपदे'''
"अङ्गम्" = 'अङ्गम्'
"प्रत्ययः/ विवक्षा" = 'लिङ् (सार्वधातुके)'
"परिणामः" = 'या (ङित्)'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = 'सार्वधातुके प्रत्ययादेशः'
"विधिः" = ''
"सूत्रम्" = '''
[यासुट्‌ परमैपदेषूदात्तो ङिच्च (३.४.१०३)]
लिङः सलोपोऽनन्तस्य सार्वधातुके (७.२.७९)'''
"प्रभावोदाहरणम्" = '''
भूयात् भूयासुः
नुद्यात् पठ्यात्'''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = '''
अदन्तम्
परस्मैपदे'''
"अङ्गम्" = 'अङ्गम् (एतत् तु विधिलिङि विकरणेनैव साध्यम्)'
"प्रत्ययः/ विवक्षा" = 'लिङ् (सार्वधातुके)'
"परिणामः" = 'इय्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'सार्वधातुके प्रत्ययादेशः'
"विधिः" = ''
"सूत्रम्" = 'अतो येयः सार्वधातुके (७.२.८०)'
"प्रभावोदाहरणम्" = '''
पठ्‌ + अ + यास्‌ + त् → पठ + इय्‌ + त्‌ → पठ (इति अङ्गम्‌) + इत् (इति सिद्ध-तिङ्‌प्रत्ययः) → पठेत्‌ |
नुदेत्'''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = '''
आत्मनेपदी 
अदन्तम्'''
"अङ्गम्" = 'अङ्गम्'
"प्रत्ययः/ विवक्षा" = 'लँ सार्वधातुके → आ*'
"परिणामः" = 'इय्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'सार्वधातुके प्रत्ययादेशः'
"विधिः" = 'आदेशः'
"सूत्रम्" = 'आतो ङितः।'
"प्रभावोदाहरणम्" = 'पचेताम्। पचेथाम्। यजेते। यजेथे। यजेताम्। यजेथाम्। '
"अभावोदाहरणम्" = '''
आतः इति किम्? पचन्ति। यजन्ति। पचन्ते। यजन्ते।
ङितः इति किम्? पचावहै। पचामहै। अतः इत्येव, चिन्वाते। सुन्वाते। तपरकरणम् किम्? मिमाते। मिमाथे।'''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = '''
आत्मनेपदी 
अदन्तम्'''
"अङ्गम्" = 'अङ्गम्'
"प्रत्ययः/ विवक्षा" = 'आन'
"परिणामः" = 'मुक्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'सार्वधातुके प्रत्ययादेशः'
"विधिः" = ''
"सूत्रम्" = 'आने मुक् ।'
"प्रभावोदाहरणम्" = 'यज + आन → यजमान'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'आस्'
"प्रत्ययः/ विवक्षा" = 'आन'
"परिणामः" = 'ईत्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'सार्वधातुके प्रत्ययादेशः'
"विधिः" = ''
"सूत्रम्" = 'ईदासः ।'
"प्रभावोदाहरणम्" = ' आसीनो यजते।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = 'न धा-धातोः'
"अङ्गम्" = 'झषन्तम् अङ्गम्'
"प्रत्ययः/ विवक्षा" = 'त्/थ्'
"परिणामः" = 'ध्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लँस्य प्रत्ययादेशः'
"विधिः" = 'आदेशः'
"सूत्रम्" = 'झषः तथोः धः अधः पदस्य पूर्वत्र असिद्धम् (८.२.४०)'
"प्रभावोदाहरणम्" = 'दोघ्‌ + ति → दोघ्‌ + धि'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'स्|द्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लँस्य प्रत्ययादेशः'
"विधिः" = ''
"सूत्रम्" = 'वसुस्रंसुध्वंस्वनडुहां दः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'स्|द्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लँस्य प्रत्ययादेशः'
"विधिः" = ''
"सूत्रम्" = 'तिप्यनस्तेः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'स्|द्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लँस्य प्रत्ययादेशः'
"विधिः" = ''
"सूत्रम्" = 'सिपि धातो रुर्वा ।'
"प्रभावोदाहरणम्" = 'अचकाः त्वम्, अचकात् त्वम्।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = 'दकारान्तः'
"प्रत्ययः/ विवक्षा" = 'लङि म १'
"परिणामः" = 'स्|द्'
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = 'लँस्य प्रत्ययादेशः'
"विधिः" = 'आदेशः विकल्पेन'
"सूत्रम्" = 'दश्च॥'
"प्रभावोदाहरणम्" = '''
अवेद् + स् → अवेद् / अवेः
अभिनः त्वम्, अभिनत् त्वम्।'''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गस्थितिः" = ''
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''
