[[data]]
"संज्ञा ३" = "शुद्धा"
"संज्ञा ४" = ""
"संज्ञा" = ""
"प्रामुख्यम्" = ""
"विवरणम्" = """
उपचारेण (सादृश्य-सम्बन्धेन) अमिश्रिता।
ताटस्थ्यम् (सम्पूर्णतया भिन्नत्वम्) भेदकधर्मः लक्ष्य-लक्षकयोर् इति कश्चन मीमांसकः।
 न तथेति मम्मटः - गङ्गायां घोषः इत्यत्र गङ्गा-गङ्गातीरयोः  कश्चन सम्बन्धो वर्तते इति हेतोः।"""
"उदाहरणम्" = "यष्टयः प्रविशन्ति। (पुरुषा अक्षिप्यन्ते। पुरुष-यष्टिलक्षणयोर् न सादृश्यम्।)"
"सूत्रम्" = ""

[[data]]
"संज्ञा ३" = "शुद्धा"
"संज्ञा ४" = "उपादान-लक्षणम्"
"संज्ञा" = ""
"प्रामुख्यम्" = ""
"विवरणम्" = """
स्वसिद्धये पराक्षेपः। 
स्वार्थ-अपरित्यागेन परार्थस्य उपादानम् = स्वीकारः। तेन अशक्यार्थसिद्धिः। वाच्यार्थो न पूर्णतया त्यक्तः।"""
"उदाहरणम्" = """
कुन्ताः‌ प्रविशन्ति। यष्टयः प्रविशन्ति। (पुरुषा अक्षिप्यन्ते)
मञ्चाः क्रोषन्ति।
काकेभ्यः दधि रक्ष्यताम्।"""
"सूत्रम्" = ""

[[data]]
"संज्ञा ३" = "शुद्धा"
"संज्ञा ४" = "उपादान-लक्षणम्"
"संज्ञा" = " सारोपा"
"प्रामुख्यम्" = ""
"विवरणम्" = "आरोप्यमाणः विषयः स्पष्टम् उक्तः।"
"उदाहरणम्" = "कुन्ताः पुरुषाः प्रविशन्ति।"
"सूत्रम्" = ""

[[data]]
"संज्ञा ३" = "शुद्धा"
"संज्ञा ४" = "उपादान-लक्षणम्"
"संज्ञा" = "साध्यवसाना"
"प्रामुख्यम्" = ""
"विवरणम्" = "आरोप्यमाणः विषयः अनुक्तः।"
"उदाहरणम्" = """
कुन्ताः‌ प्रविशन्ति। यष्टयः प्रविशन्ति। (पुरुषा अक्षिप्यन्ते)
"""
"सूत्रम्" = ""

[[data]]
"संज्ञा ३" = "शुद्धा"
"संज्ञा ४" = "लक्षण-लक्षणा"
"संज्ञा" = ""
"प्रामुख्यम्" = ""
"विवरणम्" = "लक्षणेन लक्षणा।"
"उदाहरणम्" = """
गङ्गायां (= पावने शीथले गङ्गातीरे) घोषः।
 गङ्गातीरे घोषः। इत्यत्र तु लक्षणा नास्ति।
"""
"सूत्रम्" = ""

[[data]]
"संज्ञा ३" = "शुद्धा"
"संज्ञा ४" = "लक्षण-लक्षणा"
"संज्ञा" = " सारोपा"
"प्रामुख्यम्" = ""
"विवरणम्" = ""
"उदाहरणम्" = "आयुर् घृतम्। (कार्यकारण-भावः)"
"सूत्रम्" = "सारोपान्या तु यत्रोक्तौ विषयी विषयस् तथा।"

[[data]]
"संज्ञा ३" = "शुद्धा"
"संज्ञा ४" = "लक्षण-लक्षणा"
"संज्ञा" = "साध्यवसाना"
"प्रामुख्यम्" = ""
"विवरणम्" = ""
"उदाहरणम्" = """
घृतं पश्यन् - आयुर् एवेदम्। (कार्यकारण-भावः)
इन्द्रार्था स्थूणा = इन्द्रः। (तादर्थ्यम्)
राजकीयपुरुषः = राजा। (स्वस्वामिभावः)
अग्रहस्तः = अङ्गुलयः। (अवयवायवीभावः)
अतक्षकुलः तक्षककार्यं करोति = तक्षा  (तात्कर्म्यम्)"""
"सूत्रम्" = "विषयि-अन्तःकृते ऽन्यस्मिन् सा स्यात् साध्यवसानिका"

[[data]]
"संज्ञा ३" = "गौणी"
"संज्ञा ४" = ""
"संज्ञा" = ""
"प्रामुख्यम्" = ""
"विवरणम्" = "उपचारेण (सादृश्य-सम्बन्धेन) मिश्रिता।"
"उदाहरणम्" = "गौः वाहीकः (वाहीकदेशीयो मन्दः जडः)। सोंहो माणवकः। "
"सूत्रम्" = "लक्ष्यमाणगुणैर् योगाद् वृत्तेर् इष्टा तु गौणता।"

[[data]]
"संज्ञा ३" = "गौणी"
"संज्ञा ४" = " सारोपा"
"संज्ञा" = ""
"प्रामुख्यम्" = ""
"विवरणम्" = "आरोपविषयः च आरोप्यमाणः (विषयी/ उपमानम्) सामानधिकरण्ये स्तः।"
"उदाहरणम्" = """
गौः वाहीकः (वाहीकदेशीयो मन्दः जडः)।
आरोपविषयः वाहीकः।"""
"सूत्रम्" = "सारोपान्या तु यत्रोक्तौ विषयी विषयस् तथा।"

[[data]]
"संज्ञा ३" = "गौणी"
"संज्ञा ४" = "साध्यवसाना"
"संज्ञा" = ""
"प्रामुख्यम्" = ""
"विवरणम्" = "उपमानेन उपमेय-कथनम्।"
"उदाहरणम्" = """
वाहीकं पश्यन् - \"गौर् अयम्।\" इति वचनम्।
कर्मणि कुशलः। (रूढिः)"""
"सूत्रम्" = "विषयि-अन्तःकृते ऽन्यस्मिन् सा स्यात् साध्यवसानिका"

[[data]]
"संज्ञा ३" = "सव्यङ्ग्यता"
"संज्ञा ४" = "रूढिः"
"संज्ञा" = ""
"प्रामुख्यम्" = ""
"विवरणम्" = "प्रसिद्धौ व्यङ्ग्यार्थराहित्यम्।"
"उदाहरणम्" = "कर्मणि कुशलः। (रूढिः)"
"सूत्रम्" = """
व्यङ्ग्येन रहिता रूढौ सहिता तु प्रयोजने ।
तच्च गूढमगूढं वा तदेषा कथिता त्रिधा ॥ काप्र-१३ ॥"""

[[data]]
"संज्ञा ३" = "सव्यङ्ग्यता"
"संज्ञा ४" = "प्रयोजनम्"
"संज्ञा" = ""
"प्रामुख्यम्" = ""
"विवरणम्" = ""
"उदाहरणम्" = """
मुखं विकसितस्मितम्। तरुणिमा उद्गमः मोदते।
(अचेतनस्य कुतो मोदनम्? मुखस्य कुतो विकसनम्)"""
"सूत्रम्" = """
व्यङ्ग्येन रहिता रूढौ सहिता तु प्रयोजने ।
तच्च गूढमगूढं वा तदेषा कथिता त्रिधा ॥ काप्र-१३ ॥"""

[[data]]
"संज्ञा ३" = "सव्यङ्ग्यता"
"संज्ञा ४" = "प्रयोजनम्"
"संज्ञा" = "गूढम्"
"प्रामुख्यम्" = ""
"विवरणम्" = ""
"उदाहरणम्" = """
मुखं विकसितस्मितम्। समुच्छलितविभ्रमा गतिः। तरुणिमा उद्गमः मोदते।
(सा सुन्दरी इति गूढम् व्यङ्ग्यम्।)"""
"सूत्रम्" = """
व्यङ्ग्येन रहिता रूढौ सहिता तु प्रयोजने ।
तच्च गूढमगूढं वा तदेषा कथिता त्रिधा ॥ काप्र-१३ ॥"""

[[data]]
"संज्ञा ३" = "सव्यङ्ग्यता"
"संज्ञा ४" = "प्रयोजनम्"
"संज्ञा" = "अगूढम्"
"प्रामुख्यम्" = ""
"विवरणम्" = ""
"उदाहरणम्" = """
श्रीपरिचयात् जडा अपि भवन्ति अभिज्ञा विदग्धचरितानाम्।
उपदिशन्ति कामिनीनाम् यौवनमद एव ललितानि॥ 
(लक्षणा - अचेतनेन कुत उपदेशः?) (सा युवती सुन्दरी इति अगूढं व्यङ्ग्यम्।)"""
"सूत्रम्" = """
व्यङ्ग्येन रहिता रूढौ सहिता तु प्रयोजने ।
तच्च गूढमगूढं वा तदेषा कथिता त्रिधा ॥ काप्र-१३ ॥"""
