[[data]]
"संज्ञा ३" = "अविवक्षित-वाच्यः"
"संज्ञा ४" = ""
"संज्ञा" = ""
"प्रामुख्यम्" = ""
"विवरणम्" = "वाच्यार्थो ऽत्र‌+‌अविवक्षितो बाधितश्च। लक्षणया ऽर्थान्तरं जनयित्वा, ततो ध्वनिः।"
"उदाहरणम्" = ""

[[data]]
"संज्ञा ३" = "अविवक्षित-वाच्यः"
"संज्ञा ४" = "अर्थान्तरसङ्क्रमित-वाच्यः"
"संज्ञा" = ""
"प्रामुख्यम्" = ""
"विवरणम्" = "उपादानलक्षणाधारः (वाच्यार्थांशोऽपरित्यक्तः) ।"
"उदाहरणम्" = """
दिन वही दिन है, शब वही शब है। 
जो तेरी याद मेँ गुजर जाए। (दिन = सफलतापूर्वक-दिन)"""

[[data]]
"संज्ञा ३" = "अविवक्षित-वाच्यः"
"संज्ञा ४" = "अत्यन्त-तिरस्कऋत-वाच्यः"
"संज्ञा" = ""
"प्रामुख्यम्" = ""
"विवरणम्" = "लक्षण-लक्षणाधारः।"
"उदाहरणम्" = ""

[[data]]
"संज्ञा ३" = "विवक्षितान्यपर-वाच्यः"
"संज्ञा ४" = ""
"संज्ञा" = ""
"प्रामुख्यम्" = ""
"विवरणम्" = "वाच्यार्थो विवक्षित एव। वाच्यार्थमूल एव ध्वनिः।"
"उदाहरणम्" = ""

[[data]]
"संज्ञा ३" = "विवक्षितान्यपर-वाच्यः"
"संज्ञा ४" = "असंलक्ष्य-क्रम-व्यङ्ग्यः"
"संज्ञा" = ""
"प्रामुख्यम्" = ""
"विवरणम्" = """
शीघ्रमेव वाच्यार्थो व्यङ्ग्यं बोधयति, येन क्रम एव न लक्ष्यते। वाच्यार्थस् तिरोहित इव क्षणे। एष ध्वनेः प्रमुख-प्रकारः।
रसाधिक-ध्वनिर्/ रसध्वनिर् इति च नामान्तरम्।"""
"उदाहरणम्" = ""

[[data]]
"संज्ञा ३" = "विवक्षितान्यपर-वाच्यः"
"संज्ञा ४" = "असंलक्ष्य-क्रम-व्यङ्ग्यः"
"संज्ञा" = "रसः"
"प्रामुख्यम्" = ""
"विवरणम्" = """
शब्दोक्तैर् विभाव+अनुभाव+सञ्चारि-भावैः संयुक्तैः सहृदय-हृदयस्थ-स्थायि-भावा उद्भूयन्ते, ततो रसं व्यञ्जयन्ति।
https://docs.google.com/spreadsheets/d/1_Hokp6dvWReXvQyXpDXi8u-VEqrn0e5ZkspNpZAM7Vc/edit#gid=6"""
"उदाहरणम्" = ""

[[data]]
"संज्ञा ३" = "विवक्षितान्यपर-वाच्यः"
"संज्ञा ४" = "असंलक्ष्य-क्रम-व्यङ्ग्यः"
"संज्ञा" = "भावः"
"प्रामुख्यम्" = ""
"विवरणम्" = ""
"उदाहरणम्" = ""

[[data]]
"संज्ञा ३" = "विवक्षितान्यपर-वाच्यः"
"संज्ञा ४" = "असंलक्ष्य-क्रम-व्यङ्ग्यः"
"संज्ञा" = "भावः"
"प्रामुख्यम्" = ""
"विवरणम्" = "वात्सल्यम्, सख्यम् …(ये रसा न, भावाः)"
"उदाहरणम्" = ""

[[data]]
"संज्ञा ३" = "विवक्षितान्यपर-वाच्यः"
"संज्ञा ४" = "असंलक्ष्य-क्रम-व्यङ्ग्यः"
"संज्ञा" = "भावः - व्यभिचारिभावः"
"प्रामुख्यम्" = ""
"विवरणम्" = "रसादधिकम् अत्र व्यभिचारिभावो व्यज्यते।"
"उदाहरणम्" = ""

[[data]]
"संज्ञा ३" = "विवक्षितान्यपर-वाच्यः"
"संज्ञा ४" = "असंलक्ष्य-क्रम-व्यङ्ग्यः"
"संज्ञा" = "रसाभासः"
"प्रामुख्यम्" = ""
"विवरणम्" = "सामाजिकादि-कारणैः स्थायीभावानौचित्यात् । करुण-बीभत्सयोर् नास्तीति केचित्।"
"उदाहरणम्" = "सीताम् प्रति रावणरतिः।"

[[data]]
"संज्ञा ३" = "विवक्षितान्यपर-वाच्यः"
"संज्ञा ४" = "असंलक्ष्य-क्रम-व्यङ्ग्यः"
"संज्ञा" = "भावाभासः"
"प्रामुख्यम्" = ""
"विवरणम्" = ""
"उदाहरणम्" = ""

[[data]]
"संज्ञा ३" = "विवक्षितान्यपर-वाच्यः"
"संज्ञा ४" = "असंलक्ष्य-क्रम-व्यङ्ग्यः"
"संज्ञा" = "भावशान्तिः"
"प्रामुख्यम्" = ""
"विवरणम्" = ""
"उदाहरणम्" = ""

[[data]]
"संज्ञा ३" = "विवक्षितान्यपर-वाच्यः"
"संज्ञा ४" = "असंलक्ष्य-क्रम-व्यङ्ग्यः"
"संज्ञा" = "भावोदयः"
"प्रामुख्यम्" = ""
"विवरणम्" = ""
"उदाहरणम्" = ""

[[data]]
"संज्ञा ३" = "विवक्षितान्यपर-वाच्यः"
"संज्ञा ४" = "असंलक्ष्य-क्रम-व्यङ्ग्यः"
"संज्ञा" = "भावसन्धिः"
"प्रामुख्यम्" = ""
"विवरणम्" = ""
"उदाहरणम्" = ""

[[data]]
"संज्ञा ३" = "विवक्षितान्यपर-वाच्यः"
"संज्ञा ४" = "असंलक्ष्य-क्रम-व्यङ्ग्यः"
"संज्ञा" = "भाव-शबलता"
"प्रामुख्यम्" = ""
"विवरणम्" = ""
"उदाहरणम्" = ""
