[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'झल्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'झश्'
"परवर्णस्थितिः" = ''
"परिणामः" = 'जश्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = 'झलां जश् झशि ।'
"उदाहरणम्" = 'दध्+ध्वम् = दद्ध्वम्।'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = '[अभ्यास-प्रकरणे उक्तम्]'
"सूत्रम्" = 'अभ्यासे चर्च्च ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'झय्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'खय्'
"परवर्णस्थितिः" = ''
"परिणामः" = 'चय्॥ (वर्गीय-प्रथमम्।)'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '(संहितायां झलां चर्) खरि च (८।४।५५)'
"उदाहरणम्" = 'अनुष्टुभ् छन्दः = अनुष्टुप्छन्दः'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'झय्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'खय्'
"परवर्णस्थितिः" = ''
"परिणामः" = 'चय्॥ (वर्गीय-प्रथमम्।) वा'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'वाऽवसाने ।'
"उदाहरणम्" = 'वाग् / वाक्'
"अभावोदाहरणम्" = ''
"विवरणम्" = '''
अवसाने परे झल्-वर्णस्य विकल्पेन चर्त्वम् भवति । 
उदाहरणानि बहुत्र विकीर्णानि - यथा https://docs.google.com/spreadsheets/d/1GP8Ps_hmgCGLZPWKIVBCfQB9ZmPQOaCwTrH9OybaWaQ/edit#gid=9 ।'''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'अणोऽप्रगृह्यस्यानुनासिकः ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'ं'
"उत्तराक्षरम् सन्धिपूर्वम्" = '''
[यय्॥]
[य् व् र् ल् वर्गीयव्यञ्जनानि]'''
"परवर्णस्थितिः" = ''
"परिणामः" = 'ङ् ञ् ण् न् म् यँ रँ लँ वँ'
"प्रामुख्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = 'अनुस्वारस्य ययि परसवर्णः (८।४।५८)'
"उदाहरणम्" = '''
कक्ष्याङ्गच्छामि
संयमः -> सय्ँयमः'''
"अभावोदाहरणम्" = ''
"विवरणम्" = 'अन्ते प्रयोक्तव्यम्'

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'ं पदान्ते'
"उत्तराक्षरम् सन्धिपूर्वम्" = '''
[यय्॥]
[य् व् र् ल् वर्गीयव्यञ्जनानि]'''
"परवर्णस्थितिः" = ''
"परिणामः" = 'ङ् ञ् ण् न् म् यँ रँ लँ वँ (वा)'
"प्रामुख्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'वा पदान्तस्य ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'तुँ'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'ल्'
"परवर्णस्थितिः" = ''
"परिणामः" = '''
ल्
नस्य ल्ँ'''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = 'तोर्लि॥'
"उदाहरणम्" = 'अक्षयान् + लोकान् = अक्षयाल्ँ लोकान्'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'उदः स्थास्तम्भोः पूर्वस्य ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'झय्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'ह्'
"परवर्णस्थितिः" = ''
"परिणामः" = 'झष्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = 'आदेशः परस्य विकल्पेन'
"सूत्रम्" = 'झयो होऽन्यतरस्याम्॥'
"उदाहरणम्" = '''
तद् + हितम् = तद्धितम्/ तद्हितम्
त्रिष्टुब् भसति, त्रिष्टुब् हसति।
षष् +‌हत = षड् हत (झलां जशोऽन्ते) = षड्ढत'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'चय्॥'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'श्'
"परवर्णस्थितिः" = ''
"परिणामः" = 'छ्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'छत्व'
"विधिः" = 'आदेशः परस्य'
"सूत्रम्" = 'शः छः अटि'
"उदाहरणम्" = 'तच्छब्दः'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'हलो यमां यमि लोपः ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'झरो झरि सवर्णे ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = 'हल् +'
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'झर्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'झर्'
"परवर्णस्थितिः" = 'सवर्णे'
"परिणामः" = 'लोपः'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = 'आदेशः पूर्वस्य विकल्पेन'
"सूत्रम्" = '[हलः] झरो झरि सवर्णे [लोपः अन्यतरस्यां] [8.4.65]'
"उदाहरणम्" = '''
छिंद्‌ + थः → खरि च → छिन्त्‌ + थः → छिन्त्थः / छिन्थः।
न अत्र - अत्‌ + थः → अत्थः॥'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''
