[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = '''
र्,ष्,ऋ 
[अच् हट् कुँ पुँ 
धातुषु-नुम्]*'''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = '''
न्[अच्]
समानपदे
अकृति'''
"परवर्णस्थितिः" = 'न विभक्तिषु (तत्र विकल्पः पश्चादुक्तः)'
"परिणामः" = 'ण्'
"प्रामुख्यम्" = '५'
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = 'आदेशः नः'
"सूत्रम्" = '''
रषाभ्यां नो णः समानपदे॥
ऋवर्णाच् च +इति वक्तव्यम्।(वा)
अट्-कु-प्व्-आङ्-नुम्-व्यवायेऽपि ।'''
"उदाहरणम्" = '''
रामेण, परन्तु रामान्।
आङ् - पर्याणद्धम्।
नुम् - बृंहणम्।'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = '''
पूर्वपदे
र्,ष्,ऋ 
[अच् हट् (कुँ-ग) पुँ 
धातुषु-नुम्]*
'''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = '''
न्[अच्]
'''
"परवर्णस्थितिः" = '''
समस्तपदे
उत्तरपदे
संज्ञायाम्'''
"परिणामः" = 'ण्'
"प्रामुख्यम्" = '३'
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = 'आदेशः नः'
"सूत्रम्" = 'पूर्वपदात्‌ संज्ञायामगः ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = 'चितशब्दाः'
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = 'वन'
"परवर्णस्थितिः" = '''
समस्तपदे
उत्तरपदे'''
"परिणामः" = 'ण्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = 'आदेशः नः'
"सूत्रम्" = 'वनं पुरगामिश्रकासिध्रकाशारिकाकोटराऽग्रेभ्यः ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'प्रनिरन्तःशरेक्षुप्लक्षाम्रकार्ष्यखदिरपियूक्षाभ्योऽसंज्ञायामपि ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = '''
वनस्पतिः/ ओषधिः
र्,ष्,ऋ 
[अच् हट् कुँ पुँ 
धातुषु-नुम्]*'''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = 'वन'
"परवर्णस्थितिः" = '''
समस्तपदे
उत्तरपदे'''
"परिणामः" = 'ण्/ न्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = 'आदेशः नः वा'
"सूत्रम्" = 'विभाषौषधिवनस्पतिभ्यः॥'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अह्नः'
"परवर्णस्थितिः" = '''
समस्तपदे
उत्तरपदे'''
"परिणामः" = 'ण्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = 'आदेशः नः'
"सूत्रम्" = 'अह्नो ऽदन्तात्'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = 'वाहम्'
"परवर्णस्थितिः" = '''
समस्तपदे
उत्तरपदे'''
"परिणामः" = 'ण्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = 'आदेशः नः'
"सूत्रम्" = 'वाहनम् आहितात्'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = 'देशे'
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = 'पानम्'
"परवर्णस्थितिः" = '''
समस्तपदे
उत्तरपदे'''
"परिणामः" = 'ण्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = 'आदेशः नः'
"सूत्रम्" = 'पानं देशे'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = 'न्[अच्]'
"परवर्णस्थितिः" = '''
समस्तपदे
उत्तरपदे
भाव/करणयोः'''
"परिणामः" = 'ण्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = 'आदेशः नः वा'
"सूत्रम्" = 'वा भावकरणयोः॥'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = 'न्[अच्]'
"परवर्णस्थितिः" = 'सुप्सु'
"परिणामः" = 'ण्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = 'आदेशः नः वा'
"सूत्रम्" = 'प्रातिपदिकान्त-नुम्-विभक्तिषु च॥'
"उदाहरणम्" = 'माषवापेण / माषवापेन'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'एकाजुत्तरपदे णः ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'कुमति च ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'रवान् उपसर्गः + णोपदेशः धातुः'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'न्[अच्]'
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'उपसर्गादसमासेऽपि णोपदेशस्य ।'
"उदाहरणम्" = 'रणमति। परिणमति। प्रणायकः। परिणायकः।'
"अभावोदाहरणम्" = 'उपसर्गातिति किम्? प्रगता नायकाः अस्माद् देशात् प्रनायको देशः।'
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'हिनुमीना ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'उपसर्गे रेफः + धातुः'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'न्[अच्]'
"परवर्णस्थितिः" = 'आनि लोट्'
"परिणामः" = 'ण्'
"प्रामुख्यम्" = '३'
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'आनि लोट् ।'
"उदाहरणम्" = 'परियाणि'
"अभावोदाहरणम्" = 'मांसानि'
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'नेर्गदनदपतपदघुमास्यतिहन्तियातिवातिद्रातिप्सातिवपतिवहतिशाम्यतिचिनोतिदेग्धिषु च ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'शेषे विभाषाऽकखादावषान्त उपदेशे ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'अनितेः ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'अन्तः ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'उभौ साभ्यासस्य ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'हन्तेरत्पूर्वस्य ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'वमोर्वा ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'अन्तरदेशे ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'अयनं च ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'छन्दस्यृदवग्रहात्‌ ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'नश्च धातुस्थोरुषुभ्यः ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'उपसर्गाद् बहुलम् ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = '''
उपसर्गे
र्,ष्,ऋ 
[अच् हट् कुँ पुँ 
धातुषु-नुम्]*'''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = '''
[अच्]न्[अच्]
'''
"परवर्णस्थितिः" = 'कृत्'
"परिणामः" = 'ण्'
"प्रामुख्यम्" = '५'
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = 'आदेशः नः'
"सूत्रम्" = 'कृत्यचः ।'
"उदाहरणम्" = '''
प्रयाणम्। प्रयाणीयम्।
न अत्र -  प्रभुग्नः, परिभुग्नः ।'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = '''
उपसर्गे
र्,ष्,ऋ 
[अच् हट् कुँ पुँ 
धातुषु-नुम्]*'''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'णिजन्तः धातुः'
"उत्तराक्षरम् सन्धिपूर्वम्" = '[अच्]न्[अच्]'
"परवर्णस्थितिः" = 'कृत्'
"परिणामः" = 'ण् / न्'
"प्रामुख्यम्" = '४'
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = 'आदेशः नः'
"सूत्रम्" = 'णेर्विभाषा ।'
"उदाहरणम्" = 'प्रयापणीयम् प्रयापनीयम् ।'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = '''
उपसर्गे
र्,ष्,ऋ 
[अच् हट् कुँ पुँ 
धातुषु-नुम्]*'''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'हलादिः  इच्-उपधा'
"उत्तराक्षरम् सन्धिपूर्वम्" = '[अच्]न्[अच्]'
"परवर्णस्थितिः" = 'कृत्'
"परिणामः" = 'ण् / न्'
"प्रामुख्यम्" = '४'
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = 'आदेशः नः'
"सूत्रम्" = 'हलश्च इजुपधात्‌ ।'
"उदाहरणम्" = '''
प्रकोपणियम् प्रकोपनीयम् । 
हलः किम् ? प्रोहणीयम् । 
इजुपधात् किम् ? प्रवपणीयम् ।'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = '''
उपसर्गे
र्,ष्,ऋ 
[अच् हट् कुँ पुँ 
धातुषु-नुम्]*'''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'इजादिः धातुः सनुम्'
"उत्तराक्षरम् सन्धिपूर्वम्" = '[अच्]न्[अच्]'
"परवर्णस्थितिः" = 'कृत्'
"परिणामः" = 'ण्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = 'आदेशः नः'
"सूत्रम्" = 'इजादेः सनुमः ।'
"उदाहरणम्" = '''
प्रेङ्खणियम् । 
इजादेः किम् ? प्रमङ्गनीयम् । मगि सर्पणे ।'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = '''
उपसर्गे
र्,ष्,ऋ 
[अच् हट् कुँ पुँ 
धातुषु-नुम्]*'''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'निंस निक्ष निन्द'
"उत्तराक्षरम् सन्धिपूर्वम्" = '[अच्]न्[अच्]'
"परवर्णस्थितिः" = 'कृत्'
"परिणामः" = 'ण् / न्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = 'आदेशः नः'
"सूत्रम्" = 'वा निंसनिक्षनिन्दाम् ।'
"उदाहरणम्" = '''
प्रनिंसितव्यम् । प्रणिंसितव्यम् ।

'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = '''
पूर्वपदे
र्,ष्,ऋ 
[अच् हट् (कुँ-ग) पुँ 
धातुषु-नुम्]*'''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'भा | भू | पू(-ङ्) | कम्| गम्|| प्यायी |‌वेप'
"उत्तराक्षरम् सन्धिपूर्वम्" = '[अच्]न्[अच्]'
"परवर्णस्थितिः" = 'कृत्'
"परिणामः" = '- ण्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = 'यथा पूर्वम्'
"सूत्रम्" = '''
न भाभूपूकमिगमिप्यायीवेपाम्  ( णः समानपदे उपसर्गाद् कृति )॥
'''
"उदाहरणम्" = '''
कमि प्रकमनम्। परिकमनम्। गमि प्रगमनम्। परिगमनम्। प्यायी प्रप्यायनम्। परिप्यायनम्। वेप प्रवेपनम्। परिवेपनम्। ण्यन्तानां भादीनाम् उपसङ्ख्यानं कर्तव्यम्। प्रभापनम्। परिभापनम्।

'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = '''
पूर्वपदे
र्,ष्,ऋ 
[अच् हट् (कुँ-ग) पुँ 
धातुषु-नुम्]*'''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'पूङ्'
"उत्तराक्षरम् सन्धिपूर्वम्" = '[अच्]न्[अच्]'
"परवर्णस्थितिः" = ''
"परिणामः" = ' +  ण्'
"प्रामुख्यम्" = '२'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'पूञ एव इह ग्रहणमिष्यते (वा)'
"उदाहरणम्" = 'पूङ् प्रवपणीयः सोमः ।'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = '''
पूर्वपदे
र्,ष्,ऋ 
[अच् हट् (कुँ-ग) पुँ 
धातुषु-नुम्]*'''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'भा | भू | पू(-ङ्) | कम्| गम्|| प्यायी |‌वेप+णि'
"उत्तराक्षरम् सन्धिपूर्वम्" = '[अच्]न्[अच्]'
"परवर्णस्थितिः" = ''
"परिणामः" = '- ण्'
"प्रामुख्यम्" = '३'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'ण्यन्तभादीनाम् उपसंख्यानम् (वा)'
"उदाहरणम्" = 'प्रभापनीयम् । प्रख्यानीयम् ।'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = '''
पूर्वपदे
र्,ष्,ऋ 
[अच् हट् (कुँ-ग) पुँ 
धातुषु-नुम्]*'''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = '- ण्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'षात्‌ पदान्तात्‌ ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = '''
पूर्वपदे
र्,ष्,ऋ 
[अच् हट् (कुँ-ग) पुँ 
धातुषु-नुम्]*'''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = '- ण्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'नशेः षान्तस्य ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = '''
पूर्वपदे
र्,ष्,ऋ 
[अच् हट् (कुँ-ग) पुँ 
धातुषु-नुम्]*'''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = '- ण्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'पदान्तस्य ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = '''
पूर्वपदे
र्,ष्,ऋ 
[अच् हट् (कुँ-ग) पुँ 
धातुषु-नुम्]*'''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = '- ण्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'पदव्यवायेऽपि ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = '''
पूर्वपदे
र्,ष्,ऋ 
[अच् हट् (कुँ-ग) पुँ 
धातुषु-नुम्]*'''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = '- ण्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'णत्वम्'
"विधिः" = ''
"सूत्रम्" = 'क्षुभ्नाऽऽदिषु च ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''
