[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'ऋक्पादमध्ये ए ओ'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अ[^व्य्]'
"परिणामः" = ''
"प्रामुख्यम्" = '२'
"विधिप्रकारः" = 'प्रकृतिभावः'
"विधिः" = ''
"सूत्रम्" = 'प्रकृत्या ऽन्तःपादम् अव्यपरे ।'
"उदाहरणम्" = 'ते अग्ने अश्वमायुञ्जन्; ते अस्मिन् जवमादधुः'
"अभावोदाहरणम्" = 'तेऽवदन्'
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'ऋक्पादमध्ये  ए ओ'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अव्यात् , अवद्यात् , अवक्रमुः , अव्रत , अवन्तु , अवस्यु'
"परिणामः" = ''
"प्रामुख्यम्" = '१'
"विधिप्रकारः" = 'प्रकृतिभावः'
"विधिः" = ''
"सूत्रम्" = 'अव्याद्-अवद्याद्-अवक्रमुर्-अव्रताऽयम्-अवन्त्व्-अवस्युषु च ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'यजुष्य् उरो'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अ'
"परिणामः" = ''
"प्रामुख्यम्" = '१'
"विधिप्रकारः" = 'प्रकृतिभावः'
"विधिः" = ''
"सूत्रम्" = 'यजुष्य् उरः ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'यजुषि आपो , जुषाणो , वृष्णो , वर्षिष्ठे'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अ'
"परिणामः" = ''
"प्रामुख्यम्" = '२'
"विधिप्रकारः" = 'प्रकृतिभावः'
"विधिः" = ''
"सूत्रम्" = 'आपो-जुषाणो-वृष्णो-वर्षिष्ठेऽम्बेऽम्बालेऽम्बिकेपूर्वे ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'यजुषि अम्बे अम्बाले'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अम्बालिके'
"परिणामः" = ''
"प्रामुख्यम्" = '१'
"विधिप्रकारः" = 'प्रकृतिभावः'
"विधिः" = ''
"सूत्रम्" = 'आपो-जुषाणो-वृष्णो-वर्षिष्ठेऽम्बेऽम्बालेऽम्बिकेपूर्वे ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'यजुषि ए ओ'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अङ्गे'
"परिणामः" = ''
"प्रामुख्यम्" = '२'
"विधिप्रकारः" = 'प्रकृतिभावः'
"विधिः" = ''
"सूत्रम्" = 'अङ्ग इत्यादौ च ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'यजुषि ए ओ'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अनुदात्तः अ(कवर्गः|ध)'
"परिणामः" = ''
"प्रामुख्यम्" = '२'
"विधिप्रकारः" = 'प्रकृतिभावः'
"विधिः" = ''
"सूत्रम्" = 'अनुदात्ते च कुधपरे ।'
"उदाहरणम्" = 'अयं सो अग्निः। अयं सो अध्वरः।'
"अभावोदाहरणम्" = 'अनुदात्ते इति किम्? अधोग्रे।'
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'यजुषि ए ओ'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अनुदात्तः। अ(वपथाः)'
"परिणामः" = ''
"प्रामुख्यम्" = '१'
"विधिप्रकारः" = 'प्रकृतिभावः'
"विधिः" = ''
"सूत्रम्" = 'अवपथासि च ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'गो'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अ'
"परिणामः" = 'गोऽ|०'
"प्रामुख्यम्" = '४'
"विधिप्रकारः" = 'प्रकृतिभावः'
"विधिः" = '''
लोपः परस्य
वा आदेशः पूर्वस्य
वा प्रकृतिभावः'''
"सूत्रम्" = '''
सर्वत्र विभाषा गोः ।
अवङ् स्फोटायनस्य॥'''
"उदाहरणम्" = '''
गो अग्रम्। गवाग्रम्।
वा गोऽग्रम् [समस्तपदेऽपि "प्रत्ययलोपे प्रत्ययलक्षणम्" इत्यस्मात् पदान्तसंज्ञा गोः]'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'गो'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अच् && ^इन्द्र'
"परिणामः" = 'अव् वा'
"प्रामुख्यम्" = '४'
"विधिप्रकारः" = 'प्रकृतिभावः'
"विधिः" = 'वा आदेशः पूर्वस्य'
"सूत्रम्" = 'अवङ् स्फोटायनस्य॥'
"उदाहरणम्" = 'गवाजिनम्, गवौदनम्, गवोष्ट्रम्,  गोऽग्रम्, गोऽजिनम्, गवोदनम्, गवुष्ट्रम्'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = 'गो-शब्दात्'
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'ओ'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'इन्द्र'
"परिणामः" = 'अव'
"प्रामुख्यम्" = '२'
"विधिप्रकारः" = 'प्रकृतिभावः'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = 'इन्द्रे च॥'
"उदाहरणम्" = 'गौ इन्द्र = गवेन्द्र (न गविन्द्रेति)'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'प्लुतः | प्रगृह्य'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अच्॥'
"परिणामः" = '०'
"प्रामुख्यम्" = '५'
"विधिप्रकारः" = 'प्रकृतिभावः'
"विधिः" = ''
"सूत्रम्" = 'प्लुतप्रगृह्या अचि नित्यम् (६।१।१२५)'
"उदाहरणम्" = '''
हरी एतौ। इ इन्द्रः।
अहो! अहम् आगतः।'''
"अभावोदाहरणम्" = ''
"विवरणम्" = 'प्रागृह्य-विवरणम् अन्यत्र'

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'आ छन्दसि'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अच्'
"परिणामः" = 'आँ'
"प्रामुख्यम्" = '१'
"विधिप्रकारः" = 'प्रकृतिभावः'
"विधिः" = ''
"सूत्रम्" = 'आङोऽनुनासिकश्छन्दसि ।'
"उदाहरणम्" = 'अभ्र आँ अपः'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'इक्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'असवर्णः'
"परिणामः" = 'ह्रस्वः विकल्पेन'
"प्रामुख्यम्" = '५'
"विधिप्रकारः" = 'प्रकृतिभावः'
"विधिः" = ''
"सूत्रम्" = 'इकोऽसवर्णे शाकल्यस्य ह्रस्वश्च ।'
"उदाहरणम्" = 'दधि अत्र, मधु अत्र, कुमारि अत्र किशोरि अत्र॥'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'अक्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'ऋ'
"परिणामः" = '०'
"प्रामुख्यम्" = '५'
"विधिप्रकारः" = 'प्रकृतिभावः'
"विधिः" = ''
"सूत्रम्" = 'ऋत्यकः ।'
"उदाहरणम्" = 'खट्व + ऋश्यः, माल + ऋश्यः, मुमारि + ऋश्यः, होतृ + ऋश्यः॥'
"अभावोदाहरणम्" = ''
"विवरणम्" = 'शाकल्यस्य मतेन - पदान्त-अक्-वर्णस्य असवर्णे ऋकारे परे प्रकृतिभावः भवति । '

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'प्लुतः'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'इति (अवैदिकः)'
"परिणामः" = 'अप्लुतवत्'
"प्रामुख्यम्" = '३'
"विधिप्रकारः" = 'प्रकृतिभावः'
"विधिः" = ''
"सूत्रम्" = 'अप्लुतवदुपस्थिते ।'
"उदाहरणम्" = 'सुश्लोका ३ इति = सुश्लोकेति'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'ई३'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अच्'
"परिणामः" = 'अप्लुतवत्'
"प्रामुख्यम्" = '३'
"विधिप्रकारः" = 'प्रकृतिभावः'
"विधिः" = ''
"सूत्रम्" = 'ई३ चाक्रवर्मणस्य ।'
"उदाहरणम्" = 'चिनु हीदम् or चिनु ही३ इदम् ॥'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''
