[[data]]
"अन्तर्भूतम्" = ''
"संज्ञा" = 'संहिता'
"प्रामुख्यम्" = ''
"सूत्रम्" = 'परः संनिकर्षः संहिता'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = '''
 वर्णानाम् अतिशयितः संनिधिः संहिता।
पूर्ववर्णोच्चारणानन्तरमेव यद्वर्णान्तरम् उच्चार्यते , न तु तच्छून्यान्तरालसद्भावः स परः उत्कृष्टः सन्निकर्षः प्रत्यासत्तिलक्षणः संहितासंज्ञः इति सूत्रार्थः । इति कय्यटः।
वर्णानामेकप्राणयोगस्संहिता इति प्रातिशाख्याः।
"पदप्रकृतिः संहिता (निरु. पू. 6 खं. 17)"'''

[[data]]
"अन्तर्भूतम्" = ''
"संज्ञा" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'परः सन्निकर्षः संहिता चेदद्रुतायम् असंहितम् (वार्तिकम्)'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अन्तर्भूतम्" = ''
"संज्ञा" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'तुल्यः सन्निकर्षः (वा)'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = 'भा - तुल्यः सन्निकर्षः वर्णानां द्रुतमध्यविलम्बितासु वृत्तिषु'

[[data]]
"अन्तर्भूतम्" = ''
"संज्ञा" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'वर्णकालभूयस्त्वं तु (वा)'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = '''
वर्णानां तु कालभूयस्त्वम् । तद्यथा - हस्तिमशकयोः तुल्यः सन्निकर्षः , प्राणिभूयस्त्वं तु । (प्राणी=शरीरम् - नागेशः)

कैयटः -- हस्तिमशकयोरिति । हस्तिनो हस्तिनः यः सन्निकर्षः मशकस्य मशकेन सः तुल्यः परस्परापेक्षय़ा इत्यर्थः । प्राणिभूयस्त्वम् । हस्तिनौ महान्तं देशं व्याप्नुतः मशकौ तु स्वल्पम्। नैरन्तर्यं तु अविशिष्टम् इत्यर्थः।'''

[[data]]
"अन्तर्भूतम्" = ''
"संज्ञा" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'उक्तं वा (वा)'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = 'भा - किमुक्तम् ? सिद्धं त्ववस्थिता वर्णा वक्तुः चिराचिरवचनात् वृत्तयो विशिष्यन्ते इति ।'

[[data]]
"अन्तर्भूतम्" = ''
"संज्ञा" = 'अवसानम्'
"प्रामुख्यम्" = ''
"सूत्रम्" = 'विरामोऽवसानम्'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अन्तर्भूतम्" = ''
"संज्ञा" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'संहितावसानयोः लोकविदितत्वात् सिद्धम् (वा)'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = '''
भा - संहिता अवसानम् इति लोकविदितौ एतौ अर्थौ ।
कैय्यटः - यथा पदनैरन्तर्ये संहिताव्यवहारः तथा ऐकपद्ये’पि वर्णनैर्न्तर्ये ।'''

[[data]]
"अन्तर्भूतम्" = ''
"संज्ञा" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अन्तर्भूतम्" = 'हल्+हल्'
"संज्ञा" = 'संयोगः'
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'हलोऽनन्तराः संयोगः ।'
"उदाहरणम्" = 'क्स्'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अन्तर्भूतम्" = ''
"संज्ञा" = 'अनुनासिकः'
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'मुखनासिकावचनोऽनुनासिकः ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अन्तर्भूतम्" = ''
"संज्ञा" = 'सवर्णम्‌'
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'तुल्यास्यप्रयत्नं सवर्णम् ।'
"उदाहरणम्" = 'अ+अ इ+ई'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अन्तर्भूतम्" = ''
"संज्ञा" = 'सवर्णम्‌'
"प्रामुख्यम्" = ''
"सूत्रम्" = 'नाज्झलौ ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अन्तर्भूतम्" = ''
"संज्ञा" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अन्तर्भूतम्" = '(*-ईत् |*-ऊत् | *-एत्) ^ द्विवचनम्'
"संज्ञा" = 'प्रगृह्यम्‌'
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'ईदूदेद्द्विवचनं प्रगृह्यम् ।'
"उदाहरणम्" = '''
अग्नी इति। वायु इति। माले इति। पचेते इति। 
किं दम्पतिमिति ब्रूयामुताहो दम्पती इति । इत्यस्मिन् नीलकण्ठदीक्षितस्य प्रसिद्धे श्लोकेपि ईदृगेव प्रयोगः ।'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अन्तर्भूतम्" = ''
"संज्ञा" = 'प्रगृह्यम्‌'
"प्रामुख्यम्" = '३'
"सूत्रम्" = ' ईदादीनां प्रगृह्यत्वे मणीवादीनां प्रतिषेधो वक्तव्यः।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = 'मणीवोष्ट्रस्य लम्बेते प्रियौ वत्सतरौ मम। दम्पतीव। जम्पतीव।'
"विवरणम्" = ''

[[data]]
"अन्तर्भूतम्" = 'अदस् सम्बुद्धौ मकारात् परः (*-ईत् |*-ऊत् | *-एत्)'
"संज्ञा" = 'प्रगृह्यम्‌'
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'अदसो मात् ।'
"उदाहरणम्" = 'अमी अत्र। अमी आसते। अमू अत्र।'
"अभावोदाहरणम्" = 'मातिति किम्? अमुके ऽत्र।'
"विवरणम्" = ''

[[data]]
"अन्तर्भूतम्" = 'सुपः स्थाने शे छन्दसि'
"संज्ञा" = 'प्रगृह्यम्‌'
"प्रामुख्यम्" = '१'
"सूत्रम्" = 'शे ।'
"उदाहरणम्" = 'अस्मे इन्द्राबृहस्पती। युष्मे इति। अस्मे इति। त्वे रायः। मे रायः। त्वे इति। मे इति।'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अन्तर्भूतम्" = 'एकाच् निपातः -आङ्'
"संज्ञा" = 'प्रगृह्यम्‌'
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'निपात एकाजनाङ् ।'
"उदाहरणम्" = 'अ अपेहि। इ इन्द्रं पश्य। उ उत्तिश्ठ। आ एवं नु मन्यसे। आ एवं किल तत्।'
"अभावोदाहरणम्" = '''
अनाङिति किम्? आ उदकान्तात्, ओदकान्तात्।
"प्राग्नये" इति। प्रशब्दो भवति निपातः, न त्वेकाच्।'''
"विवरणम्" = ''

[[data]]
"अन्तर्भूतम्" = '*ओत् निपातः'
"संज्ञा" = 'प्रगृह्यम्‌'
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'ओत् ।'
"उदाहरणम्" = 'नो इदानीम्। अथो इति। अहो अधुना।'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अन्तर्भूतम्" = 'सम्बुद्धौ ओत् + इति (न वेदे)'
"संज्ञा" = 'प्रगृह्यम्‌'
"प्रामुख्यम्" = '३'
"सूत्रम्" = 'सम्बुद्धौ शाकल्यस्येतावनार्षे ।'
"उदाहरणम्" = '(शाकल्यमते) वायो इति, (अन्येषां मते) वायविति। भानो इति, भानविति। अध्वर्यो इति, अध्वर्यविति॥'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अन्तर्भूतम्" = 'उ + इति (न वेदे)'
"संज्ञा" = 'प्रगृह्यम्‌'
"प्रामुख्यम्" = '१'
"सूत्रम्" = 'उञः ।'
"उदाहरणम्" = 'उ इति, विति।'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अन्तर्भूतम्" = 'उ + इति (न वेदे)'
"संज्ञा" = 'प्रगृह्यम्‌'
"प्रामुख्यम्" = '१'
"सूत्रम्" = 'ऊँ ।'
"उदाहरणम्" = 'उँं इति'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अन्तर्भूतम्" = 'ईत् | ऊत् सप्तम्यर्थे'
"संज्ञा" = 'प्रगृह्यम्‌'
"प्रामुख्यम्" = '२'
"सूत्रम्" = 'ईदूतौ च सप्तम्यर्थे ।'
"उदाहरणम्" = 'सोमो गौरी अधिश्रितः। मामकी तनू इति।'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''
