[[data]]
"पूर्वपदस्थितिः" = '1 शर, 2 वंश, 3 धूम, 4 अहि, 5 कपि 6 मणि, 7 मुनि, 8 शुचि, 9 हनु संज्ञायाम्'
"अन्यपदस्थितिः" = 'मतुप्'
"परिणामः" = 'दीर्घीकरणम्'
"अवधानावश्यकता" = ''
"विधिप्रकारः" = ''
"सूत्रम्" = 'शरादीनां च'
"समस्तपदम् उदाहरणम्" = 'शरावती'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

