[[data]]
"पूर्वपदस्थितिः" = ''
"विवक्षा" = ''
"संज्ञा २" = 'आम्रोडितम्'
"संज्ञा ३" = 'संज्ञाविधानम्'
"अवधानावश्यकता" = ''
"सूत्रम्" = 'तस्य परम् आम्रेडितम् सर्वस्य द्वे'
"समस्तपदम् उदाहरणम्" = 'चौर चौर इत्यस्मिन् द्वितीयं "चौर"'
"विवरणम्" = 'द्वितीयवारम् उक्तं पदम् आम्रोडितम् इति'

[[data]]
"पूर्वपदस्थितिः" = ''
"विवक्षा" = ''
"संज्ञा २" = ''
"संज्ञा ३" = 'स्वरविधानम्'
"अवधानावश्यकता" = ''
"सूत्रम्" = 'अनुदात्तं च सर्वस्य द्वे आम्रेडितम्'
"समस्तपदम् उदाहरणम्" = '''भुङ्क्ते भु॑ङ्क्ते'''
"विवरणम्" = 'अनुदात्तम्'

[[data]]
"पूर्वपदस्थितिः" = '*'
"विवक्षा" = 'पौनःपुन्ये'
"संज्ञा २" = ''
"संज्ञा ३" = 'द्विरुक्तिविधानम्'
"अवधानावश्यकता" = '५'
"सूत्रम्" = 'नित्यवीप्सयोः सर्वस्य द्वे'
"समस्तपदम् उदाहरणम्" = '''
पठति पठति। (नित्ये)
'''
"विवरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"विवक्षा" = 'वीप्सा'
"संज्ञा २" = ''
"संज्ञा ३" = 'द्विरुक्तिविधानम्'
"अवधानावश्यकता" = '५'
"सूत्रम्" = 'नित्यवीप्सयोः सर्वस्य द्वे'
"समस्तपदम् उदाहरणम्" = 'ग्रामो ग्रामो रमणीयः। (वीप्सा)'
"विवरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = 'परि'
"विवक्षा" = ''
"संज्ञा २" = ''
"संज्ञा ३" = 'द्विरुक्तिविधानम्'
"अवधानावश्यकता" = '२'
"सूत्रम्" = 'परेः वर्जने सर्वस्य द्वे'
"समस्तपदम् उदाहरणम्" = 'परि परि सज्जनेभ्यः वृष्टो मोघः।'
"विवरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = 'प्र सम् उप उत्'
"विवक्षा" = 'पादपूरणे'
"संज्ञा २" = ''
"संज्ञा ३" = 'द्विरुक्तिविधानम्'
"अवधानावश्यकता" = '३'
"सूत्रम्" = 'प्रसमुपोदः पादपूरणे सर्वस्य द्वे'
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = 'उपरि अधस्'
"विवक्षा" = 'सामीप्ये'
"संज्ञा २" = ''
"संज्ञा ३" = 'द्विरुक्तिविधानम्'
"अवधानावश्यकता" = '३'
"सूत्रम्" = 'उपर्यध्यधसः सामीप्ये सर्वस्य द्वे'
"समस्तपदम् उदाहरणम्" = 'उपर्य् उपरि ग्रामम्/ दुःखम्।'
"विवरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = 'वाक्यादेः आमन्त्रितः'
"विवक्षा" = 'असूया सम्मति कोप कुत्सन भर्त्सनेषु'
"संज्ञा २" = ''
"संज्ञा ३" = 'द्विरुक्तिविधानम्'
"अवधानावश्यकता" = '४'
"सूत्रम्" = 'वाक्यादेः आमन्त्रितस्या असूयासम्मतिकोपकुत्सनभर्त्सनेषु सर्वस्य द्वे'
"समस्तपदम् उदाहरणम्" = '''
असूया - माणवक' माणवक' अभिरूपक' अभिरूपक' - रिक्तं ते आभिरूप्यम्।
'''
"विवरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = 'एक'
"विवक्षा" = ''
"संज्ञा २" = 'बहुव्रीहिवत्'
"संज्ञा ३" = 'द्विरुक्तिविधानम्'
"अवधानावश्यकता" = '५'
"सूत्रम्" = 'एकं बहुव्रीहिवत् सर्वस्य द्वे'
"समस्तपदम् उदाहरणम्" = 'एकैकम् एकैकः एकैका'
"विवरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = '*'
"विवक्षा" = 'आबाधे\'
"संज्ञा २" = 'बहुव्रीहिवत्'
"संज्ञा ३" = 'द्विरुक्तिविधानम्'
"अवधानावश्यकता" = '५'
"सूत्रम्" = 'आबाधे च सर्वस्य द्वे बहुव्रीहिवत्'
"समस्तपदम् उदाहरणम्" = 'मृतमृता गौः! (शोकः)'
"विवरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = 'गुणम्'
"विवक्षा" = 'अपरिपूर्णगुणे = प्रकारे'
"संज्ञा २" = 'कर्मधारयवत्'
"संज्ञा ३" = 'द्विरुक्तिविधानम्'
"अवधानावश्यकता" = '५'
"सूत्रम्" = 'प्रकारे गुणवचनस्य सर्वस्य द्वे कर्मधारयवत्'
"समस्तपदम् उदाहरणम्" = 'मृदुमृदुः पटुपटुः (अन्तिमस्वर उदात्तः)'
"विवरणम्" = 'नात्र - अग्निर्माणवकः। गौर्वाहीकः।'

[[data]]
"पूर्वपदस्थितिः" = 'गुणम्'
"विवक्षा" = 'आनुपूर्व्ये'
"संज्ञा २" = 'कर्मधारयवत्'
"संज्ञा ३" = 'द्विरुक्तिविधानम्'
"अवधानावश्यकता" = '३'
"सूत्रम्" = 'आनुपूर्व्ये द्वे भवत इति वक्तव्यम्॥'
"समस्तपदम् उदाहरणम्" = 'मूलेमूले स्थूलाः। अग्रेऽग्रे सूक्ष्माः। ज्येष्ठंज्येष्ठं प्रवेशय॥'
"विवरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = '*'
"विवक्षा" = 'आनुपूर्व्ये'
"संज्ञा २" = 'कर्मधारयवत्'
"संज्ञा ३" = 'द्विरुक्तिविधानम्'
"अवधानावश्यकता" = '२'
"सूत्रम्" = 'स्वार्थेऽवधार्यमाणेऽनेकस्मिन् द्वे भवत इति वक्तव्यम्॥'
"समस्तपदम् उदाहरणम्" = 'अस्मात् कार्षापणादिह भवद्भ्यां माषंमाषं देहि।'
"विवरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = '*'
"विवक्षा" = 'चापले'
"संज्ञा २" = 'कर्मधारयवत्'
"संज्ञा ३" = 'द्विरुक्तिविधानम्'
"अवधानावश्यकता" = '२'
"सूत्रम्" = 'चापले द्वे भवत इति वक्तव्यम्॥'
"समस्तपदम् उदाहरणम्" = 'अहिरहिः, बुध्यस्वबुध्यस्व। अहिरहिरहिः, बुध्यस्वबुध्यस्वबुध्यस्व इति॥'
"विवरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = '*'
"विवक्षा" = 'आभीक्ष्ण्ये'
"संज्ञा २" = 'कर्मधारयवत्'
"संज्ञा ३" = 'द्विरुक्तिविधानम्'
"अवधानावश्यकता" = '२'
"सूत्रम्" = 'आभीक्ष्ण्ये द्वे भवत इति वक्तव्यम्॥ '
"समस्तपदम् उदाहरणम्" = 'भुक्त्वाभुक्त्वा व्रजति। भोजंभोजं व्रजति। '
"विवरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = '*डाच्'
"विवक्षा" = ''
"संज्ञा २" = 'कर्मधारयवत्'
"संज्ञा ३" = 'द्विरुक्तिविधानम्'
"अवधानावश्यकता" = '२'
"सूत्रम्" = 'डाचि द्वे भवत इति वक्तव्यम्॥'
"समस्तपदम् उदाहरणम्" = 'पटपटाकरोति। पटपटायते। '
"विवरणम्" = 'अव्यक्तानुकरणे डाजन्तस्य द्विर्वचनमिष्यते।'

[[data]]
"पूर्वपदस्थितिः" = 'पूर्व|प्रथम'
"विवक्षा" = 'अतिशये'
"संज्ञा २" = 'कर्मधारयवत्'
"संज्ञा ३" = 'द्विरुक्तिविधानम्'
"अवधानावश्यकता" = '२'
"सूत्रम्" = 'पूर्वप्रथमयोरर्थातिशयविवक्षायां द्वे भवत इति वक्तव्यम्॥'
"समस्तपदम् उदाहरणम्" = 'पूर्वंपूर्वं पुष्प्यन्ति। प्रथमंप्रथमं पच्यन्ते।'
"विवरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = '*डातर|*डातम'
"विवक्षा" = ''
"संज्ञा २" = 'कर्मधारयवत्'
"संज्ञा ३" = 'द्विरुक्तिविधानम्'
"अवधानावश्यकता" = '२'
"सूत्रम्" = 'डतरडतमयोः समसंप्रधारणयोः स्त्रीनिगदे भावे द्वे भवत इति वक्तव्यम्॥ स्त्रीनिगदाद् भावादन्यत्रापि हि दृश्यते॥'
"समस्तपदम् उदाहरणम्" = ' उभाविमावाढ्यौ। कतराकतरा अनयोराढ्यता। सर्व इम आढ्याः। कतमाकतमा एषामाढ्यता।'
"विवरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"विवक्षा" = 'परस्पर-क्रियायाम्'
"संज्ञा २" = 'कर्मधारयवत्'
"संज्ञा ३" = 'द्विरुक्तिविधानम्'
"अवधानावश्यकता" = '२'
"सूत्रम्" = ' कर्मव्यतिहारे सर्वनाम्नो द्वे भवत इति वक्तव्यं समासवच्च बहुलम्। यदा न समासवत् प्रथमैकवचनं तदा पूर्वपदस्य॥'
"समस्तपदम् उदाहरणम्" = 'न्योऽन्यमिमे ब्राह्मणा भोजयन्ति। इतरेतरं भोजयन्ति।'
"विवरणम्" = 'अव्यक्तानुकरणे डाजन्तस्य द्विर्वचनमिष्यते।'

[[data]]
"पूर्वपदस्थितिः" = '*'
"विवक्षा" = 'परस्पर-क्रियायाम्'
"संज्ञा २" = 'कर्मधारयवत्'
"संज्ञा ३" = 'द्विरुक्तिविधानम्'
"अवधानावश्यकता" = '२'
"सूत्रम्" = 'स्त्रीनपुंसकयोर् उत्तरपदस्य वाम्भावो वक्तव्यः॥'
"समस्तपदम् उदाहरणम्" = 'अन्योऽन्यामिमे ब्राह्मण्यौ भोजयतः। अन्योऽन्यं भोजयतः। इतरेतरां भोजयतः।'
"विवरणम्" = 'अव्यक्तानुकरणे डाजन्तस्य द्विर्वचनमिष्यते।'


[[data]]
"पूर्वपदस्थितिः" = 'प्रिय सुख'
"विवक्षा" = 'विकल्पेन अकष्टे'
"संज्ञा २" = 'कर्मधारयवत्'
"संज्ञा ३" = 'द्विरुक्तिविधानम्'
"अवधानावश्यकता" = '५'
"सूत्रम्" = 'अकृच्छ्रे प्रियसुखयोः अन्यतरस्याम् सर्वस्य द्वे कर्मधारयवत्'
"समस्तपदम् उदाहरणम्" = 'प्रियप्रियेण वदति/ प्रियेण वदति'
"विवरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = 'यथा'
"विवक्षा" = 'स्वे / आत्मीयतायाम्'
"संज्ञा २" = 'कर्मधारयवत्'
"संज्ञा ३" = 'द्विरुक्तिविधानम्'
"अवधानावश्यकता" = '२'
"सूत्रम्" = 'यथास्वे यथायथम् सर्वस्य द्वे कर्मधारयवत्'
"समस्तपदम् उदाहरणम्" = 'ज्ञातास् सर्वे यथायथम्'
"विवरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = 'द्वं'
"विवक्षा" = '''
रहस्य-मर्यादावचन-
व्युत्क्रमण-
यज्ञपात्रप्रयोग-
अभिव्यक्तिषु'''
"संज्ञा २" = 'द्वन्द्वम्'
"संज्ञा ३" = 'द्विरुक्तिविधानम्'
"अवधानावश्यकता" = '३'
"सूत्रम्" = 'द्वन्द्वं रहस्य-मर्यादा-वचन-व्युत्क्रमण-यज्ञ-पात्र-प्रयोगाभिव्यक्तिषु सर्वस्य द्वे कर्मधारयवत्'
"समस्तपदम् उदाहरणम्" = '''
द्वन्द्वं मन्त्रयन्ते (रहस्ये)।
'''
"विवरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"विवक्षा" = ''
"संज्ञा २" = ''
"संज्ञा ३" = ''
"अवधानावश्यकता" = ''
"सूत्रम्" = 'आम्रोडितं भर्त्सने'
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
