[[data]]
"विवक्षा/ पदयोगः" = 'विभागाश्रयः'
"परिणाम-संज्ञा १" = 'अपादानम्'
"परिणाम-संज्ञा २" = 'विभागाश्रयः'
"अवधानम्" = '५'
"सूत्रम्" = 'ध्रुवमपायेऽपादानम्'
"विवरणम्" = '''
ध्रुवम् अपादानम् अपाये कारके।
ध्रुवम् = निश्चलत्वयुक्तम् वियोगदृष्ट्या।'''
"उदाहरणम्" = '''
पत्त्रं वृक्षात् पतति।
उभयोर् अपि अनेन अपादानसंज्ञा शक्यम्।
परन्तु वृक्षः कर्तृसंज्ञां अन्ते प्राप्तिमर्हति परतमसूत्रात्।'''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'भयहेतुः भी-त्रा-अर्थानाम्।'
"परिणाम-संज्ञा १" = 'अपादानम्'
"परिणाम-संज्ञा २" = 'भीत्रादिः'
"अवधानम्" = '४'
"सूत्रम्" = 'भीत्रार्थानां भयहेतुः (अपादानं कारके)'
"विवरणम्" = ''
"उदाहरणम्" = '''
चोरात् बिभेति।
चोरात् रक्षति।'''
"अयोग्यता" = 'अरण्ये बिभेति।'

[[data]]
"विवक्षा/ पदयोगः" = 'पराजये असोढः।'
"परिणाम-संज्ञा १" = 'अपादानम्'
"परिणाम-संज्ञा २" = 'भीत्रादिः'
"अवधानम्" = '३'
"सूत्रम्" = 'पराजेः असोढः (अपादानं कारके)'
"विवरणम्" = '''
परा-जि-धातोः योगे यः असह्यः अपादानम्।
पराजयः = ग्लायते/ श्रान्तः भवति इत्यर्थे।'''
"उदाहरणम्" = '''
अध्ययनात् पराजयते।
(अध्ययनम् असह्यम्।)'''
"अयोग्यता" = '''
शतॄन् पराजयते।
पराजि=जये।'''

[[data]]
"विवक्षा/ पदयोगः" = 'वारणार्थानाम्  वार्यमाणप्रवृत्त्या ईप्सितः।'
"परिणाम-संज्ञा १" = 'अपादानम्'
"परिणाम-संज्ञा २" = 'भीत्रादिः'
"अवधानम्" = '४'
"सूत्रम्" = 'वारणार्थानाम् ईप्सितः (अपादानं कारके)'
"विवरणम्" = 'वारणम् - प्रवृत्ति-विघातः/रोधः।'
"उदाहरणम्" = '''
माता बालकं अग्नेर् वारयति।
(प्रवृत्त्या ईप्सितः अग्निः।)'''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'अन्तर्धौ येन अदर्शनम् इष्टम्।'
"परिणाम-संज्ञा १" = 'अपादानम्'
"परिणाम-संज्ञा २" = 'भीत्रादिः'
"अवधानम्" = '३'
"सूत्रम्" = 'अन्तर्धौ  येन अदर्शनमिच्छति (अपादानं कारके)'
"विवरणम्" = 'अन्तर्धिः = आत्मगोपनम्।'
"उदाहरणम्" = 'मातुः कृष्णः निलीयते।'
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'अध्यापकः विद्यास्वीकारे।'
"परिणाम-संज्ञा १" = 'अपादानम्'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '४'
"सूत्रम्" = 'आख्याता उपयोगे (अपादानं कारके)'
"विवरणम्" = ''
"उदाहरणम्" = 'अध्यापकात् अधीते।'
"अयोग्यता" = 'नटस्य गाथां श्रुणोति।'

[[data]]
"विवक्षा/ पदयोगः" = 'जननकर्तुः '
"परिणाम-संज्ञा १" = 'अपादानम्'
"परिणाम-संज्ञा २" = 'विभागाश्रयः'
"अवधानम्" = '१'
"सूत्रम्" = 'जनिकर्तुः प्रकृतिः (अपादानं कारके)'
"विवरणम्" = 'ध्रुवमपायेऽपादानं॥ इत्येव पर्याप्तम् स्यात्।'
"उदाहरणम्" = 'दशरथात् रामः जातः।'
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'भूकर्तुः'
"परिणाम-संज्ञा १" = 'अपादानम्'
"परिणाम-संज्ञा २" = 'विभागाश्रयः'
"अवधानम्" = '१'
"सूत्रम्" = 'भुवः प्रभवः (अपादानं कारके)'
"विवरणम्" = 'ध्रुवमपायेऽपादानं॥ इत्येव पर्याप्तम् स्यात्।'
"उदाहरणम्" = 'हिमवतः गङ्गा प्रवहति।'
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = '''
दाने कर्मसंज्ञकवस्तुना / क्रियया
संबद्धुम् इष्यमानम्'''
"परिणाम-संज्ञा १" = 'संप्रदानम्'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '५'
"सूत्रम्" = 'कर्मणा यम् अभिप्रैति सः सम्प्रदानम् कारके।'
"विवरणम्" = ''
"उदाहरणम्" = '''
रामाय पुष्पं ददाति।
पत्ये शेते।
'''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = '''
(अकर्मक)क्रियया संबद्धुम्
इष्यमानम्'''
"परिणाम-संज्ञा १" = 'संप्रदानम्'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '१'
"सूत्रम्" = 'क्रियया यम् अभिप्रैति(वा)॥'
"विवरणम्" = '''
कर्म नाम न केवलम् कर्मपदम्, क्रिया अपि।
अतः एतत् नावश्यकम् इति पतञ्जलिः।'''
"उदाहरणम्" = '''
पत्ये शेते।
युद्धाय सन्नह्यते।'''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'रुच्यर्थानाम् प्रियामाणः।'
"परिणाम-संज्ञा १" = 'संप्रदानम्'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '४'
"सूत्रम्" = 'रुच्यर्थानां प्रीयमाणः कारके सम्प्रदानम्'
"विवरणम्" = ''
"उदाहरणम्" = '''
कृष्णाय गोपयो रोचन्ते।
कृष्णाय गोपिभिः रुच्यते।'''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'श्लाघ्-ह्नुङ्-स्था-शप-योगे ज्ञीप्स्यमानः।'
"परिणाम-संज्ञा १" = 'संप्रदानम्'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '२'
"सूत्रम्" = 'श्लाघह्नुङ्स्थाशपां ज्ञीप्स्यमानः कारके सम्प्रदानम्'
"विवरणम्" = ''
"उदाहरणम्" = 'देवदत्ताय श्लाघते मार्गे। देवदत्तं श्लाघमानस्ताम् श्लाघां तम् एव ज्ञपयितुम् इच्छति इत्यर्थः। एवम् देवदत्ताय ह्नुते। यज्ञदत्ताय ह्नुते। देवदत्ताय तिष्ठते। यज्ञदत्ताय तिष्ठते। देवदत्ताय शपते। यज्ञदत्ताय शपते।'
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'धारि-धातुना सह उत्तम-ऋणस्वीकर्ता।'
"परिणाम-संज्ञा १" = 'संप्रदानम्'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '१'
"सूत्रम्" = 'धारेः उत्तमर्णः कारके सम्प्रदानम्'
"विवरणम्" = 'उत्तमर्णः = ऋणदाता।'
"उदाहरणम्" = '''
भक्ताय मोक्षम् धारयति हरिः।
रामाय शतं नाणकानि धारयति।'''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'स्पृहेः ईप्सितः।'
"परिणाम-संज्ञा १" = 'संप्रदानम्'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '२'
"सूत्रम्" = 'स्पृहेः ईप्सितः कारके सम्प्रदानम्'
"विवरणम्" = ''
"उदाहरणम्" = 'बालः पुष्पेभ्यः स्पृहयति'
"अयोग्यता" = 'अतीच्छायां - बाला पुष्पाणि स्पृहयति।'

[[data]]
"विवक्षा/ पदयोगः" = '''
क्रुध-द्रुह-ईर्ष्य-असूय-अर्थानाम्
यं प्रति कोपः।
(उपसर्ग+कृध/द्रुह्)-योगे अपवादः।'''
"परिणाम-संज्ञा १" = 'संप्रदानम्'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '४'
"सूत्रम्" = 'क्रुधद्रुहेर्ष्यासूयार्थानां यं प्रति कोपः कारके सम्प्रदानम्।'
"विवरणम्" = ''
"उदाहरणम्" = 'भार्याम् ईर्ष्यति यवनाय।'
"अयोग्यता" = 'क्रोधाभावे।'

[[data]]
"विवक्षा/ पदयोगः" = '(उपसर्ग+कृध/द्रुह्)-योगे यं प्रति कोपः।'
"परिणाम-संज्ञा १" = 'कर्म'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '२'
"सूत्रम्" = 'क्रुधद्रुहोः उपसृष्टयोः कर्म कारके यं प्रति कोपः'
"विवरणम्" = ''
"उदाहरणम्" = 'रामं रावणः अधिकृध्यति।'
"अयोग्यता" = 'रामाय रावणः‌ कृध्यति।'

[[data]]
"विवक्षा/ पदयोगः" = 'राध्-ईक्ष्-योः विप्रश्ननार्थे।'
"परिणाम-संज्ञा १" = 'संप्रदानम्'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '३'
"सूत्रम्" = 'राधीक्ष्योः यस्य विप्रश्नः कारके सम्प्रदानम्'
"विवरणम्" = 'विप्रश्नः = विविधप्रश्नः।'
"उदाहरणम्" = 'वाल्मीकिः नारदाय ईक्षते।'
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'प्रति/आङ्+श्रु योगे पूर्वप्रार्थकः।'
"परिणाम-संज्ञा १" = 'संप्रदानम्'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '३'
"सूत्रम्" = 'प्रत्याङ्भ्यां श्रुवः पूर्वस्य कर्ता कारके सम्प्रदानम्'
"विवरणम्" = 'प्रतिश्रु = प्रतिज्ञा।'
"उदाहरणम्" = '''
विप्रेण "मे गां देहि" इति।
विप्राय गां प्रतिश्रुणोति राजा।'''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = '‌अनु/प्रति+गृणाति योगे पूर्वकार्यकर्ता'
"परिणाम-संज्ञा १" = 'संप्रदानम्'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '२'
"सूत्रम्" = 'अनुप्रतिगृणः च कारके सम्प्रदानम् पूर्वस्य कर्ता'
"विवरणम्" = ''
"उदाहरणम्" = '''
अध्वर्युः होत्रे अनुगृणाति।
विप्रः उपायं सूचयति।
राजा अनुगृणाति।'''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'यस्य उपयोगानन्तरमेव क्रियाफलजननम्'
"परिणाम-संज्ञा १" = 'करणम्'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '५'
"सूत्रम्" = 'साधकतमं करणम्'
"विवरणम्" = ''
"उदाहरणम्" = '''
अहं चमसेन खादामि।
अहं विस्तरेण बोधामि। (विस्तारं विना बोधनं न सिध्यति।)'''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = ''
"परिणाम-संज्ञा १" = 'करणम्'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '२'
"सूत्रम्" = 'कर्मणः करणसंज्ञा वक्तव्या, संप्रदानस्य च कर्मसंज्ञा (वा)'
"विवरणम्" = ''
"उदाहरणम्" = '''
पशुं रुद्राय ददाति।
पशुना रुद्रं यजते।'''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'दिवतेः साधकतमम् कर्म वा करणम्।'
"परिणाम-संज्ञा १" = 'कर्म'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = ''
"सूत्रम्" = '[साधकतमं] दिवः कर्म च  करणम्।'
"विवरणम्" = 'करणकारके विवृतम्।'
"उदाहरणम्" = ''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'दिवतेः साधकतमम् कर्म वा करणम्।'
"परिणाम-संज्ञा १" = 'करणम्'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '२'
"सूत्रम्" = '[साधकतमं] दिवः कर्म च  करणम्।'
"विवरणम्" = ''
"उदाहरणम्" = 'अक्षैः दीव्यति। अक्षान् दिव्यति।'
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = ''
"परिणाम-संज्ञा १" = 'संप्रदानम्'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '२'
"सूत्रम्" = '[साधकतमं] परिक्रयणे संप्रदानमन्यतरस्याम् [करणम्]।'
"विवरणम्" = '''
परिक्रयणम् = नियतकालभृत्यस्वीकारः।
अन्यतरस्याम् = वा।'''
"उदाहरणम्" = 'स्वामी सेवकम् त्रिमासकालं परिक्रीणाति दशनाण्येभ्यः/ दशनाण्येन।'
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'कर्तुः वा कर्मणः आधारः एकदेशे'
"परिणाम-संज्ञा १" = 'अधिकरणम्'
"परिणाम-संज्ञा २" = 'आधारः औपश्लेषिकः'
"अवधानम्" = '५'
"सूत्रम्" = 'आधारोऽधिकरणम्'
"विवरणम्" = '''
कर्तृकर्मभ्यां तन्निष्टक्रियायाः आधारः।
सम्बन्धः संयोगः।'''
"उदाहरणम्" = '''
रामो ग्रामे अटति।
[अधारतमः किमर्थम् न? ]
गङ्गायां उटजम्।'''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'कर्तुः वा कर्मणः आधारः विषये'
"परिणाम-संज्ञा १" = 'अधिकरणम्'
"परिणाम-संज्ञा २" = 'आधारः वैषयिकः'
"अवधानम्" = '५'
"सूत्रम्" = 'आधारोऽधिकरणम्'
"विवरणम्" = ''
"उदाहरणम्" = '''
पठने आसक्तिः।
पक्षी आकाशे डयते।'''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'कर्तुः वा कर्मणः आधारः सर्वत्र'
"परिणाम-संज्ञा १" = 'अधिकरणम्'
"परिणाम-संज्ञा २" = 'आधारः अभिव्यापकः'
"अवधानम्" = '५'
"सूत्रम्" = 'आधारोऽधिकरणम्'
"विवरणम्" = 'संबन्धः समवायः।'
"उदाहरणम्" = 'तिलेषु तैलम्'
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'अधि+शीङ्|स्था|आस्'
"परिणाम-संज्ञा १" = 'कर्म'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '४'
"सूत्रम्" = '[आधारः] अधिशीङ्स्थाऽऽसां कर्म ।'
"विवरणम्" = ''
"उदाहरणम्" = 'रामो आसनम् अधि-आस्ते।'
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'अभिनि+विश् (विकल्पेन)'
"परिणाम-संज्ञा १" = 'अधिकरणम्'
"परिणाम-संज्ञा २" = 'आधारः'
"अवधानम्" = '२'
"सूत्रम्" = '[आधारः] अभिनिविशश्च [अन्यतरस्याम् कर्म]।'
"विवरणम्" = 'कर्मकारके विवृतम्।'
"उदाहरणम्" = ''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'अभिनि+विश् (विकल्पेन)'
"परिणाम-संज्ञा १" = 'कर्म'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '२'
"सूत्रम्" = '[आधारः] अभिनिविशश्च [अन्यतरस्याम् कर्म]।'
"विवरणम्" = ''
"उदाहरणम्" = '''
अभिनिविशते सन्मार्गम्।
अभिनिवेशः पापे/ पापम्।'''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'उपान्वध्याङ्+वस्'
"परिणाम-संज्ञा १" = 'कर्म'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = ''
"सूत्रम्" = '[आधारः] उपान्वध्याङ्वसः [कर्म]।'
"विवरणम्" = ''
"उदाहरणम्" = 'वैकुण्टम् उपवसति गरुत्मन्।'
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'क्रियाफलेन संबद्धुं ईप्सिततमम्'
"परिणाम-संज्ञा १" = 'कर्म'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '५'
"सूत्रम्" = 'कर्तुरीप्सिततमं कर्म'
"विवरणम्" = ''
"उदाहरणम्" = '''
जनः ग्रामं गच्छति। पयसा ओदनम् भुङ्क्ते।
माषेषु अश्वं बध्नाति। जनः विषं भुङ्क्ते।'''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'ईप्सिततमेन वस्तुना युक्तम्।'
"परिणाम-संज्ञा १" = 'कर्म'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '४'
"सूत्रम्" = 'तथायुक्तं चानीप्सितम् [कर्म]'
"विवरणम्" = ''
"उदाहरणम्" = '''
जनः अन्नं खादन् विषं भुङ्क्ते। (अनिच्छन्नपि)
ग्रामम् गच्छन् तृणं स्पृषति।'''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = '''
द्विकर्मकधातुभिस् सह प्रयुक्तम् -
दोग्धि याचते पचति दण्डयति पृच्छति चिनोति
ब्रूते शास्ति जयति मथ्नाति मुष्णाति नयति हरति कर्षति वहति । तत्समानार्थकाश्च। '''
"परिणाम-संज्ञा १" = 'कर्म'
"परिणाम-संज्ञा २" = 'गौणकर्म'
"अवधानम्" = '५'
"सूत्रम्" = '''
अकथितञ्च॥
दुह्याच्पच्दण्ड्रुधिप्रच्छिचिब्रूशासुजिमथ्मुषाम् ।
कर्मयुक् स्यादकथितं तथा स्यान्नीहृकृष्वहाम् ॥ '''
"विवरणम्" = '''
दुह्-याच्-पच्-दण्ड्-रुधि-प्रच्छि-चि-ब्रू-शासु-जि-मथ्-मुष्-नी--हृ-कृष्-वह्। एते हि चितार्थेषु, तत्समानार्थकाश्च द्विकर्मकधातवो, नान्ये।
एतेषु अपादानादाव् अविवक्षिते गौणकर्मसंज्ञा दीयते।
दुहादीनां द्वादशानां तथा नीप्रभृतीनां चतुर्णां कर्मणा यद्युज्यते तदेवाकथितं कर्मेति परिगणनं कर्तव्यमित्यर्थः ।
यस्य पदस्य अन्येन कारकेण अपि विवक्षा कर्तुं शक्यते, तत् गौणकर्म ।
'''
"उदाहरणम्" = '''
दुहि गां दोग्धि पयः। याचि पौरवं गां याचते। रुधि गामवरुणद्धि व्रजम्। चिञ् वृक्षमविचिनोति फलानि। ब्रुवि माणवकं धर्मं ब्रूते। शासि माणवकं धर्मम् अनुशास्ति।
प्रच्छि -- माणवकं पन्थानं पृच्छति ।। "नैतदस्ति । कथिताऽत्र पूर्वाऽपादानसंज्ञा।" इति चेन्न।। न प्रश्नादेवाऽपायो भवति । पृष्टोऽसौ यद्याचष्टे ततोऽपायेन युज्यते ।
भिक्षि-पौरवं गां भिक्षते ।। "नैतदस्ति । कथिताऽत्र पूर्वाऽपादानसंज्ञा।" इति चेन्न ।। न भिक्षणादेवाऽपायो भवति । भिक्षितोऽसौ यदि ददाति ततोऽपायेन युज्यते । '''
"अयोग्यता" = '"पाणिना कांस्यपात्र्यां गां दोग्धि पयः। " पाण्यादिकम् अप्युपयोगनिमित्तं, तस्य कस्मान् न भवति? न एतदस्ति। विहिता हि तत्र करणादिसंज्ञा।'

[[data]]
"विवक्षा/ पदयोगः" = 'अकर्मकधातुभिर्योगे देशः कालो भावो गन्तव्योऽध्वा'
"परिणाम-संज्ञा १" = 'कर्म'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '५'
"सूत्रम्" = 'अकर्मकधातुभिर्योगे देशः कालो भावो गन्तव्योऽध्वा च कर्मसंज्ञक इति वाच्यम् '
"विवरणम्" = ''
"उदाहरणम्" = 'कुरून् स्वपिति । मासमास्ते । गोदोहमास्ते । क्रोशमास्ते ॥ '
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = '''
प्रयोज्यकर्ता
गति-बुद्धि-भक्षण-जल्पन-अर्थकेषु,
[-नीवह् अद् खाद् भक्ष्-अहिंसायां
शब्द्]
'''
"परिणाम-संज्ञा १" = 'कर्म'
"परिणाम-संज्ञा २" = 'प्रधानकर्म'
"अवधानम्" = '५'
"सूत्रम्" = '''
गतिबुद्धिप्रत्यवसानार्थशब्दकर्माकर्मकाणाम् अणि कर्ता स णौ [कर्म]।
नीवहेर्न। अदिखाद्योर् न। भक्षेर् अहिंसार्थस्य न। शब्दायतेर् न।'''
"विवरणम्" = ''
"उदाहरणम्" = '''
सः रामं बोधयति वेदान्।
'''
"अयोग्यता" = '"पिता‌ पत्न्या पाचयति" इत्येव साधुः - पत्नीम् पाचयति इति न।'

[[data]]
"विवक्षा/ पदयोगः" = '''
प्रयोज्यकर्तुः अकर्मकानाम्
निषेधाभावे'''
"परिणाम-संज्ञा १" = 'कर्म'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '५'
"सूत्रम्" = 'गतिबुद्धिप्रत्यवसानार्थशब्दकर्माकर्मकाणाम् अणि कर्ता स णौ [कर्म]'
"विवरणम्" = ''
"उदाहरणम्" = ''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'प्रयोज्यकर्तुः जल्प्-विलप्-आभाष्-दृश् योगे प्रयोज्यकर्ता'
"परिणाम-संज्ञा १" = 'कर्म'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '४'
"सूत्रम्" = '''
जल्पप्रभृतीनामुपसङ्ख्यानम्।
दृशेश्च।'''
"विवरणम्" = 'जल्प्, विलप्, आभाष्, दृश्'
"उदाहरणम्" = 'सीता रामं हिरण्यमृगं दर्शयति।'
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = '''
हृ-कृ-णिजन्त-योगे प्रयोज्यकर्तुः कर्म वा।
अभिवादि-दृश् इत्येतयोर् योगे वा।'''
"परिणाम-संज्ञा १" = 'कर्म'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '४'
"सूत्रम्" = '''
हृक्रोर् अन्यतरस्याम्।
अभिवादि-दृशोर् आत्मनेपदे वा।'''
"विवरणम्" = ''
"उदाहरणम्" = '''
स्वामी रामं/ रामेण कार्यं कारयति।
पिता पुत्रेण/ पुत्रं फलं हरयति।
अभिवादयते देवं भक्तं/ भक्तेन गुरुः।'''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = ''
"परिणाम-संज्ञा १" = ''
"परिणाम-संज्ञा २" = ''
"अवधानम्" = ''
"सूत्रम्" = ''
"विवरणम्" = ''
"उदाहरणम्" = ''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'अकर्मके देशः कालो भावो इत्यादिभ्यः'
"परिणाम-संज्ञा १" = 'कर्म'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '४'
"सूत्रम्" = 'अकर्मकधातुभिर् योगे देशः कालः भावः गन्तव्यो ऽध्वा च कर्मसंज्ञकः (वा??)'
"विवरणम्" = ''
"उदाहरणम्" = '''
जनः दिनम् तिष्ठति।
सः गोदोहं  (गोदोहनकालं) तिष्ठति।
सः क्रोशम् उड्डयते।'''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = ''
"परिणाम-संज्ञा १" = 'कर्म'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '२'
"सूत्रम्" = 'कर्मणः करणसंज्ञा वक्तव्या, संप्रदानस्य च कर्मसंज्ञा (वा)'
"विवरणम्" = ''
"उदाहरणम्" = '''
पशुं रुद्राय ददाति।
पशुना रुद्रं यजते।'''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'धातु-व्यापाराश्रयः'
"परिणाम-संज्ञा १" = 'कर्ता'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '५'
"सूत्रम्" = 'स्वतन्त्रः कर्ता'
"विवरणम्" = ''
"उदाहरणम्" = '''
सः चपेटां ददाति.
अत्र संयोगफलं चपेटायाम् आश्रितम्
'''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'प्रयोज्यकर्ता'
"परिणाम-संज्ञा १" = 'कर्ता'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '३'
"सूत्रम्" = ''
"विवरणम्" = '''
चितधातुषु गौणकर्मसंज्ञकः।
कर्मसंज्ञायां विवृतम्।
अन्यत्र कर्तृकरणयोस् तृतीया इत्यादि उपयोक्तव्यम्।'''
"उदाहरणम्" = '''
पिता बालम् ग्रामम् गमयति। इत्यस्मिन् बालः।
पिता रामेण अन्नम् अदयति।'''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'प्रयोजकः'
"परिणाम-संज्ञा १" = 'कर्ता'
"परिणाम-संज्ञा २" = 'हेतुः'
"अवधानम्" = ''
"सूत्रम्" = 'तत्प्रयोजको हेतुश्च।'
"विवरणम्" = 'प्रयोजकः = हेतुसंज्ञकः'
"उदाहरणम्" = 'पिता बालम् गमयति। इत्यस्मिन् पिता'
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = ''
"परिणाम-संज्ञा १" = ''
"परिणाम-संज्ञा २" = ''
"अवधानम्" = ''
"सूत्रम्" = ''
"विवरणम्" = ''
"उदाहरणम्" = ''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = ''
"परिणाम-संज्ञा १" = ''
"परिणाम-संज्ञा २" = ''
"अवधानम्" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"विवरणम्" = ''
"उदाहरणम्" = ''
"अयोग्यता" = ''

[[data]]
"विवक्षा/ पदयोगः" = 'क्रियाविशेषणम्'
"परिणाम-संज्ञा १" = 'कर्म'
"परिणाम-संज्ञा २" = ''
"अवधानम्" = '५'
"सूत्रम्" = '''
अव्ययीभावः।
क्रियाविशेषणानां कर्मत्वं नपुंसकत्वमेकवचनान्तत्वं चेष्यते। (वा)'''
"विवरणम्" = ''
"उदाहरणम्" = 'रामः शीघ्रं गच्छति।'
"अयोग्यता" = ''
