[[data]]
"गणः" = ''
"प्रयोग-विषयः" = 'उपलक्षणम्'
"प्रामुख्यम्" = '४'
"असाधुत्व-उदाहरणम्" = ''
"साधुत्व-उदाहरणम्" = 'रघूणां कथां वक्ष्ये। इति कालिदासः।'

[[data]]
"गणः" = 'उद्भूतावयव-समुदाये'
"प्रयोग-विषयः" = 'सर्व'
"प्रामुख्यम्" = ''
"असाधुत्व-उदाहरणम्" = ''
"साधुत्व-उदाहरणम्" = 'सर्वे जनाः'

[[data]]
"गणः" = 'अनुद्भूतावयव-समुदाये'
"प्रयोग-विषयः" = 'सर्व'
"प्रामुख्यम्" = ''
"असाधुत्व-उदाहरणम्" = ''
"साधुत्व-उदाहरणम्" = 'सर्वः खादितवान्'

[[data]]
"गणः" = 'विशेष-विशेष्य-भावः'
"प्रयोग-विषयः" = 'द्विरुक्ति-दोषः'
"प्रामुख्यम्" = ''
"असाधुत्व-उदाहरणम्" = 'मह्यं पात्रं भाजनम् आनय।'
"साधुत्व-उदाहरणम्" = ''
