[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"प्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'भस्य ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'पाद'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'पत्'
"प्रासिद्ध्यम्" = '३'
"प्रकारः" = 'पादः पादादेशः'
"विधिः" = ''
"सूत्रम्" = 'पादः पत् ।'
"प्रभावोदाहरणम्" = 'द्विपाद + ङे → द्विपदे'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = '*वस्'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'सम्प्रसारणम्'
"प्रासिद्ध्यम्" = ''
"प्रकारः" = 'सम्प्रसारणम्'
"विधिः" = ''
"सूत्रम्" = 'वसोः सम्प्रसारणम् ।'
"प्रभावोदाहरणम्" = 'विद्वस् + आम् → विदुषाम्'
"अभावोदाहरणम्" = 'चन्द्रमसाम्'
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'वाह्'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ऊठ्'
"प्रासिद्ध्यम्" = '२'
"प्रकारः" = 'सम्प्रसारणम्'
"विधिः" = ''
"सूत्रम्" = 'वाह ऊठ् ।'
"प्रभावोदाहरणम्" = 'प्रष्ठौहः, प्रष्ठौहा, प्रष्ठौहे, दित्यौहः, दित्यौहा, दित्यौहे ॥'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'श्व युवन् मघवन्'
"प्रत्ययः/ विवक्षा" = 'अतद्धिते'
"परिणामः" = ''
"प्रासिद्ध्यम्" = '४'
"प्रकारः" = 'सम्प्रसारणम्'
"विधिः" = ''
"सूत्रम्" = 'श्वयुवमघोनामतद्धिते ।'
"प्रभावोदाहरणम्" = '''
शुनः, शुना, शुने, यूनः, यूना, यूने, मघोनः, मघोना, मघोने ॥ मघवन् → मघोनः'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = '*अन् (अपवादा उक्ताः)'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अत्-लोपः'
"प्रासिद्ध्यम्" = '४'
"प्रकारः" = 'अङ्गलोपः'
"विधिः" = ''
"सूत्रम्" = 'अल्लोपोऽनः ।'
"प्रभावोदाहरणम्" = 'राजन् + ङस् → राज्ञः, राज्ञः पश्य, राज्ञा, राज्ञे, तक्ष्णः पश्य, तक्ष्णा and तक्ष्णे'
"अभावोदाहरणम्" = 'राजकीयम्'
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'ष्+अन् | हन् | धृतराजन्'
"प्रत्ययः/ विवक्षा" = 'अण्'
"परिणामः" = 'अत्-लोपः'
"प्रासिद्ध्यम्" = '३'
"प्रकारः" = 'अङ्गलोपः'
"विधिः" = ''
"सूत्रम्" = '''
षपूर्वहन्धृतराज्ञामणि ।
(अन्)'''
"प्रभावोदाहरणम्" = 'उक्षन् → औक्ष्णः'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = '*अन्'
"प्रत्ययः/ विवक्षा" = 'ङि | शी'
"परिणामः" = 'अत्-लोपः'
"प्रासिद्ध्यम्" = '३'
"प्रकारः" = 'अङ्गलोपः'
"विधिः" = 'आदेशः विकल्पेन'
"सूत्रम्" = 'विभाषा ङिश्योः ।'
"प्रभावोदाहरणम्" = 'सामन् + ङि → साम्नि सामनि'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'संयोगे (व्|म्) + अन्'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = '- अत्-लोपः'
"प्रासिद्ध्यम्" = '३'
"प्रकारः" = 'अङ्गलोपः'
"विधिः" = ''
"सूत्रम्" = 'न संयोगाद्वमन्तात्‌ ।'
"प्रभावोदाहरणम्" = 'पर्वणः'
"अभावोदाहरणम्" = 'दीव्नः'
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'अञ्च्'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अत्-लोपः'
"प्रासिद्ध्यम्" = '२'
"प्रकारः" = 'अङ्गलोपः'
"विधिः" = ''
"सूत्रम्" = 'अचः ।'
"प्रभावोदाहरणम्" = 'दधि + अच् + शस् → दधिच् → दधीच्(?)'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'उत् + अञ्च्'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ईत्'
"प्रासिद्ध्यम्" = '२'
"प्रकारः" = 'अङ्गलोपः'
"विधिः" = ''
"सूत्रम्" = 'उद ईत्‌ ।'
"प्रभावोदाहरणम्" = 'उत् + अच् → उदीच्'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'धातु + च्वि| विज् | विड्'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = '५'
"प्रकारः" = 'अङ्गलोपः'
"विधिः" = ''
"सूत्रम्" = 'आतो धातोः ।'
"प्रभावोदाहरणम्" = 'जलपा + शस् → जलपः'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = '१'
"प्रकारः" = 'अङ्गलोपः'
"विधिः" = ''
"सूत्रम्" = 'मन्त्रेष्वाङ्यादेरात्मनः ।'
"प्रभावोदाहरणम्" = 'त्मना देवेभ्यः, त्मना सोमेषु ॥'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'विंशति'
"प्रत्ययः/ विवक्षा" = 'डित्'
"परिणामः" = 'ति-लोपः'
"प्रासिद्ध्यम्" = '२'
"प्रकारः" = 'अङ्गलोपः'
"विधिः" = ''
"सूत्रम्" = 'ति विंशतेर्डिति ।'
"प्रभावोदाहरणम्" = 'विंशं शतम्। विंशकः = विंशत्या क्रीतः। '
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'डित्'
"परिणामः" = 'टेः लोपः'
"प्रासिद्ध्यम्" = '५'
"प्रकारः" = 'टेर् लोपः'
"विधिः" = ''
"सूत्रम्" = 'टेः ।'
"प्रभावोदाहरणम्" = 'त्रिंशता क्रीतः → ड्वुन् = त्रिंशकः'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = '''
*न्
-(अहन् | अन्-अपवादाः| इन्-अपवादाः)'''
"प्रत्ययः/ विवक्षा" = 'तद्धितम्'
"परिणामः" = 'लोपः'
"प्रासिद्ध्यम्" = '५'
"प्रकारः" = 'टेर् लोपः'
"विधिः" = ''
"सूत्रम्" = 'नस्तद्धिते ।'
"प्रभावोदाहरणम्" = 'आग्निशर्म्मिः, औडुलोमिः, सारलोमिः'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'अहन्'
"प्रत्ययः/ विवक्षा" = 'ट|ख'
"परिणामः" = ''
"प्रासिद्ध्यम्" = '२'
"प्रकारः" = 'टेर् लोपः'
"विधिः" = ''
"सूत्रम्" = 'अह्नष्टखोरेव ।'
"प्रभावोदाहरणम्" = 'द्वे अहनी समाहूते = द्व्यहः, त्र्यहः'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = '*उ'
"प्रत्ययः/ विवक्षा" = 'तद्धितम् - ढ'
"परिणामः" = 'गुणः'
"प्रासिद्ध्यम्" = '४'
"प्रकारः" = 'उकारान्तस्य'
"विधिः" = ''
"सूत्रम्" = 'ओर्गुणः ।'
"प्रभावोदाहरणम्" = 'बभ्रु + यञ् → बाभ्रो + यञ् → बाभ्रव् + य [वान्तो यि प्रत्यये]'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = '-कद्रु'
"प्रत्ययः/ विवक्षा" = 'ढ'
"परिणामः" = 'लोपः'
"प्रासिद्ध्यम्" = '३'
"प्रकारः" = 'उकारान्तस्य'
"विधिः" = ''
"सूत्रम्" = 'ढे लोपोऽकद्र्वाः ।'
"प्रभावोदाहरणम्" = 'कामण्डलेयः। शैतवाहेयः। जांवेयः। माद्रबाहेयः। '
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'अ|इ'
"प्रत्ययः/ विवक्षा" = 'ई-आदिः | तद्धितः'
"परिणामः" = 'लोपः'
"प्रासिद्ध्यम्" = '५'
"प्रकारः" = 'इवर्णान्तस्य'
"विधिः" = ''
"सूत्रम्" = 'यस्येति च ।'
"प्रभावोदाहरणम्" = 'दाक्षि, प्लाक्षि, सखि + ई →दाक्षी, प्लाक्षी, सखी '
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'सूर्य तिष्य अगस्त्य मत्स्य'
"प्रत्ययः/ विवक्षा" = 'ई-आदिः | तद्धितः'
"परिणामः" = 'य्-लोपः'
"प्रासिद्ध्यम्" = '२'
"प्रकारः" = 'यलोपः'
"विधिः" = ''
"सूत्रम्" = 'सूर्यतिष्यागस्त्यमत्स्यानां य उपधायाः ।'
"प्रभावोदाहरणम्" = 'सूर्येणैकदिक् सौरी बलाका। '
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'हल्+(य् तद्धिते) +?'
"प्रत्ययः/ विवक्षा" = 'ई-आदिः'
"परिणामः" = 'य्-लोपः'
"प्रासिद्ध्यम्" = '३'
"प्रकारः" = 'यलोपः'
"विधिः" = ''
"सूत्रम्" = 'हलस्तद्धितस्य ।'
"प्रभावोदाहरणम्" = 'गार्ग्य + ङीप् → गार्गी'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'हल्+ आपत्य-यकारः'
"प्रत्ययः/ विवक्षा" = 'अनात् तद्धितः'
"परिणामः" = 'य्-लोपः'
"प्रासिद्ध्यम्" = '४'
"प्रकारः" = 'यलोपः'
"विधिः" = ''
"सूत्रम्" = 'आपत्यस्य च तद्धितेऽनाति ।'
"प्रभावोदाहरणम्" = 'गार्गकम्'
"अभावोदाहरणम्" = 'गार्ग्यायणः'
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'हल्+ आपत्य-यकारः'
"प्रत्ययः/ विवक्षा" = 'क्य|च्वि'
"परिणामः" = 'य्-लोपः'
"प्रासिद्ध्यम्" = '४'
"प्रकारः" = 'यलोपः'
"विधिः" = ''
"सूत्रम्" = 'क्यच्व्योश्च ।'
"प्रभावोदाहरणम्" = 'वात्सीयति'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'बिल्वकादिः + कुक् + छ'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लुक्'
"प्रासिद्ध्यम्" = '३'
"प्रकारः" = 'छस्य लुक्'
"विधिः" = ''
"सूत्रम्" = 'बिल्वकादिभ्यश्छस्य लुक् ।'
"प्रभावोदाहरणम्" = 'बिल्व → बिल्वकीया (छ)→ बैल्वक (ण्वुल्)'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = '* + तृ'
"प्रत्ययः/ विवक्षा" = 'इष्ठन्|  इमनिच्| इयसुन्'
"परिणामः" = 'लुक्'
"प्रासिद्ध्यम्" = '३'
"प्रकारः" = 'इष्ठेमेयःसु आदेशः'
"विधिः" = ''
"सूत्रम्" = 'तुरिष्ठेमेयस्सु ।'
"प्रभावोदाहरणम्" = 'करिष्ठः, विजयिष्ठः, वहिष्ठः, दोहीयसी धेनुः ॥'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = '*'
"प्रत्ययः/ विवक्षा" = 'इष्ठन्|  इमनिच्| इयसुन्'
"परिणामः" = 'टेः लोपः'
"प्रासिद्ध्यम्" = '४'
"प्रकारः" = 'इष्ठेमेयःसु आदेशः'
"विधिः" = ''
"सूत्रम्" = 'टेः ।'
"प्रभावोदाहरणम्" = 'पटिष्ठः, पटिमा, पटीयान्'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'स्थूल दूर युव ह्रस्व क्षिप्र क्षुद्र'
"प्रत्ययः/ विवक्षा" = 'इष्ठन्|  इमनिच्| इयसुन्'
"परिणामः" = '''
यणादिपरस्य लोपः,
पूर्वस्य गुणः'''
"प्रासिद्ध्यम्" = '२'
"प्रकारः" = 'इष्ठेमेयःसु आदेशः'
"विधिः" = ''
"सूत्रम्" = 'स्थूलदूरयुवह्रस्वक्षिप्रक्षुद्राणां यणादिपरं पूर्वस्य च गुणः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = '''
प्रिय स्थिर स्फिर उरु बहुल गुरु वृद्ध तृप्र दीर्घ वृन्दारक
'''
"प्रत्ययः/ विवक्षा" = 'इष्ठन्|  इमनिच्| इयसुन्'
"परिणामः" = 'प्र स्थ स्फ वर् बंहि गर् वर्षि त्रप् द्राधि वृन्द'
"प्रासिद्ध्यम्" = '२'
"प्रकारः" = 'इष्ठेमेयःसु आदेशः'
"विधिः" = ''
"सूत्रम्" = 'प्रियस्थिरस्फिरोरुबहुलगुरुवृद्धतृप्रदीर्घवृन्दारकाणां प्रस्थस्फवर्बंहिगर्वर्षित्रब्द्राघिवृन्दाः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'बहु'
"प्रत्ययः/ विवक्षा" = 'इमनिच्| इयसुन्'
"परिणामः" = '''
बहु → भू
इष्ट्ःएमेयः → आदिलोपः'''
"प्रासिद्ध्यम्" = '३'
"प्रकारः" = 'इष्ठेमेयःसु आदेशः'
"विधिः" = ''
"सूत्रम्" = 'बहोर्लोपो भू च बहोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'बहु'
"प्रत्ययः/ विवक्षा" = 'इष्ठन्'
"परिणामः" = '''
यिट् आगमः।
बहु → भू'''
"प्रासिद्ध्यम्" = '३'
"प्रकारः" = 'इष्ठेमेयःसु आदेशः'
"विधिः" = ''
"सूत्रम्" = 'इष्ठस्य यिट् च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'ज्या'
"प्रत्ययः/ विवक्षा" = 'ईयसुन्'
"परिणामः" = 'ईयसुन् → आ'
"प्रासिद्ध्यम्" = '३'
"प्रकारः" = 'इष्ठेमेयःसु आदेशः'
"विधिः" = ''
"सूत्रम्" = 'ज्यादादीयसः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ' पृथुं मृदुं भृशं कृशं च दृढम्प रिपूर्वं वृढं  '
"प्रत्ययः/ विवक्षा" = 'इष्ठन्|  इमनिच्| इयसुन्'
"परिणामः" = 'ऋ → र'
"प्रासिद्ध्यम्" = '२'
"प्रकारः" = 'इष्ठेमेयःसु आदेशः'
"विधिः" = ''
"सूत्रम्" = '''
र ऋतो हलादेर्लघोः ।
(परिगणनम् वार्तिकेनोक्तम्)'''
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'ऋजु छन्दसि '
"प्रत्ययः/ विवक्षा" = 'इष्ठन्|  इमनिच्| इयसुन्'
"परिणामः" = 'ऋ → र'
"प्रासिद्ध्यम्" = '१'
"प्रकारः" = 'इष्ठेमेयःसु आदेशः'
"विधिः" = ''
"सूत्रम्" = 'विभाषर्जोश्छन्दसि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'एकाच्'
"प्रत्ययः/ विवक्षा" = 'इष्ठन्|  इमनिच्| इयसुन्'
"परिणामः" = '-(टि लोपः | नलोपः)'
"प्रासिद्ध्यम्" = '४'
"प्रकारः" = 'प्रकृतिभावः अङ्गस्य'
"विधिः" = ''
"सूत्रम्" = 'प्रकृत्यैकाच् ।'
"प्रभावोदाहरणम्" = 'स्रज् + इष्ठ → स्रजिष्ठ'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'राजन् युवन्'
"प्रत्ययः/ विवक्षा" = 'अक'
"परिणामः" = '-(टि लोपः | नलोपः)'
"प्रासिद्ध्यम्" = '२'
"प्रकारः" = 'प्रकृतिभावः अङ्गस्य'
"विधिः" = ''
"सूत्रम्" = ' प्रकृत्या ऽके राजन्यमनुष्ययुवानः। (वा)'
"प्रभावोदाहरणम्" = 'राजानक युवानक'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = '*+इन्'
"प्रत्ययः/ विवक्षा" = 'अण् अनपत्ये'
"परिणामः" = '-(टि लोपः | नलोपः)'
"प्रासिद्ध्यम्" = '४'
"प्रकारः" = 'प्रकृतिभावः अङ्गस्य'
"विधिः" = ''
"सूत्रम्" = 'इनण्यनपत्ये ।'
"प्रभावोदाहरणम्" = 'सांमार्जिनम्'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'गाथिन् विदथिन् केशिन् गणिन् पणिन्'
"प्रत्ययः/ विवक्षा" = 'अण्'
"परिणामः" = '-(टि लोपः | नलोपः)'
"प्रासिद्ध्यम्" = '२'
"प्रकारः" = 'प्रकृतिभावः अङ्गस्य'
"विधिः" = ''
"सूत्रम्" = 'गाथिविदथिकेशिगणिपणिनश्च ।'
"प्रभावोदाहरणम्" = 'गाथिन कैशिन'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = '* + संयोगः + इन्'
"प्रत्ययः/ विवक्षा" = 'अण्'
"परिणामः" = '-(टि लोपः | नलोपः)'
"प्रासिद्ध्यम्" = '३'
"प्रकारः" = 'प्रकृतिभावः अङ्गस्य'
"विधिः" = ''
"सूत्रम्" = 'संयोगादिश्च ।'
"प्रभावोदाहरणम्" = 'माद्रिन'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = '''
*+ अन्
(* + मन् अपवादः,
निपातनानि)'''
"प्रत्ययः/ विवक्षा" = 'अण्'
"परिणामः" = '-(टि लोपः | नलोपः)'
"प्रासिद्ध्यम्" = '५'
"प्रकारः" = 'प्रकृतिभावः अङ्गस्य'
"विधिः" = ''
"सूत्रम्" = 'अन् ।'
"प्रभावोदाहरणम्" = 'राजन् + अण् → राज्ञ् + अ (अल्लोपोऽनः) → राज्ञ'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = '*+ अन्'
"प्रत्ययः/ विवक्षा" = 'य्* अभावकर्मणोः'
"परिणामः" = '-(टि लोपः | नलोपः)'
"प्रासिद्ध्यम्" = '४'
"प्रकारः" = 'प्रकृतिभावः अङ्गस्य'
"विधिः" = ''
"सूत्रम्" = 'ये चाभावकर्मणोः ।'
"प्रभावोदाहरणम्" = 'सामनि साधुः → सामन्यः'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'आत्मन् अध्वन्'
"प्रत्ययः/ विवक्षा" = 'ख'
"परिणामः" = '-(टि लोपः | नलोपः)'
"प्रासिद्ध्यम्" = '३'
"प्रकारः" = 'प्रकृतिभावः अङ्गस्य'
"विधिः" = ''
"सूत्रम्" = 'आत्माध्वानौ खे ।'
"प्रभावोदाहरणम्" = 'आत्मने हित आत्मनीनः'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = '*+म्+अन् (-वर्मन्)'
"प्रत्ययः/ विवक्षा" = 'अण् अपत्ये'
"परिणामः" = '(टि लोपः | नलोपः)'
"प्रासिद्ध्यम्" = '३'
"प्रकारः" = 'प्रकृतिभावः अङ्गस्य'
"विधिः" = ''
"सूत्रम्" = 'न मपूर्वोऽपत्येऽवर्मणः ।'
"प्रभावोदाहरणम्" = 'सुषाम्णोर् अपत्यं सुषामः'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'ब्रह्मन्'
"प्रत्ययः/ विवक्षा" = 'अण् अनपत्ये'
"परिणामः" = '(टि लोपः | नलोपः)'
"प्रासिद्ध्यम्" = '२'
"प्रकारः" = 'प्रकृतिभावः अङ्गस्य'
"विधिः" = ''
"सूत्रम्" = 'ब्राह्मो'
"प्रभावोदाहरणम्" = 'ब्राह्मो गर्भः'
"अभावोदाहरणम्" = ''
"विवरणम्" = 'योगविभागः। ब्राह्म इति निपातनम्।'

[[data]]
"अङ्गम्" = 'ब्रह्मन्'
"प्रत्ययः/ विवक्षा" = 'अण् अपत्ये'
"परिणामः" = '- (टि लोपः | नलोपः)'
"प्रासिद्ध्यम्" = '३'
"प्रकारः" = 'प्रकृतिभावः अङ्गस्य'
"विधिः" = ''
"सूत्रम्" = 'अजातौ '
"प्रभावोदाहरणम्" = 'ब्राह्मणः'
"अभावोदाहरणम्" = ''
"विवरणम्" = 'योगविभागः'

[[data]]
"अङ्गम्" = 'कर्मन्'
"प्रत्ययः/ विवक्षा" = 'अण् ताच्छील्ये'
"परिणामः" = '(टि लोपः | नलोपः)'
"प्रासिद्ध्यम्" = '२'
"प्रकारः" = 'निपातनानि'
"विधिः" = ''
"सूत्रम्" = 'कार्मस्ताच्छील्ये ।'
"प्रभावोदाहरणम्" = 'कार्मः'
"अभावोदाहरणम्" = ''
"विवरणम्" = 'निपातनम्'

[[data]]
"अङ्गम्" = 'औक्षन्'
"प्रत्ययः/ विवक्षा" = 'अण् अनपत्ये'
"परिणामः" = '(टि लोपः | नलोपः)'
"प्रासिद्ध्यम्" = '१'
"प्रकारः" = 'निपातनानि'
"विधिः" = ''
"सूत्रम्" = 'औक्षमनपत्ये ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = 'निपातनम्'

[[data]]
"अङ्गम्" = 'दाण्दिनायन हास्तिनायन आथर्वणिक जैह्माशिनेय वासिनायनि भ्रौणहत्य धैवत्य सारव ऐक्ष्वाक मैत्रेय हिरण्मय'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = '१'
"प्रकारः" = 'निपातनानि'
"विधिः" = ''
"सूत्रम्" = 'दाण्डिनायनहास्तिनायनाथर्वणिकजैह्माशिनेयवाशिनायनिभ्रौणहत्यधैवत्यसारवैक्ष्वाकमैत्रेयहिरण्मयानि ।'
"प्रभावोदाहरणम्" = 'दाण्दिनायन हास्तिनायन आथर्वणिक जैह्माशिनेय वासिनायनि भ्रौणहत्य धैवत्य सारव ऐक्ष्वाक मैत्रेय हिरण्मय'
"अभावोदाहरणम्" = ''
"विवरणम्" = 'निपातनम्'

[[data]]
"अङ्गम्" = '''
ऋत्व्य वास्त्व्य वास्त्व माध्वी हिरण्यय
छन्दसि'''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = '१'
"प्रकारः" = 'निपातनानि'
"विधिः" = ''
"सूत्रम्" = 'ऋत्व्यवास्त्व्यवास्त्वमाध्वीहिरण्ययानि च्छन्दसि ।'
"प्रभावोदाहरणम्" = 'ऋत्व्य वास्त्व्य वास्त्व माध्वी हिरण्यय'
"अभावोदाहरणम्" = ''
"विवरणम्" = 'निपातनम्'
