[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तद्धितः ञित् णित्'
"परिणामः" = 'आदिवृद्धिः'
"प्रासिद्ध्यम्" = '५'
"सूत्रम्" = 'तद्धितेष्वचामादेः ।'
"प्रभावोदाहरणम्" = 'गर्ग + यञ् - गार्ग्यः। दाक्षिः (दक्ष + इञ्), प्लाक्षिः, उपगु + अण् = औपगवः '
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तद्धितः कित्'
"परिणामः" = 'आदिवृद्धिः'
"प्रासिद्ध्यम्" = '५'
"सूत्रम्" = 'किति च ।'
"प्रभावोदाहरणम्" = 'फक् → नाडायन, आक्षिकः। शालाकिकः।'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'देविका शिंशपा दित्यवाट् दीर्घसत्र श्रेयस'
"प्रत्ययः/ विवक्षा" = 'ञित् णित् कित्'
"परिणामः" = 'आत्‌ आदौ'
"प्रासिद्ध्यम्" = '२'
"सूत्रम्" = 'देविकाशिंशपादित्यवाड्दीर्घसत्रश्रेयसाम् आत्‌ ।'
"प्रभावोदाहरणम्" = 'देविकायां भवमुदकं दाविकम् उदकम्।'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'केकय मित्त्रयु प्रलय'
"प्रत्ययः/ विवक्षा" = 'ञित् णित् कित्'
"परिणामः" = 'आदिवृद्धिः, य → इय'
"प्रासिद्ध्यम्" = '३'
"सूत्रम्" = 'केकयमित्त्रयुप्रलयानां यादेरियः ।'
"प्रभावोदाहरणम्" = 'केकयस्य अपत्यम् कैकेयः। प्रालेयम् (= प्रलयादागत)'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'उपपदान्ते, आदिमस्वरात् प्राग् {य्|व्}'
"प्रत्ययः/ विवक्षा" = 'ञित् णित् कित्'
"परिणामः" = 'ऐय् | औव् आदेशः'
"प्रासिद्ध्यम्" = '५'
"सूत्रम्" = 'न य्वाभ्यां पदान्ताभ्याम् पूर्वौ तु ताभ्यामैच् ।'
"प्रभावोदाहरणम्" = 'व्यसने भवम् वैयसनम्। व्याकरणमधीते वैयाकरणः। स्वश्वस्य अपत्यम् सौवश्वः।'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'द्वार। स्वर। व्यल्कश। स्वस्ति। स्वर्। स्फ्यकृत। स्वादुमृदु। श्वन्। स्व।'
"प्रत्ययः/ विवक्षा" = 'ञित् णित् कित्'
"परिणामः" = 'ऐय् | औव् आदेश आदिस्वरपूर्वस्य'
"प्रासिद्ध्यम्" = '३'
"सूत्रम्" = 'द्वारादीनां च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'असमासे न्यग्रोधः'
"प्रत्ययः/ विवक्षा" = 'ञित् णित् कित्'
"परिणामः" = 'ऐय् | औव् आदेशः'
"प्रासिद्ध्यम्" = '२'
"सूत्रम्" = 'न्यग्रोधस्य च केवलस्य ।'
"प्रभावोदाहरणम्" = 'नैयग्रोधश्चमसः'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'प्रतिकर्मसूचकम्'
"प्रत्ययः/ विवक्षा" = 'ञित् णित् कित्'
"परिणामः" = 'आदिवृद्धिः'
"प्रासिद्ध्यम्" = '३'
"सूत्रम्" = 'न कर्मव्यतिहारे ।'
"प्रभावोदाहरणम्" = 'व्यावक्रोशी, व्यावलेखी, व्याववर्ती, व्यावहासी'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'स्वागत। स्वध्वर। स्वङ्ग। व्यङ्ग। व्यड। व्यवहार। स्वपति। '
"प्रत्ययः/ विवक्षा" = 'ञित् णित् कित्'
"परिणामः" = 'आदिवृद्धिः'
"प्रासिद्ध्यम्" = '३'
"सूत्रम्" = 'स्वागतादीनां च ।'
"प्रभावोदाहरणम्" = 'स्वागतम् इत्याह स्वागतिकः। स्वध्वरेण चरति स्वाध्वरिकः। स्वङ्गस्य अपत्यम् स्वङ्गिः।'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'श्वन्.*'
"प्रत्ययः/ विवक्षा" = 'इञि'
"परिणामः" = 'आदिवृद्धिः'
"प्रासिद्ध्यम्" = '३'
"सूत्रम्" = 'श्वादेर् इञि ।'
"प्रभावोदाहरणम्" = 'श्वभस्त्रस्य अपत्यम् श्वाभस्त्रिः। श्वादंष्ट्रिः।'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'पदान्तस्यान्यतरस्याम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'उत्तरपदस्य ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'अवयवादृतोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'सुसर्वार्धाज्जनपदस्य ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'दिशोऽमद्राणाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'प्राचां ग्रामनगराणाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'संख्यायाः संवत्सरसंख्यस्य च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'वर्षस्याभविष्यति ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'परिमाणान्तस्यासंज्ञाशाणयोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'जे प्रोष्ठपदानाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'हृद्भगसिन्ध्वन्ते पूर्वपदस्य च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'अनुशतिक। अनुहोड। अनुसंवरण। अनुसंवत्सर। अङ्गारवेणु। असिहत्य। वध्योग। पुष्करसद्। अनुहरत्। कुरुकत। कुरुपञ्चाल। उदकशुद्ध। इहलोक। परलोक। सर्वलोक। सर्वपुरुष। सर्वभूमि। प्रयोग। परस्त्री। राजपुरुषात् ष्यञि। सूत्रनड। आकृतिगणः'
"प्रत्ययः/ विवक्षा" = 'ञित् णित् कित्'
"परिणामः" = 'उभय-वृद्धिः'
"प्रासिद्ध्यम्" = '४'
"सूत्रम्" = 'अनुशतिकादीनां च ।'
"प्रभावोदाहरणम्" = 'पाञ्चभौतिकम्'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'देवताद्वंद्वे च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'नेन्द्रस्य परस्य ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'दीर्घाच्च वरुणस्य ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'प्राचां नगरान्ते ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'जङ्गलधेनुवलजान्तस्य विभाषितमुत्तरम्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'अर्धात्‌ परिमाणस्य पूर्वस्य तु वा ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'नातः परस्य ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'प्रवाहणस्य ढे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'तत्प्रत्ययस्य च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'नञः शुचीश्वरक्षेत्रज्ञकुशलनिपुणानाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'यथातथयथापुरयोः पर्यायेण ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = ''
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''
