name: Index Hugo site

on:
  push:
    branches: [ 'gh-pages' ]
  workflow_dispatch:
    inputs:
      logLevel:
        default: 'warning'

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4.4.1
    - name: Checkout
      id: checkout
      uses: actions/checkout@gh-pages
      with:
        submodules: false
        fetch-depth: 1
      