name: Index site

on:
  push:
    branches: [ 'gh-pages' ]
  workflow_dispatch:

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4.4.1
    - name: Checkout
      id: checkout
      uses: actions/checkout@gh-pages
      with:
        submodules: false
        fetch-depth: 1
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Or your desired Node.js version

    - name: Install Pagefind (if not in package.json)
      run: npm install -g pagefind

    - name: Run Pagefind
      run: npx pagefind --source .
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
        force_orphan: true # stop git history growth     